### ISSUE TITLE
Question: Problem with numpy wrappers for functions with char* parameters?

### ISSUE THREAD

**Issue by g40** [swig/swig#1005]
Not sure if this is a bug or a misunderstanding on my part. Any help much appreciated.

[Edit] %apply definitions changed as per Flexo's advice on SO.
```
// integer
%apply (int* INPLACE_ARRAY1,int DIM1) {(int* buffer,int bytes)}
// signed 8
%apply (char* INPLACE_ARRAY1,int DIM1) {(char* buffer,int bytes)}
// unsigned 8
%apply (unsigned char* INPLACE_ARRAY1,int DIM1) {(unsigned char* buffer,int bytes)}
```

functions `average_i` and `average_u8` now work as expected. However `double average_s8(char* buffer,int bytes)` still fails with

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    avg = example.average_s8(np_i8)
TypeError: average_s8 expected 2 arguments, got 1
```

Where am I going wrong? TAIA.

A concise project demonstrating the issue is here: github.com/g40/swig8bit.git

**Comment by ojwb** [comment]
Looks like the issue here is that `numpy.i` only defines typemaps for `signed char` and `unsigned char` but not for `char` - you either need to use `signed char` explicitly (which I'd recommend as that way you get the same semantics regardless of whether `char` is signed or unsigned by default on the architecture in use), or else add something like `%numpy_typemaps(char     , NPY_BYTE    , int)` to your interface file (that assumes `char` is signed, which it is on some architectures, but not on ARM for example).  Doing either fixes your problem.
