### ISSUE TITLE
SWIG_VERSION is not defined on SWIGJAVA

### ISSUE THREAD

**Issue by luav** [swig/swig#1050]
`SWIG_VERSION` should be always defined if either SWIG preprocessor or parser are used, but it does not defined on the wrapper compilation for Java.

Consider the following code:
```c++
template <typename LinksT>
class NodeI {
public:
#ifdef SWIG
	%ignore owners;
#endif // SWIG
	Owners<links_type>  owners;
// Note: SWIG_VERSION is not defined for SWIGJAVA
#if defined(SWIG_VERSION)
	Owners<links_type>& owncs() noexcept  { return owners; }
#endif // SWIG_VERSION
	...
}
```
The produced wrapper is compiled fine for Python, Ruby Octave, etc. except for Java, yielding the following error for Java:
```
error: 'class daoc::NodeI<std::vector<daoc::Link<float, false>, std::allocator<daoc::Link<float, false> > > >' has no member named 'owncs'
 NodeI< vector< daoc::Link< float,false > > >::links_type > *) &(arg1)->owncs();
```

As a workaround I had to:
```c++
#if defined(SWIG_VERSION) || defined(SWIGJAVA)
	Owners<links_type>& owncs() noexcept  { return owners; }
#endif // SWIG_VERSION
```
Which is not the designed behavior of SWIG.

When the macros for  any language is defined (`SWIGJAVA`, `SWIGPYTHON`, ...) it makes sense to very internally whether the `SWIG_VERSION` is defined and generate compilation `#error` otherwise.

*Note:* this issue might exist not only for Java.

*Environment:*  
SWIG Version 3.0.12  
Compiled with g++ [x86_64-pc-linux-gnu]  
Configured options: +pcre

**Comment by luav** [comment]
The same problem for SWIGCSHARP, but not for all other scripting languages without the static types.

**Comment by ojwb** [comment]
> `SWIG_VERSION` should be always defined if either SWIG preprocessor or parser are used, but it does not defined on the wrapper compilation for Java.

By "wrapper compilation" do you mean generating the wrapper using SWIG?

If so, I can't reproduce the reported problem:

```
$ cat test.i
%module test
#ifdef SWIG_VERSION
#warning SWIG_VERSION is defined
#else
#error SWIG_VERSION is not defined
#endif
$ ../preinst-swig -php test.i
test.i:3: Warning 204: CPP #warning, "SWIG_VERSION is defined".
$ ../preinst-swig -java test.i
test.i:3: Warning 204: CPP #warning, "SWIG_VERSION is defined".
$ ../preinst-swig -csharp test.i
test.i:3: Warning 204: CPP #warning, "SWIG_VERSION is defined".
```

If you mean compiling the generated code with a C/C++ compiler - it's actually explicitly documented that SWIG_VERSION is **not** defined in the generated wrapper file - see §1.8 "Backwards compatibility" in Doc/Manual/Preface.html :

> Note: The version symbol is not defined in the generated SWIG wrapper file. The SWIG preprocessor has defined SWIG_VERSION since SWIG-1.3.11.

However, it seems it is actually defined for some languages, probably due to 40828f8cc52400ceace324a102d79364b3510c0c which looks like it was added in 1.3.32 (assuming the old tags got migrated to git accurately) but not all (at least Java, C# and D don't seem to).

It doesn't seem helpful to stop defining this in the generated wrapper given we have for so long even though the manual says it isn't defined, so I suppose we should define it for all languages and update the docs to align with that.

**Comment by ojwb** [comment]
@wsfulton Does that sound good to you?  To be clear, I'm suggesting we define `SWIG_VERSION` in the generated SWIG C/C++ wrapper file for all target languages (rather than just some), add a testcase to enforce that, and to document that this is the case (currently the docs say it isn't, but actually it is for most target languages).

The alternative is to make reality match the docs, which potentially breaks usage relying on the current behaviour.

**Comment by wsfulton** [comment]
The conditionals should be used at SWIG parse time, not C++ compilation time. It is really important for users to distinguish between SWIG parsing and C++ parsing and SWIG is the main macro for that and that must not change.

As documented, SWIG_VERSION ought not be defined in the wrappers, nor should SWIG, SWIGJAVA, etc. There is nothing documented about these being available. Unfortunately this is now not the case. The correct practice is to use these conditionals at SWIG parse time. As this is not enforced and these macros are defined in some languages, we'd better make this consistent and document what is available and that using these conditionals at SWIG parse time is 'good practice' and using them at C++ compilation time in the wrappers is bad practice. Why you might ask? Full control of the generated code is possible at SWIG parse time and adding to the already bloated wrappers has negative consequences around unnecessary complexity and slower C++ compilations.  

Sot the way forward is:

SWIG - only defined during SWIG parsing.
SWIG_VERSION - defined during both SWIG parsing and in the wrappers for the C++ compiler.
SWIGJAVA, SWIGPYTHON etc - defined during both SWIG parsing and in the wrappers for the C++ compiler. 

We can't have two version macros, so I want SWIGVERSION removed. Having that really is a confusing mistake.

BTW, https://github.com/swig/swig/blob/90aa3f75ba0d4d1ac6984be31f3711968f590c4c/Doc/Manual/Php.html#L1226-L1232 should be modified to use 'good practice'.

**Comment by ojwb** [comment]
Sticking that code in `test.i` I get:

```
$ ../preinst-swig -php -E test.i|tail



  if ($error == FAILURE)

  {
    throw Swig::DirectorMethodException();
  }
}
%endoffile
```

So it is a SWIG-time conditional already and I don't understand what you're complaining about here.

**Comment by wsfulton** [comment]
Oh so sorry, my mental parsing used %{ ... %} instead of { ... } which would turn it into a C compile time conditional. Please ignore as it is perfectly correct as documented.

**Comment by ojwb** [comment]
Looking at fixing this, I think I understand why `SWIGVERSION` is defined - `Lib/typemaps/swigmacros.swg` has:

```
#if SWIG_VERSION
%insert("header") {
%define_as(SWIGVERSION,  SWIG_VERSION)
%#define SWIG_VERSION SWIGVERSION
}
#endif
```

Marcelo presumably struggled to come up with something like this but which actually worked:

```
%define_as(SWIG_VERSION,  SWIG_VERSION)
```

(The above expands to something like `#define 0x040100 0x040100`)

I also failed to find a good way to achieve this - @wsfulton any brilliant ideas?  If not I propose to just undefine `SWIGVERSION` again by adding this to the current code:

```
%#undef SWIGVERSION
```

**Comment by ojwb** [comment]
I updated my WIP branch for this and pushed it - it looks like a number of languages currently fail to define `SWIG_VERSION` so CI should  show us exactly which those are:

https://github.com/swig/swig/actions/runs/3154442749

The new testcase doesn't currently check `SWIG` or `SWIGJAVA`, etc.

**Comment by ojwb** [comment]
I've addressed the SWIG/PHP blockers for the release, so I'll sort out this next.

**Comment by ojwb** [comment]
I've updated the patch.

I haven't added an automated test that the target-language-specific define (`SWIGJAVA` for Java) is actually defined as I didn't see a way to do so that seemed very satisfactory.  Best option I came up with was something like:

```
#if defined SWIGPERL
#elif defined SWIGPHP
#elif defined SWIGPYTHON
// ...
#else
#error No target language SWIG define detected
#endif
```

@wsfulton Thoughts?

**Comment by ojwb** [comment]
I came up with a way to test exactly one target-language-specific macro is defined at both SWIG-time and in the generated wrapper.  It requires a single list of these macros (in `Examples/test-suite/preproc_predefined.h`) but I don't really see a way to avoid that, and the `preproc_predefined` testcase will fail for a new target language with:

```
Did not detect exactly one target-language-specific macro defined at SWIG time.
```
and
```
Did not detect exactly one target-language-specific macro defined in the generated wrapper.
```
both pointing to this header file which starts with the comment:
```
/* This list will need updating when new target languages are added. */
```
I think that makes it clear to someone adding a new target language what the problem is and what needs doing.

**Comment by wsfulton** [comment]
Given the problem in #2395 I tried looking for some preprocessor tricks but failed unfortunately. I also thought that autoconf could solve it, but there is no obvious way to convert PACKAGE_VERSION into a hex version we need.

I think the best solution is to generate SWIG_VERSION from the SWIG executable instead of from a swigversion.swg by providing a helper function that all the target languages must call. So, for example, python.cxx would be changed as follows:

```diff
diff --git a/Source/Modules/python.cxx b/Source/Modules/python.cxx
index a8175eb0e..8fb5c729f 100644
--- a/Source/Modules/python.cxx
+++ b/Source/Modules/python.cxx
@@ -586,8 +586,7 @@ public:
     methods_proxydocs = NewString("");
 
     Swig_banner(f_begin);
-
-    Printf(f_runtime, "\n\n#ifndef SWIGPYTHON\n#define SWIGPYTHON\n#endif\n\n");
+    Swig_obligatory_macros(f_runtime, "PYTHON");
 
     if (directorsEnabled()) {
       Printf(f_runtime, "#define SWIG_DIRECTORSdiff --git a/Source/Modules/python.cxx b/Source/Modules/python.cxx
index a8175eb0e..8fb5c729f 100644
--- a/Source/Modules/python.cxx
+++ b/Source/Modules/python.cxx
@@ -586,8 +586,7 @@ public:
     methods_proxydocs = NewString("");
 
     Swig_banner(f_begin);
-
-    Printf(f_runtime, "\n\n#ifndef SWIGPYTHON\n#define SWIGPYTHON\n#endif\n\n");
+    Swig_obligatory_macros(f_runtime);
 
     if (directorsEnabled()) {
       Printf(f_runtime, "#define SWIG_DIRECTORS\n");
\n");
```
and the new `Swig_obligatory_macros` would generate the macros for SWIGPYTHON and SWIG_VERSION into f_runtime. This would be near the top of the generated code after the begin section, which seems like a more sensible place than where it currently gets generated.

**Comment by wsfulton** [comment]
This is the test I had in mind:
```diff
diff --git a/Examples/test-suite/preproc_predefined.i b/Examples/test-suite/preproc_predefined.i
index 7db5352f5..63aab6c89 100644
--- a/Examples/test-suite/preproc_predefined.i
+++ b/Examples/test-suite/preproc_predefined.i
@@ -10,6 +10,16 @@
 #endif
 %}
 
+%define %generate_swig_version_from_preprocessor()%#define SWIG_VERSION_FROM_SWIG_PREPROCESSOR SWIG_V
+%insert("header") {
+%generate_swig_version_from_preprocessor()
+}
+%insert("header") %{
+#if SWIG_VERSION != SWIG_VERSION_FROM_SWIG_PREPROCESSOR
+# error SWIG_VERSION in SWIG preprocessor does not match SWIG_VERSION from C preprocessor
+#endif
+%}
+
 /* Test that SWIGVERSION is NOT defined at SWIG-time or in the wrapper.
  * It used to be defined in the wrapper as a side-effect of how SWIG_VERSION
  * was defined in the wrapper but was never documented and is redundant.
```
I tried splitting the macro name, but missed that trick. I wonder if it behaving like this is not a bug (not important for now though). Unfortunately the output with what you have contains some cruft that is not really acceptable:
```swig
/*@SWIG:../../../Lib/typemaps/swigversion.swg,11,%define_swig_version_@*/#define SWIG_\
VERSION 0x040100 /*@SWIG@*/
```
so I'd rather implement it by generating it from the swig executable. Would you care to implement it in next day if you have nothing else for the release? If not, I'll do it in a day or two. BTW, I tried replacing the `%define %define_swig_version` with a `#define` but the behaviour was quite different and I got nowhere.

**Comment by ojwb** [comment]
My trick working might be a bug, but it's SWIG-specific preprocessor stuff so I guess we get to define what it should do...

I think either your cut and paste truncated the long line or there's a typo - `SWIG_V` should presumably be `SWIG_VERSION`?

Checking the value is the same at both SWIG-time and compile-time is nice, but I think also ought to check something like `SWIG_VERSION >= 0x040100` (can be either only at SWIG-time or only at compile time since we're also checking equality) - without that it wouldn't catch cases such as if both are defined to a non-numeric value.

I think it's best you implement generating from the SWIG executable as you've more idea what you have in mind and I'm not short of things to do already.

**Comment by wsfulton** [comment]
> I think either your cut and paste truncated the long line or there's a typo - SWIG_V should presumably be SWIG_VERSION?

Yes, sorry, annoying feature of git that truncates stdout :(

**Comment by ojwb** [comment]
@wsfulton I think that's your pager rather than git - most git commands pipe their output to your configured pager automatically.

A pager should check if stdout is a terminal and if it isn't just act like `cat`, so redirecting or piping git's output should avoid any pager-related formatting problems.

I usually do `git diff|xclip` then I can middle click paste into my browser and get the diff without any formatting problems (just checked and this definitely handles lines wider than my terminal).
