### ISSUE TITLE
Type aliases (produced by `typedef` and `using`) are not available in the generated interface

### ISSUE THREAD

**Issue by luav** [swig/swig#1069]
SWIG processes `typedef` and `using` specifiers internally for the type equivalence rules, but the aliased types are not available to the end-user of the wrapper interface:
Interface file `alias.i`:
```c++
%module alias

%inline %{
struct SType {
	int val;
};

using USType = SType;
typedef SType  TSType;

int val(TSType tv)  { return tv.val; }
%}

%{
	USType a;
	TSType b = a;
%}
```
Lets look at the available end-user interface of the wrapper in Python:
```sh
>>> import alias; [nm for nm in dir(alias) if not nm.startswith('_')]
['SType', 'SType_swigregister', 'val']
```
So, `USType` and `TSType` are not available, which inconvenient even for simple types. Typically libraries provide semantic naming with possibly the same underlying physical types. For example `Id`, and 'Weight' might have `unsigned` type, but it would be nice to provide them by the meaningful name. 

Note that `alias_wrap.cxx` contains the aliases in the equivalence table:
```c++
static swig_type_info _swigt__p_SType = {"_p_SType", "SType *|TSType *|USType *", 0, 0, (void*)0, 0};
```
So, it should not be hard to make them available in the end-user interface.

For the templates this *drawback* becomes a real **bug**, see #1058, because type aliases are used there mainly to reduce the number of template parameters substituting the constexpr and producing a new template for the further usage.

*Environment:*
SWIG Version 4.0.0
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

**Comment by n8vm** [comment]
Having the same issue...

**Comment by wsfulton** [comment]
This is by design and is documented, although arguably not very clearly in https://swig.org/Doc4.1/SWIG.html#SWIG_nn20 ...

> typedef definitions appearing in a SWIG interface are not propagated to the generated wrapper code

So only one name can be used in the target language. You can change the name available in the target language using %rename if you are not happy with the original C++ name (non-primitive C/C++ types only). For example you could use the following so that `USType` is the name to use in the target language instead of `SType`:
```swig
%rename(USType) SType;
```

The `swig_type_info` you showed is for use in the runtime type checker and is an essential part for handling C/C++ type info and not exposed to the target language.
