### ISSUE TITLE
Namespace declaration via `using` is ignored by SWIG

### ISSUE THREAD

**Issue by luav** [swig/swig#1093]
Namespace declaration via `using` is ignored by SWIG at least in the SWIG directives.
**Note:** This is the regression bug that appeared during the last month, it seems after the 96e9941, see #1063 for details.

The interface file `usingclass.i`:
```c++
%module usingclass

%inline %{
namespace nsd {

// Value without the assignment operator
struct Wrapper {
	void *ptr;
	
	Wrapper(): ptr(nullptr)  {}
	Wrapper(const Wrapper&)=delete;
	Wrapper(Wrapper&&)=default;
};

template <bool COND=false>
struct Data {
	Wrapper wr;
	int val;

	Data(): wr(), val(COND)  {}
	Data(const Data&)=delete;
	Data(Data&&)=default;
};

}  // nsd

using namespace nsd;
%}

using namespace nsd;
%immutable Data::wr;  // Compilation fails, but compiled fine for "nsd::Data::wr"
%template(DataTrue) Data<true>;
```
Compilation:
```sh
$ swig -v -c++ -python usingclass.i
...
$ g++ -std=c++14 -fPIC -Wfatal-errors -c ./usingclass_wrap.cxx -I/usr/include/python2.7 && g++ -shared usingclass_wrap.o -o _usingclass.so
./usingclass_wrap.cxx: In function ‘PyObject* _wrap_DataTrue_wr_set(PyObject*, PyObject*)’:
./usingclass_wrap.cxx:3471:24: error: use of deleted function ‘constexpr nsd::Wrapper& nsd::Wrapper::operator=(const nsd::Wrapper&)’
   if (arg1) (arg1)->wr = *arg2;
                        ^
compilation terminated due to -Wfatal-errors.
```
But the compilation is successful for the *explicit namespace specification* (i.e. the `using namespace` declaration was ignored by SWIG in the example above):
```c++
%immutable nsd::Data::wr;
%template(DataTrue) Data<true>;
```

**Environment:**
$ swig -version
SWIG Version 4.0.0
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

To be more precise about the used SWIG version:
commit 6077b808f737c1d05df158e31ce50f9189bf9506
Author: William S Fulton <wsf@fultondesigns.co.uk>
Date:   Mon Sep 11 23:18:55 2017 +0100

**Comment by wsfulton** [comment]
In swig-3.0.12, `%template(DataTrue) Data<true>` ignored the using directive and instantiated the template in the global namespace and not in the nsd namespace. The commits for swig-4.0.0 fix a pile of subtle namespace bugs and problems for %template including this. So in swig-3.0.12, the fully qualified template was (incorrect): `Data<true>` and in swig-4.0.0 it is (correct): `nsd::Data<true>`.

The SWIG feature name matching rules are complex, but they will match a fully qualified name (%immutable is a feature). SWIG features do not follow using declarations and using directives (I don't see how this can be supported, but will explain on request if this isn't clear). `%immutable Data::wr` quite correctly does not match ns::Data::wr in swig-4.0.0. It did incorrectly match in swig-3.0.12 because the template was instantiated in the wrong namespace. You will have to correct your code in 4.0.0. If you need to support both versions of swig, just put in `%immutable Data::wr` and `%immutable ns::Data::wr` in your interface file.

**Comment by wsfulton** [comment]
You may want to look at the symbol tables in both versions with the `-debug-csymbol` command line option.
