### ISSUE TITLE
%newobject with director in jni

### ISSUE THREAD

**Issue by leozzyzheng** [swig/swig#1104]
I'm using director for callback class in jni, but there are some object pointer passed directly to java object. In general, I need copy data from those object pointer and pass it to java object, so I think %newobject is what I need.

But I found `%newobject MyCallBackClass::CallBackFunc(const CustomClass* object);` won't make director function to `new` a `CustomClass` instance to copy data from `object`, it still pass the `object` pointer directly to java object. Is there wrong with my usage?

And btw, if `MyCallBackClass` is only used to be extended for call back, could I make all implement of callback functions empty? They are useless in this case I think.

**Comment by wsfulton** [comment]
`%newobject` is for return types from functions. A couple of options for you:
1. Change the signature to pass by value rather than pointer: `MyCallBackClass::CallBackFunc(CustomClass object);`
2. Write typemaps which effectively do the same as if passing by value. I just copied the ones in java.swig and adapted. Try these:
```swig
%typemap(javadirectorin) CustomClass *object
  "($jniinput == 0) ? null : new $javaclassname($jniinput, true)"
%typemap(directorin,descriptor="L$packagepath/$javaclassname;") CustomClass *object
%{ $input = 0;
   *(($&1_ltype)&$input) = new $*1_ltype(*$1); %}
```

**Comment by leozzyzheng** [comment]
Thanks, the second option is just what I have done. :)

**Comment by ojwb** [comment]
Can this be closed now then?

**Comment by leozzyzheng** [comment]
Sure, thanks!
