### ISSUE TITLE
C++ attribute specifier sequence support

### ISSUE THREAD

**Issue by reyreaud-l** [swig/swig#1158]
Hi,

Is c++ [attribute specifier sequence](http://en.cppreference.com/w/cpp/language/attributes) support considered?

I have a quick fix done in a fork (bypass everything between '[[' and ']]' ) and would like to know if swig was considering adding support for it so that I would open a PR.

**Comment by wsfulton** [comment]
Support for this is missing, see http://swig.org/Doc3.0/CPlusPlus11.html#CPlusPlus11_attributes. Support for this would be great to add to SWIG so please do submit your pull request. Could you update those docs with the pull request in the repo, you can find them at: https://github.com/swig/swig/blob/master/Doc/Manual/CPlusPlus11.html.

I don't know how you have implemented this, but the implementation ought to create a new token in the scanner and then the tokens would be used in the appropriate valid places in the parser. I'd appreciate a new testcase in the test-suite to show the support and include tests like [[ inside a string showing they don't get swallowed.

**Comment by ReDucTor** [comment]
As language support becomes a painful thing each new standard is it worth looking at using clang for parsing?

**Comment by wsfulton** [comment]
This has been brought up before, but there are some fundamental problems which would need sorting out. For example, SWIG does not always following #include and SWIG works without full type information. I don't know the internals of Clang, but if this is possible, it would be great to utilize a well estabilished parser Clang or gcc. Anyone with intimate knowledge of these two tools should open a separate ticket with a serious proposal to discuss.

**Comment by ReDucTor** [comment]
Created #1159 to discuss this further

**Comment by reyreaud-l** [comment]
According to cppreference, [attr specifier sequences](http://en.cppreference.com/w/cpp/language/attributes) are used to indicate information to the compiler. For example putting `[[noreturn]]` in a function declaration to indicate to the compiler that the function will exit the program.

What would SWIG do with such information ?
Maybe we could just bypass the `[[...]]` in the scanner and not produce any token ?

**Comment by wsfulton** [comment]
SWIG is a compiler, so to control SWIG via attributes would be in scope of what attributes are designed for in my opinion. 

I can't see how any of the standard attributes can be usefully used, but there are some non-standard gnu attributes that could control's SWIG code generation, such as gnu:nonnull, gnu:nothrow, gnu:visibility. 

The main use would be to open up the possibility to adopt these attributes as an inline alternative to the SWIG syntax for features via an attribute namespace called 'swig'. For example a variable called be made immutable for wrapping via either one of these approaches:
```c++
#if defined(SWIG)
%feature("immutable") Foo::var;
#endif
struct Foo {
  int var;
};

struct Foo {
  [[swig::immutable]] int var;
};
```
or attributes attached to functions, such as the 'new' feature (also known as %newobject):
```c++
#if defined(SWIG)
%feature("new") createFoo;
#endif
Foo * createFoo(int v) { return new Foo{v}; }

[[swig::new]] Foo * createFoo(int v) { return new Foo{v}; }
```
For all these possibilities, attributes would need to be properly parsed and tokenised by the scanner so that they could be fed to the parser.

**Comment by ojwb** [comment]
`[[noreturn]]` is standard and might be useful for code generation.

**Comment by JessHolle** [comment]
SWIG is the _perfect_ place for generalized attribute use well beyond the C++ compiler!

Examples: one could denote that there are certain threading considerations for a given virtual method -- and then translate that into appropriate metadata in other languages.  For instance one might have something like `[[worker_thread]]` translate into `@WorkerThread` when generating Java code for Android.

How would this be accomplished currently?  I don't see a good solution.  Am I just overlooking it?  SWIG doesn't parse doxygen comments to allow this sort of generation to be done based on specific documentation comments, right?

The closest analogy for me is working on annotation processors for Java. These hinge on Java class and method signatures _including_ annotations (and Javadoc comments, though these are a last resort in my opinion, as they need to be parsed to get at any detail) and allow one to generate code (etc) on that basis.  Annotations (Java's "generalized attributes") play a _huge_ role here -- and I believe C++ generalized attributes should be equally important to SWIG.

**Comment by torokati44** [comment]
All I want is for SWIG to simply skip, ignore, and forget about anything between `[[` and `]]`.
At least it wouldn't get in the way all the time, even if it can't do anything useful with them... :/

I wanted to
```
#ifdef SWIG
  #define MY_ATTRIBUTE(x)
#else
  #define MY_ATTRIBUTE(x) [[x]]
#endif
```
and
```
MY_ATTRIBUTE(something) void foo();
```
my way out of this, but guess what: because of an unrelated issue, the definition of this macro isn't carried over from the header it is in to the problematic piece of code... :'(

Why doesn't SWIG invoke `cpp`, that works correctly?

**Comment by ojwb** [comment]
I haven't checked, but presumably `[[` and `]]` are tokens in which case `Source/CParse/cscanner.c` needs to generate them.

Then the grammar in `Source/CParse/parser.y` needs to have new and adjusted rules which match attribute specifiers using those tokens.  Those rules can probably just have empty actions (at least for now) since (as discussed above) parsing but ignoring attribute specifiers would be a step forwards in itself.

A recurring problem with extending SWIG's grammar is that adding support for something introduces conflicts into the grammar but I suspect here that won't be a big issue as there are new tokens delimiting the additions to the grammar.

**Comment by jmarrec** [comment]
thanks @ojwb . I have opened a draft PR with my failed attempt at this: https://github.com/swig/swig/pull/2286. I'm hoping someone can help put it through the finish line by taking it over or nudging me in the right direction

**Comment by jmarrec** [comment]
@ojwb and @wsfulton thanks for getting this merged. Is there any plan to tag a new release soon? I see 4.0.2 was more than a year ago.

**Comment by wsfulton** [comment]
Hopefully in a month or so, check out https://github.com/swig/swig/milestone/3
