### ISSUE TITLE
Is it possible to use %typemap(javainterfaces) and %interface() together?

### ISSUE THREAD

**Issue by nssang00** [swig/swig#1188]
%typemap(javaimports) Listener "import java.util.EventListener;";
%typemap(javainterfaces) Listener "EventListener";
**%interface_impl(Listener);**

class Listener
{
protected:
	Listener() {};
	virtual ~Listener() {};
};

class DataReaderListener : public Listener
{
}
##################
# Expected results
##################
==========Listener.java
import java.util.EventListener;

public interface Listener **implements EventListener** {
	long Listener_GetInterfaceCPtr();
}

##################
# Actual results
##################
===========Listener.java
import java.util.EventListener;

public interface Listener {
	long Listener_GetInterfaceCPtr();
}

===========ListenerSwigImpl.java

import java.util.EventListener;

public class ListenerSwigImpl implements EventListener {
	...
}

**Comment by ojwb** [comment]
`%interface_impl` is implemented as a macro and one of this things it does is

```
%rename("%sSwigImpl") CTYPE;
```

where `CTYPE` is the first argument passed to the macro, i.e. `Listener` in your case.

So that's why you get what you get.  With git master you'd now get

```
ListenerSwigImpl.java:public class ListenerSwigImpl implements Listener, EventListener {
```

which is slightly different, but still not what you want.

Looking at `java.cxx`, `public interface Listener` seems to get emitted by `emitInterfaceDeclaration()`, which doesn't seem to have any code to emit `implements`, so I don't think what you want is currently possible (directly at least).

@wsfulton Any ideas?
