### ISSUE TITLE
Debugging swig

### ISSUE THREAD

**Issue by balazsbanyai** [swig/swig#1190]
Hi, 

I'm trying to extend a language module for swig, and I have trouble debugging. All I get is a `Segmentation fault: 11` message, and I don't know how could I get more verbose information about the nature of the issue. 

I've tried to set the CFLAGS env var to "-g -O0 -DDEBUG", run ./configure and then make, but this made no effect. 

Could you please suggest a way to get a stacktrace out of swig, or directions on how to debug?
Also, If you could provide information on what IDE is recommended for development, that would be extremely helpful.

Apologies for my question, my cpp background is far from complete.

**Comment by wsfulton** [comment]
@balazsbanyai I'm afraid you need to have some basic C/C++ skills in order to wrap C/C++ code (with or without SWIG) and debugging a seg fault is one of those. You need rather good C/C++ skills to create a new language module but if you are just fixing a bug in one of the current language modules, you can probably get by with some basic skills. 

Read up about gdb or whatever debugger you are using. Every C/C++ developer has their favourite development environment, they all work. I think the best env for debugging the SWIG source code is something that invokes gdb as there are some useful gdb debugging macros which you can read about in the Development docs in the Doc/Devel directory which can also be read online at https://rawgit.com/swig/swig/master/Doc/Devel/. Look at the **Debugging SWIG** section at https://rawgit.com/swig/swig/master/Doc/Devel/internals.html. 

http://swig.org/Doc3.0/Extending.html is also useful.
