### ISSUE TITLE
array_class does not work for pointer of pointers

### ISSUE THREAD

**Issue by ctongfei** [swig/swig#1264]
For example in C I have
```c
struct Foo { ... }
```
I'd like to create a SWIG wrapper for `Foo**`.
`array_class(Foo *, FooArray)` doesn't work, however, `array_functions(Foo *, FooArray)` works.

Error message:
```
torch.i:31: Error: Syntax error in input(1).
```

**Comment by ojwb** [comment]
This is a documented limitation of `%array_class` (and non-limitation of `%array_functions`) - from https://swig.org/Doc4.1/Library.html#Library_carrays:

> %array_functions(type, name)
> [...]
> When using this macro, type may be any type and name must be a legal identifier in the target language.
> [...]
> %array_class(type, name)
> [...]
> When using this macro, type is restricted to a simple type name like int or float. Pointers and other complicated types are not allowed.

The parse error seems to be due to `%types(Foo * = FooArray);` not parsing, which is because it is parsed like a C++ function parameter list.

Using a `typedef` gives me a module which builds and loads at least, so that's probably a workaround:

```
%module x
%inline %{
struct Foo {};
typedef Foo *Foo_ptr;
%}
%include <carrays.i>

%array_class(Foo_ptr, FooArray);
```

Closing as the restriction reported here is a documented one.
