### ISSUE TITLE
.NET core for Linux

### ISSUE THREAD

**Issue by IvanFarkas** [swig/swig#1299]
1. What's the ETA for **SWIG 4.0**, please?
2. Can it generate proper **.NET Core 2.1.2** code for Windows and **Linux** as well?

**Comment by wsfulton** [comment]
See https://github.com/swig/swig/wiki/SWIG-4.0-Development to track SWIG 4 development. Most of the essential code is now ready. Hopefully we can get it out in the next couple of months, but no promises!

Regarding .NET Core, I don't know of anyone working on this, but given your success in #1216, it sounds like it is already working. Would you be able to help setting up testing SWIG with .NET Core? It shouldn't be much more than setting up Travis and Appveyor by installing .NET core and possibly making a few tweaks to find and use .NET Core by the SWIG testing framework. I can help with more information if you can assist.

**Comment by IvanFarkas** [comment]
That's good to hear @wsfulton.
#1216 was a simple test.
My ultimate goal would be to use SWIG to generate a C# wrapper for a complex C++ library like the [Intel IoT DevKit- MRAA](https://github.com/intel-iot-devkit/mraa) and use that on Linux running .NET Core 2.1 and above.
I would be glad to help you setting up the test cases.

**Comment by wsfulton** [comment]
SWIG has a comprehensive test-suite already including C# runtime tests. The runtime tests could be expanded by porting them from other language runtime tests or even writing new unique ones. However, given there is already a test-suite, that is a lower priority and the most important thing is to actually run it against .NET core. As we already use Travis and Appveyor for testing on x86_64, adding .NET core to these Continuous Integration testing environment is what needs configuring and setting up. 

What will be required is to get the test-suite running locally first with .NET core and the easiest will be on a Linux box. You need to do the usual configure and build described at http://swig.org/svn.html. You need to install .NET core and then there might be appropriate changes to make in configure.ac and variables to pass to the makefiles in Examples/Makefile.in and Examples/test-suite/csharp/Makefile.in.

Once you have it working locally, you'll need to find the 'sudo apt-get install' command for installing it on Linux and modify Tools/travis-linux-install.sh to install it. You can control what to install and test by adding a new build with appropriate env variables to the .travis.yml file and then use those env variables in the .sh script. There is more info on Travis setup I posted on 24 Jun in #968.

Windows and is harder to test on a local box as cygwin/mingw needs installing, see http://swig.org/Doc3.0/Windows.html#Windows_cygwin_mingw. It might be easier nowadays though with WSL as an alternative. On the other hand, it is possible to set up an Appveyor build and actually log in to the box running it to debug and fix. 

Either way, please test Travis or Appveyor using your own account to get a patch working before submitting it as a patch. The reason is each patch runs the entire test-suite for all languages and is really resource heavy taking hours to complete as we run 79 builds at the moment. You just need to run and test 1 or 2 extra builds for .NET core.

More detailed information on the test-suite is here: http://swig.org/Doc3.0/Extending.html#Extending_test_suite. Setting up an Ubuntu environment from a new install is easy, see https://github.com/swig/swig/wiki/Getting-Started.

**Comment by IvanFarkas** [comment]
I started the process this weekend.

**Plan**
- Update solutions and projects to VS 2017 and VS 2017 Preview. It should work with both.
- Update .NET Framework to the latest current release 4.7.2.
- Command line build on Windows 10 (nmake)
- Add solutions, project, make, nmake to clear, build, run and test .NET Core 2.1.2 on both Windows 10 and Ubuntu, Debian and perhaps Alpine Linux.

**Comment by wsfulton** [comment]
hi @IvanFarkas. I'm somewhat confused! We already build on Windows 10 on Appveyor. I tried VS2017 and unfortunately csc crashed compiling the generated code, so I havn't turned it on at Appveyor. Hopefully this is fixed now though. The test framework and build does not have any VS solutions nor nmake. If you are adding in a parallel build based on Microsoft tech, I'm afraid that I'm not going to accept it as I have no intention of maintaining parallel build or test systems. You should be able to get this all working with a few small changes using the existing test framework and build system as I outlined. If there is anything that doesn't make sense or you don't think will work, please mention or ask about it here.

**Comment by IvanFarkas** [comment]
@wsfulton I'll try the VS 2017 Preview and nmake for the examples only.
For the tests I'll do the least intrusive modification and/or additions making sure that .NET Core 2.1.2 on Linux works. Is that acceptable?

**Comment by wsfulton** [comment]
Linux sounds fine. I don't follow the rest, so probably best if I just wait for the patch and have a look then. Cheers.

**Comment by IvanFarkas** [comment]
Fantastic.

**Comment by wsfulton** [comment]
Hi @IvanFarkas, will you be doing any of these changes to test .NET core?

**Comment by IvanFarkas** [comment]
Hi @wsfulton, **Hope**, my baby girl is the #1 priority!
I'll get back to this as soon as **.NET Core 3.0** is released. to save time.

**Comment by wsfulton** [comment]
Looking after your baby sounds much more important! Your help when you have time will of course be much appreciated.

**Comment by arif-hanif** [comment]
any update on this?

**Comment by ojwb** [comment]
@IvanFarkas Did you ever get anywhere with this?

**Comment by vadz** [comment]
FWIW C# bindings for our library are used without any problems with .NET Core (although I don't remember the version). I.e. I think it can be assumed to work unless proven otherwise.

But it would, of course, be nice to add a CI build testing for this.

**Comment by ojwb** [comment]
Thanks - closing then.
