### ISSUE TITLE
SWIG - double array in struct to c# - SWIGTYPE_p_double

### ISSUE THREAD

**Issue by zjmsky** [swig/swig#1479]
HI:
I have an question. I'm trying to use swig to wrap some native dll, which contains struct looking like this:
struct Test
{	double Price[20];
};
and c# representation for Price is not an array, but SWIGTYPE_p_double. Is there way to tell swig to interpret my float Price[20] as an array, and not SWIGTYPE_p_double?

**Comment by jaskiransur** [comment]
Change it to std::array<double, 20> or std::vector<double> Price
and include 
%include <std_array.i> or 
%include <std_vector.i>

**Comment by zjmsky** [comment]
> Change it to std::array<double, 20> or std::vector Price
> and include
> %include <std_array.i> or
> %include <std_vector.i>

Hi,it's third company dll,i can't change it,have you another method?

**Comment by jaskiransur** [comment]
I see; since this is a public member variable, SWIG tries to convert it to a C# property, and it exposes these as SWIGTYPE_p_<type>
To circumvent this, you may hide the public member variable and extend the class to have appropriate functions to expose it as C# array using OUT typemaps

%{
#include "test.h"
#include <stdexcept>
%}

%include "arrays_csharp.i"

%apply double OUTPUT[] { double* array1 }

%ignore Test::Price;

%extend Test
{
	#define countof(arr) sizeof(arr) / sizeof(arr[0])
	public:
	int Size()
	{
		return countof($self->Price);
	}

	void GetPrice(double* array1, int size)
	{
		auto sourceSize = countof($self->Price);
		if (size < sourceSize)
			std::runtime_error("Initialize target array to appropriate size: "+ sourceSize);
		std::memcpy((void*)&array1[0], (void*)&$self->Price[0], sizeof(double)*sourceSize);
	}
}

%include "test.h"


+++++++++++++++++

Foo foo = new Foo();
 var array1 = new double[foo.Size()];
foo.GetPrice(array1, array1.Length);
