### ISSUE TITLE
Using SWIG as a library?

### ISSUE THREAD

**Issue by IngwiePhoenix** [swig/swig#1502]
Hello there.

I am working on the concept for a program (a build tool/system) in C/C++ and I am currently thinking about code generation in terms of API generation towards other scripting/programming languages. Now, the easy-way to go would be to use an installation of SWIG and use it through `exec()` and friends to do the generation. But I would like to know if it would be possible to use SWIG as a library as well?

When I think about SWIG, I also have [WebPack](https://webpack.js.org) and it's loaders in my mind, as they transpile from one source code to another. True, this is not the same as to what SWIG does, but it also is about code generation. Now, most of those loaders - and WebPack itself - have a library-usage as well. So the basic idea is to instantiate a transpiler, feed it a configuration, a piece of source, and then process the output of the process. Something like:

```js
const Transpiler = require("...");
const t = new Transpiler({...options});
let out = t.run(src);
```

But would SWIG be usable as a library as well?

Something else, that kind of feeds into this, is to also load custom-made language handlers (like for [Gravity](https://github.com/marcobambini/gravity) or [AngelScript](http://angelcode.com/angelscript/)). Is that possible, or does one need to compile those extensions into SWIG itself (staticaly) to work properly?

I did not see any reference to a Gitter or Slack (or alike) channel for discussion and decided to ask here. Do you mind? :)

Kind regards,
Ingwie

**Comment by vadz** [comment]
It's possible to embed SWIG inside another application (i.e. I did it), but it doesn't work out of the box, i.e. I had to customize it. Loading `Language` subclasses dynamically isn't implemented at all currently.

To the best of my knowledge, the discussion place for SWIG is the mailing list (very last millennium, I know...).

**Comment by IngwiePhoenix** [comment]
Oh! Well then I better get me subscribed to the mailing list - I didn't see it in the readme but that might have also been me just overlooking it :) Thank you for that info!

I see - so SWIG does not support this natively, but rather via patching. That is very unfortunate, but nothing horrible either :). Would you be able to share the patches you applied for it to work?


Kind regards, Ingwie.

**Comment by vadz** [comment]
> I see - so SWIG does not support this natively, but rather via patching. That is very unfortunate, but nothing horrible either :). Would you be able to share the patches you applied for it to work?

This was a long time and I'm not sure if they're still relevant. Roughly, I've just put some/most of the stuff done in SWIG's `main.cxx` in my own code.

**Comment by ojwb** [comment]
I'm not sure if there was any discussion on the mailing list, but the code was in general never written with the intention that it would be turned into a library, so there would be significant pain involved.

For example, there are a number of uses of file or even block local `static` variables.  Once you'd called `Transpiler::run()` once these wouldn't get reset on a second call to `run()`, not even if you made a new `Transpiler` object.  There's also in general a somewhat cavalier attitude to memory leaks.  Problematic ones get addressed but there's tended to be a bit of a reliance on everything getting reclaimed by the OS at the end of the run (not helped by the DOH API that essentially everything uses not making it entirely obvious when you need to call `Delete()` on a returned object - at least I've been involved with SWIG development for more than 17 years and still haven't fully grasped it, so I'm doubtful casual contributors have).

Sorting out such problems is not impossible but the amount of development effort it would require seems disproportionate to the benefit.  I agree it would be neater to be able to create an object and pass it parameters, but running `swig` as an external program works pretty well - it's not like there's interaction needed during the run.  A separate process also means a crash in SWIG doesn't crash the program calling it so there are benefits.

There are also a lot of open SWIG issues that don't have good workarounds that seem more compelling things to work on.

So I'm going to close this issue.  If someone was actually really keen to put in all the effort to make it happen then it's useful to have a ticket open, but realistically it's never going to get done otherwise and the number of open tickets has meant that many fall between the cracks.  I've closed
