### ISSUE TITLE
Incorrect encoding when passing `std::wstring` as return value to C#

### ISSUE THREAD

**Issue by smithx** [swig/swig#1532]
When you pass a wide string from C++ to C# , unnecessary encoding occurs. The behavior of this encoding is similar to [Replacement Fallback](https://docs.microsoft.com/en-US/dotnet/standard/base-types/character-encoding#replacement-fallback). I added an example (test) for this case (#1530). Debugging this problem, I see that from C# to C++ comes the correct (UTF-16) wstring, then used the factory (delegate) on the C# side to create a CLR string to return, this factory also creates the correct CLR string. When transferring already-constructed string from C++ to C#  somewhere encoding is happening. I can't see moment of this encoding not from C++ debugger neither from C# debuger (

**Comment by geefr** [comment]
We had a similar issue in our C# wrappers a while back (Sorry, can't share the typemaps)

We found that as long as all strings are marshalled as wstrings on the C++ side, and marked with 'MarshalAs(UnmanageType.LPWStr)' on the C# side the data would be passed through correctly, to wchar_t* in utf-16 encoding.

When trying to pass regular char*s we had a similar problem, so also pass those through as wstrings (Our C++ side is utf-8 char*s on all platforms). Trying to marshal from C# string to const char* automatically encodes to the 'system codepage' before the data hits the native layer.

Not tested on Linux/non-windows, I expect things would be different as a wchar is 32-bit instead of the windows 16-bit version.

**Comment by smithx** [comment]
Please, look [at the code](https://github.com/swig/swig/pull/1530/files#diff-79199e57399e220ddd626dac455967b2R7) - I am trying to pass `std::wstring` (which is already in UTF16 encoded), no conversions are required but they happen. I tried to put the attribute `MarshalAs(UnmanageType.LPWStr)` on the return value, but the result was even worse

**Comment by smithx** [comment]
[We've fixed this problem](https://github.com/swig/swig/pull/1530/commits/62ef5974d43c031e1c5145205a1d45a492573ab0)

**Comment by wsfulton** [comment]
Fixed in #1530.
