### ISSUE TITLE
Swig generates wrong Java (type unsafe) enum for C++ enum with trailing comma

### ISSUE THREAD

**Issue by equeim** [swig/swig#1566]
E.g. for
```C++
enum RatioLimitMode
{
    GlobalRatioLimit,
    SingleRatioLimit,
    UnlimitedRatio,
};
```
following Java code will be generated:
```Java
public final static class RatioLimitMode {
    public final static int GlobalRatioLimit = ;
    public final static int SingleRatioLimit = GlobalRatioLimit + 1;
    public final static int UnlimitedRatio = SingleRatioLimit + 1;
}
```
GlobalRatioLimit has no value.
If you remove trailing comma, it is correctly set to 0. However C++ allows trailing commas in enums since C++11.

**Comment by geefr** [comment]
Tried to reproduce using swig 4 (master) and the generated code is identical regardless of trailling comma

The generated enum is also a much larger class instead of a plain enum declaration:
`public final class RatioLimitMode {
  public final static RatioLimitMode GlobalRatioLimit = new RatioLimitMode("GlobalRatioLimit");
  public final static RatioLimitMode SingleRatioLimit = new RatioLimitMode("SingleRatioLimit");
  public final static RatioLimitMode UnlimitedRatio = new RatioLimitMode("UnlimitedRatio");
// snip
}
`

If using enums.swg (Docs: 'Proper java enums' example) it's slightly different, but again same output regardless of C++ syntax:
`public enum RatioLimitMode {
  GlobalRatioLimit,
  SingleRatioLimit,
  UnlimitedRatio;
// snip
}`

Is this using an old version of swig by any chance?

**Comment by equeim** [comment]
BTW this is regression since 4.0.0, it worked fine in 3.0.12.

**Comment by geefr** [comment]
Thanks, should help pin the issue down

Not sure if I know swig well enough to solve this, but taking a look/will bisect if git behaves
So far can see the value is different in java.cxx:enumvalueDeclaration, debugging through to find where that comes from..

**Comment by geefr** [comment]
Okay looks like this was caused by #1515 

- Reverting the changes makes the enum generate correctly
- current doxygen_parsing_enums_typeunsafe test case passes, and generated enums look correct to me
- Adding %javaconst(1); at the top of doxygen_parsing_enums.i makes the test fail due to the java syntax error

I won't pretend to understand the parser changes there, so paging @vadz

**Comment by vadz** [comment]
I'll try to look at this, thanks for debugging it so far.

**Comment by vadz** [comment]
I've finally debugged this and made #1584 with the fix, please let me know if you still have any problems with it (but I'm relatively confident that there should be no regressions, at least). TIA!
