### ISSUE TITLE
carrays.i does now allow long arguments for arrays

### ISSUE THREAD

**Issue by imatiach-msft** [swig/swig#1680]
carrays.i does now allow long arguments for arrays, for example see here:
https://github.com/swig/swig/blob/master/Lib/carrays.i#L23

see related issue:
https://github.com/microsoft/LightGBM/issues/2615

for now our workaround is to define our own macro

**Comment by wsfulton** [comment]
The carrays.i library merely contains macros for simple convenience functions. In your case where they don't fit the bill as the C type needs to be a 64 bit integer, I suggest copying and renaming the macros and adjusting to use `int64_t` or just copying the expanded macros (the preprocessor output after running `swig -E`) and adjusting. You'll need a `%include <stdint.i>` to handle `int64_t`. Alternatively just use 'long long'.

**Comment by ojwb** [comment]
@wsfulton Given your reply above, do you think we should just close this as WONTFIX?

FWIW, to me `int` seems the wrong choice here and `size_t` would be better since that's the standard C type for an array size, but maybe you have concerns about breaking existing usage if we change that at this point?  I'm not really seeing how, but if you don't like just changing the type I guess we could add an optional parameter to specify the type to use for the index.

**Comment by wsfulton** [comment]
Agreed int is the wrong choice and size_t is the correct choice for indexing into C arrays and for sizing the array when allocated. I'll make the changes to switch to size_t. Note that many of the scripting languages already use size_t as they utilise [carrays.swg](https://github.com/swig/swig/blob/master/Lib/typemaps/carrays.swg.)

The following target languages will be affected with this change from int to size_t:
- C#
- D
- Go
- Guile
- Java
- Javascript
- Lua
- MzScheme/Racket
- Ocaml
- R
