### ISSUE TITLE
CWE-190: Integer Overflow or Wraparound in generated code for Python

### ISSUE THREAD

**Issue by hamza-soussou** [swig/swig#1732]
A vulnerability warning has been raised by a scanning tool that reported a CWE-190 (http://cwe.mitre.org/data/definitions/190.html) issue in the SWIG_Python_str_AsChar function:
```
SWIG_Python_str_AsChar(PyObject *str)
{
#if PY_VERSION_HEX >= 0x03000000
  char *cstr;
  char *newstr;
  Py_ssize_t len;
  str = PyUnicode_AsUTF8String(str);
  PyBytes_AsStringAndSize(str, &cstr, &len);
**newstr = (char *) malloc(len+1);**
  memcpy(newstr, cstr, len+1);
  Py_XDECREF(str);
  return newstr;
#else
  return PyString_AsString(str);
#endif
}
```
The scanning tool complains about the allocation made for newstr where len+1 could exceed the max size of the associated representation.

**Comment by wsfulton** [comment]
Code has changed a bit since then, see https://github.com/swig/swig/pull/1700.

The vulnerability looks like a false positive because Python allocates the len + 1 for storing the trailing NULL, see https://github.com/python/cpython/blob/c705fd1e89ccb8f6d414ec817b4616546147d877/Objects/bytesobject.c#L2917. So in other words it is possible to add one to the size. For overkill, checking `len is < PY_SSIZE_T_MAX` would keep the scanning tool quiet. Can you run the tool through the latest code first though (it'll be in swig-4.0.2 which will go out fairly soon)?

**Comment by ojwb** [comment]
I agree this is a false positive as `PyBytes_AsStringAndSize()` can't return `PY_SSIZE_T_MAX` for len, so `len+1` is actually safe.

Adding a redundant `if (len == PY_SSIZE_T_MAX)` check doesn't seem a good answer - we'd need to do something to handle this case that can never actually happen, and that's liable to cause warnings from other scanning tools.

If people want to use imperfect scanning tools, they can't realistically expect us to make every bogus warning go away for them.

We've investigated and concluded it's a false positive, and I think that's all we can reasonably do, so closing.
