### ISSUE TITLE
[C++14] Missing features with auto type

### ISSUE THREAD

**Issue by Galiley** [swig/swig#1743]
Let's say i have a c++ class like this one
```c++
class Example{
    public:
        Example();
        auto foo(){
            return _foo;
        }
    private:
        int _foo;
};
```
Swig fails with a syntax error on the method foo which is kinda odd since foo is basically a getter for a private attribute. 
After a quick look into the C parser, it seems that only lambda function auto type is supported.

Could it be possible to fix this missing features or be able to ignore the method causing the syntax error?

NB: I'm working on the wrapping of a package I'm not the owner. So I cannot put swig directive directly in the header file

**Comment by wsfulton** [comment]
This is not valid C++11, so I've modified the title accordingly. Function return type deduction was introduced in C++14, so you need a C++14 compiler for this syntax to work. SWIG does not yet support this C++14 feature, so your workaround is to add in the trailing return type, so change the declaration of foo to:
```c++
auto foo() -> int { return _foo; }
```
While adding in the type information manually might seem a nuisance, I'm afraid that if you are going to wrap this function with SWIG and SWIG was fixed to parse this syntax, you will need to provide the type to use because SWIG does not parse function bodies and so will not be able to deduce the type.

**Comment by wsfulton** [comment]
Also, I tried adding support for this new syntax into the parser, but it adds many shift/reduce conflicts. It was a quick attempt, but I suspect quite a big change in the parser would be needed to add support for this. Needs further investigation.

**Comment by Galiley** [comment]
Okay thank you.
Is it possible to ignore this method while parsing the header?
```%ignore Example::foo;``` does not work.
Thanks in advance

**Comment by wsfulton** [comment]
Sorry no
