### ISSUE TITLE
Typemaps documentation variable type long->int

### ISSUE THREAD

**Issue by AlbertoEAF** [swig/swig#1744]
Hello,

I was reading the SWIG 4.0 documentation regarding typemaps and I think it's just a typo but, aren't all references in this section supposed to report to int instead of long, or always long instead of int?
![image](https://user-images.githubusercontent.com/3976753/75623384-61639580-5ba1-11ea-8d7e-f83c74f57342.png)

(http://www.swig.org/Doc4.0/SWIGDocumentation.html#Library_nn3)

Thank you :)

**Comment by wsfulton** [comment]
`PyInt_AsLong` and `PyInt_FromLong` are part of the official Python 2.7 API, see https://docs.python.org/2/c-api/int.html where you'll see they use C type `long` as mentioned in the SWIG docs you show above.

Note that the API above was removed in Python 3 and the replacement APIs are `PyLong_AsLong` and `PyLong_FromLong`  documented at https://docs.python.org/3.8/c-api/long.html. It still uses a C `long`.

`arg1` and `result` in the documentation you show above should be of type int, because that is the type in the function being wrapped:
```C
int factorial(int n);
```

Hope that helps.

**Comment by AlbertoEAF** [comment]
Thank you @wsfulton :)
