### ISSUE TITLE
A lot of the existing code is hard to read due to use of tabs

### ISSUE THREAD

**Issue by ahungry** [swig/swig#1767]
Please see screenshot - on the left is the existing guile.cxx module, on the right is the new one I'm working on for janet-lang.org 

I like to use GNU style with 2 space indentation and avoid tabs.

Due to my less than 8 char tab width, the Guile code appears unreadable ("indented" IF blocks are more left aligned than some space-indented blocks).

I'm also confused on why the style guide mentions using tabs for indentation, yet the guile.cxx file in particular seems to have a mix of tabs and spaces? (as do many other files).

Please see attached screenshot for sample

(I may have to link screenshot in a follow up comment not seeing a button here for upload at the moment).

**Comment by ahungry** [comment]
[Hard to read](https://raw.githubusercontent.com/ahungry/swig/feature/Add-janet/ugly-format.png)

**Comment by vadz** [comment]
I didn't choose SWIG indentation style but I seriously hope nobody is going to seriously argue for changing it and reformatting the entire code base. You do need to set tabstop to 8, of course (`set ts=8 sw=2 noet tw=160` for Vim, for example).

**Comment by ahungry** [comment]
No, that would be a bad argument, although I may suggest easing the style requirements/guidelines in the docs for contributions of brand new modules/things (obviously for existing files/classes, "when in Rome"), but I don't agree with new code adapting a sub-par practice for the sake of "its been that way".

**Comment by ojwb** [comment]
But it's not just you that will have to work with the code in your new module.

Having the coding conventions vary across a codebase makes life much harder for those who try to maintain the whole codebase.

**Comment by ojwb** [comment]
> I'm also confused on why the style guide mentions using tabs for indentation, yet the guile.cxx file in particular seems to have a mix of tabs and spaces? (as do many other files).

The indent is 2 columns, tab filled with a tab width of 8 columns - `sw=2 ts=8` in vim which you seem to use.  So e.g. a 10 column indent would be a tab and two spaces.

I don't think we're going to let different backends use different coding styles - it just makes life needlessly difficult for those of us who try to work on SWIG across backends.  Any coding style isn't going to be to everyone's taste - I'm not madly keen on 2 space indents personally for example, but I appreciate that it's better to have consistency than for me to go with my personal preference here.

To me the left pane in your screenshot is harder to read because it looks different to the rest of the SWIG code.

**Comment by wsfulton** [comment]
The documentation for writing a new language module talks about coding style. Patches to make this clearer are welcome. See http://swig.org/Doc4.0/Extending.html#Extending_coding_style_guidelines.
