### ISSUE TITLE
Move python default version to 3

### ISSUE THREAD

**Issue by tpaviot** [swig/swig#1779]
After the latest swig version (4.0.1) was released (in August 2019), python2 support was officially dropped down in January 2020. That would make sense that swig keeps consistent with this decision, and move its default python version to 3.

Currently, in order to generate a python wrapper using swig, you have to pass both the ```-python``` flag, as well as ```-py3``` to explicitly request for python 3 specific features. The compiled module ca be used with python 3 only. If only ```-python``` is passed to swig, then the generated python code syntax is python 2. Today, this should be the opposite: the default python code should be 3 if nothing is passed but the ```-python``` flag, and python 2 code should be explicitly requested.

The following suggestion would allow this with only a few changes to the current codebase:

* add another ```-py2``` flag

* make ```-py2``` and ```-py3``` mutually exclusive

* set default py3 value to true by default, to false if ever ```-py2``` is passed

* optional: make either ```-py2``` or ```-py3``` mandatory to prevent swig users from an unexpected API change to the python code when moving from 4.0.1 to any later version.

**Comment by ojwb** [comment]
> Currently, in order to generate a python wrapper using swig, you have to pass both the -python flag, as well as -py3 to explicitly request for a python 3 compliant module. If only -python is passed, then the generated python code is python 2.

That's wrong - see the manual:

>33.12 Python 3 Support
>
>SWIG is able to support Python 3.x. The wrapper code generated by SWIG can be compiled with both Python 2.x or 3.x. Further more, by passing the `-py3` command line option to SWIG, wrapper code with some Python 3 specific features can be generated (see below subsections for details of these features).

**Comment by tpaviot** [comment]
@ojwb you're right, what I wrote is actually wrong I went to fast.

**Comment by tpaviot** [comment]
I made a small change to the issue description, I guess it's more accurate and conform to the documentation.

**Comment by wsfulton** [comment]
Related to #1561. `-py3` does very little apart from add in these function annotations, which are really not very good and should be off by default and only explicitly added in if required. Something to think about for swig-4.1.0.

**Comment by ojwb** [comment]
Something I'd definitely be keen to do here is eliminate the need to run the testsuite with:

```
make check-python-test-suite PY3=y
```

(Or `PY3=1` depending which docs you read - what actually seems to matter is if it's empty or not.)

Literally every time I run the Python testsuite I fail to add the `PY3` bit and then wonder at the resultant error of it failing to find `Python.h` for a few seconds until I remember.  At least if you know about this it just breaks the flow a bit, but if you don't know about it you could easily waste significant time working out what's going wrong.

I think 4.1.0 would be a sensible point to default to Python3 testing and instead have something like `PY2=y` to select Python 2 testing.

**Comment by ojwb** [comment]
So to summarise the current situation:

Currently the code generated with `-python` works with either Python 2.7 or Python >= 3.2 - you can compile the same generated `_wrap.c`/`_wrap.cxx` against either.

Passing `-py3` does several things:

* Makes the generated `.py` wrapper check only for Python >= 3.0.0 instead of Python > 2.7.0
* It turns on function annotations (but these annotations are with the C/C++ types so apparently not very useful)
* Enables support for the `python:abc` feature
* Disables generating a `@_swig_add_metaclass(_SwigNonDynamicMeta)` annotation and instead adds `, metaclass=_SwigNonDynamicMeta` (when the `python:nondynamic` feature is used)

I'm no Python expert, but overall it doesn't seem to be enabling `-py3` by default in 4.1.0 seems a compelling proposition.  I think the proposal above is based on a misunderstanding as to what `-py3` does and what you get without it.

I'm going to make a concrete set of proposals here:

The testsuite should default to running with Python3 and have `PY2=1` or similar to select Python2.  _(I've got a partial patch for this - the awkward part is in CI where currently it sets `PY3=3` and then uses `python$PY3` to be `python` for Python2 and `python3` for Python3 - that's resolvable but make the change a little more fiddly.)_

The function annotations should move to a separate option, or perhaps even be reworked to be controlled by a feature.  Is it useful to be able to enable them selectively?

`-py3` should in general probably not enable specific features.  It may be required for features to work (such as `python:abc` and the annotations), but those should be opt-in unless they are genuinely features which pretty much everyone will want enabled..  That means `-py3` only really changes the version check by default.

I don't see a good reason to add a `-py2` option or to make `-py3` the default - such changes are unfriendly towards SWIG-using projects; Existing SWIG releases would error out on `-py2` so they'd need to change their build systems to run `swig` for SWIG < 4.1.0 vs `swig -py2` for SWIG >= 4.1.0.  On the other side, nobody would actually be able to drop `-py3` unless they're prepared to require SWIG >= 4.1.0.  It seems better to just leave this alone until SWIG drops Python2 support at which point `-py3` just becomes a no-op option left for compatibility.  (I suspect the timescale for that will end up driven largely by when it becomes hard to test with Python2 in CI.)

We should probably also make sure that options that require `-py3` don't quietly not work without it.  I think that may be the case with `%feature("python:abc")` currently.  I think we can just do something like:

```
#ifndef SWIGPYTHON_PY3
# error "%feature("python:abc") requires command line option -py3"
#endif
```

**Comment by geographika** [comment]
@ojwb - your suggestions make perfect sense to me. 
For reference EOL of different versions is at https://endoflife.date/python
Does SWIG have any "official" versions of Python it supports? Or should this be based on the CI setup?

>   Makes the generated .py wrapper check only for Python >= 3.0.0 instead of Python > 2.7.0

 Would it still be tied to the `-py3` flag?

>  It turns on function annotations (but these annotations are with the C/C++ types so apparently not very useful)

So these would be enabled with a new command line flag? Any suggestions on a name? `annotations`?

>    Enables support for the python:abc feature

Is this now enabled when `SWIGPYTHON_PY3` is set?

> Disables generating a @_swig_add_metaclass(_SwigNonDynamicMeta) annotation and instead adds metaclass=_SwigNonDynamicMeta (when the python:nondynamic feature is used)

How would this be handled? Would it still be tied to the `-py3` flag?

I'm happy to look at updating the command line options along with #1951 and documenting them. I can outline changes in a new issue first if that helps?

**Comment by ojwb** [comment]
You'll need to convince William to drop older Python versions.  He doesn't seem very swayed by upstream EOL dates in general.  Personally I think we're too conservative about this (realistically people who are still clinging to Python 2.7 aren't going to be trying to use the very latest and greatest versions of tools with it - they're just trying to keep some existing system going with minimal maintenance (and so minimal changes) until they can replace it with a version in Python 3 or a different language).  We clearly don't have enough developer resources to even keep on top of the bug pile, and there's an opportunity cost of eking out support for ancient versions, but it's not my call to make.

> Does SWIG have any "official" versions of Python it supports? Or should this be based on the CI setup?

The manual currently says "SWIG is compatible with all recent Python versions (Python 2.7 and Python >= 3.2)"

>> Makes the generated .py wrapper check only for Python >= 3.0.0 instead of Python > 2.7.0

>Would it still be tied to the -py3 flag?

I'm saying that's essentially all the `-py3` flag would do: "That means -py3 only really changes the version check by default."

It could potentially also omit preprocessor conditional branches in the C/C++ wrapper which are only for Python 2, but I'm not sure that's really worth the effort as it complicates the generator code, and the work would be thrown away once SWIG drops Python 2 support, which realistically shouldn't be a long way off.  It's a pretty dead parrot already.

>> It turns on function annotations (but these annotations are with the C/C++ types so apparently not very useful)

>So these would be enabled with a new command line flag? Any suggestions on a name? annotations?

Either a command line flag, or if it's useful to control them in a more fine grained way than "on" vs "off" for a while module, it could be a feature.  Something like `-annotations` (as a `-python`-specific option) or `%feature("py:annotations") probably makes sense.

>> Enables support for the python:abc feature

>Is this now enabled when SWIGPYTHON_PY3 is set?

`-py3` causes `SWIGPYTHON_PY3` to be set and allows the `python:abc` feature to actually work, but `-py3` doesn't actually turn on `python:abc` (you need to `%include "python/pyabc.i"` and then use `%pythonabc(Foo, 1)` to mark ABC classes.  If you only do the latter part and don't use `-py3` then the feature markings don't actually have any effect on the classes (or at least that's what it looks like to me from reading the code).

(And to be clear setting `SWIGPYTHON_PY3` doesn't make `python:abc` work, but isn't something people should be doing anyway.)

>> Disables generating a @_swig_add_metaclass(_SwigNonDynamicMeta) annotation and instead adds metaclass=_SwigNonDynamicMeta (when the python:nondynamic feature is used)

>How would this be handled? Would it still be tied to the -py3 flag?

I don't really know Python well enough to understand what the difference between the two is - are they just different ways of specifying a metaclass?  If the latter is equivalent to the former but just more efficient or better in some way that makes sense for everyone or something like that then it's reasonable to have it in `-py3` I think.  If it's something people may not want to have forced on them by `-py3` it then shouldn't be tied to `-py3`.

>I'm happy to look at updating the command line options along with https://github.com/swig/swig/pull/1951 and documenting them. I can outline changes in a new issue first if that helps?

A patch would be good (at least once we're happy with a plan).  I'd probably suggest keeping discussion here until we get the point where there are things we've definitely decided to do.

**Comment by vadz** [comment]
As a point of record, I would like to use the latest SWIG but still need to support Python 2.7 users.

**Comment by geographika** [comment]
How about the following proposal?

- disable all Python annotations by default
- add a new `-annotations` command line switch to enable them (or name it `-typehints` which might be clearer?)
- this would add type annotations to both functions and properties. As the latter is only support in Python 3.6+ then type annotations would no longer be available to Python 3.5 or earlier, but it would have no other impact on being able to use SWIG for these versions
- Python 2.7 is unaffected by any of these changes (empty strings are returned for Python2 already)

**Comment by ojwb** [comment]
> add a new `-annotations` command line switch to enable them (or name it `-typehints` which might be clearer?)

We should probably use the same terminology that Python does.

It could be a SWIG feature rather than a command line option, especially if it's useful to be able to add type annotations selectively - e.g. then you could do `%feature("python:annotations");` to turn it on globally, or `%feature("python:annotations") Foo;` to only turn it on for `Foo`.

**Comment by ojwb** [comment]
In 3159de3e9fcd8b7bf8747711fe240a36d620075f William added `%feature("python:annotations", "c")`, etc as a way to enable annotations explicitly, and control what they're applied to, and `-py3` no longer implicitly enables them.  (Also variables can now be annotated too: #1951.)

I've opened #2235 to default the testsuite to running with Python 3 (so no more need to remember `PY3=1`; instead `PY2=1` is needed if you actually want to run it with Python 2).

I think that leaves `-py3` doing these two things in addition to changing the generated Python version checks:

* Enables support for the python:abc feature
* Disables generating a @_swig_add_metaclass(_SwigNonDynamicMeta) annotation and instead adds , metaclass=_SwigNonDynamicMeta (when the python:nondynamic feature is used)

It's unhelpful that `python:abc` is quietly ignored unless you pass `-py3`, and would be more consistent with how the new `python:annotations` works for it to just generate Python3-specific code when used, so I suggest we just drop the `py3 &&` from `if (py3 && abcs)`.

I don't really understand the details of the metaclass one - are those equivalent to each other, but the second one only works with Python 3 and is preferable for some reason?  If so, maybe that's best left controlled by `-py3`.

**Comment by wsfulton** [comment]
I've modified pyabc.i to work with the oldest version of Python that we support (2.7). There is no need for Python 3 only syntax for the metaclass used by pythonnondynamic as the default generated code works with all the supported versions (2.7 and 3.2+), so I've removed the Python 3 only syntax that `-py3` generated.

Now there is nothing that the `-py3`command line option does, so it has been deprecated and is no longer needed.

**Comment by ojwb** [comment]
Oo, nice.

The remaining thing the `-py3` option does is to raise the minimum version threshold in the check in the generated `.py` wrapper file - do you think that's not a useful feature in itself?

My thought was it was worth keeping given it was already there as a simple way for projects which require Python 3 due to custom typemaps, etc to specify that.  Otherwise to get that checked up front one needs to replace SWIG's import logic, or add a second version check with `%pythonbegin` which makes SWIG's generated one redundant, or post-process the generated `.py` wrapper file with `sed` or similar.

Though perhaps the more useful place to add a version check is in the generated C/C++ wrapper - that's probably the point at which trying to use an older Python actually causes a problem if you have custom typemaps.

**Comment by wsfulton** [comment]
Actually, checking that a minimum version of Python is being used is a rather sub-optimal solution for checking the Python version is correct as only one version of Python should be used, that is, the version that the C code was compiled against. It is actually misleading and confusing to check for a minimum version and not an exact version as it implies that any version greater than the stated minimum will work. Even checking for python>=3 when we had the `-py3` option was pointless as a python-2.7 interpreter would show a syntax error before being able to run the code that checked for the minimum version. In fact, I think I'll remove this version check which just checks for >=2.7 now for the reasons given above.

Using `%pythonbegin` as suggested is the best option and I would recommend users incorporate taking the appropriate version from their build system and add some something like the following:
```swig
%pythonbegin %{
def my_check_version():
    from sys import version_info as _my_python_version_info
    if _my_python_version_info[0:2] != (3, 9):
        raise RuntimeError("Python 3.9 required")
my_check_version()
%}
```

Adding a version check in the C layer may or may not work depending on how successful the Python interpreter was in loading the python code. It also depends on how incompatible the version used and the target version actually are in the C layer and whether the dynamic linker successfully loads the code before being able to actually run anything. I suspect we won't be able to provide a robust check. The recommendation above is probably the only fool-proof solution.

**Comment by vadz** [comment]
> Actually, checking that a minimum version of Python is being used is a rather sub-optimal solution for checking the Python version is correct as only one version of Python should be used, that is, the version that the C code was compiled against.

This, of course, is not the case when using limited Python ABI (which is, again and again and again, the only reasonable way to ship binary modules for Python 3).

**Comment by vadz** [comment]
Just to be clear, my comment was meant to highlight that this check shouldn't be made exact if the stable ABI PR is still to be merged at all, otherwise it would (silently) break it, not to argue for merging it (I don't think I can add anything to what I already said about it).
