### ISSUE TITLE
Typemap for Google Protobuf?

### ISSUE THREAD

**Issue by tobegit3hub** [swig/swig#1780]
Swig is great for cross-language calling and provides the user friendly typemaps such as boost smart pointer. We use swig to provide C APIs and some APIs contain the objects which are generated by protobuf.

Since protobuf is the standard serialization format and it generates client code in different languages, we do not need to use swig to generate the code for the generated code by protobuf. These can also be  done by swig typemaps to convert C++ protobuf objects to Java or others protobuf objects.

I'm not sure if it is acceptable to merge in the code base so that everyone can use. We think the typemaps for google protobuf are really general and we can send the pull-requests if the community need it.

**Comment by ojwb** [comment]
I don't think it is an official policy as such, but we don't generally seem to include typemaps for third-party libraries (as you note, there is indeed some boost smart pointer support, but I think it's essentially the same support for the smart pointers now in the C++ standard).

We are lacking in people and time to maintain what we have so scope creep is a problem.  If the patches are clean and you're willing to maintain them going forwards maybe it's OK.  If they're invasive or you're just wanting to chuck them over the wall and hope someone else maintains them it seems a bad idea to me.

**Comment by wsfulton** [comment]
Typemaps for a particular project should be maintained within that project in order to keep them in sync with changes in that project. We maintain a library of typemaps for the C++ standard STL and occasionally boost types that are likely to end up in the C++ standard.

BTW, I agree that typemaps for Protobuf would be useful for numerous people, so suggest you work with the Protobuf project to get them included there.
