### ISSUE TITLE
Error importing a shared library in __init__.py auto-generated by SWIG

### ISSUE THREAD

**Issue by dbogdanov** [swig/swig#1804]
I have an error when importing a python extension of [gaia](https://github.com/MTG/gaia) built with SWIG. 

```
>>> import gaia2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/gaia2/__init__.py", line 7, in <module>
    import _gaia2
ModuleNotFoundError: No module named '_gaia2'
```
The package is installed to `/usr/local/lib/python3.7/dist-packages/gaia2/` and contains both `__init__.py` and `_gaia2.cpython-37m-x86_64-linux-gnu.so` inside that package folder.

The `__init__.py` is auto-generated by SWIG and contains `import _gaia2` which does not work. If I change to `from . import gaia2` it works. How can I configure SWIG to do that or am I doing something wrong? 

Installing the shared library one level up into `dist-packages`  works, but that's not what other packages do. 

Tried both with Python 3.7 and 3.8, and SWIG version 3.0.12 and 4.0.1.

**Comment by wsfulton** [comment]
SWIG doesn't generate an `__init__.py` though!

I do strongly recommend using 4.0.1 because there were a lot of package import improvements in version 4.0. Please also have a really good look at http://swig.org/Doc4.0/Python.html#Python_nn72 which discusses this topic and then let us know which of the scenarios described in there it is that you are using if you are still having problems.

**Comment by dbogdanov** [comment]
Sorry, I was referring to the `<packagename>.py` that contains
```
# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
```

**Comment by dbogdanov** [comment]
Fixed by modifying `%module(moduleimport="...")`.
