### ISSUE TITLE
%rename with command: fails on debian due to dash as /bin/sh

### ISSUE THREAD

**Issue by xhub** [swig/swig#1806]
The %rename with external command seems to fail on a debian system (works if /bin/sh points to bash rather than dash)

$ swig -tcl rename_camel.i 
rename_camel.i:13: Warning 301: class keyword used, but not in C++ mode.
sh: 1: Syntax error: redirection unexpected
sh: 1: Syntax error: redirection unexpected
sh: 1: Syntax error: redirection unexpected
sh: 1: Syntax error: redirection unexpected
sh: 1: Syntax error: redirection unexpected
sh: 1: Syntax error: redirection unexpected
sh: 1: Syntax error: redirection unexpected
sh: 1: Syntax error: redirection unexpected
sh: 1: Syntax error: redirection unexpected
sh: 1: Syntax error: redirection unexpected

$ swig -version
SWIG Version 4.0.1
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre

**Comment by wsfulton** [comment]
Please provide a cut down example to replicate. Perhaps your %rename is somewhat funky??

**Comment by xhub** [comment]
My bad, I forgot to mention that `rename_camel.i` is from Examples/test-suite. It's the only occurrence of the use of %rename(command

**Comment by wsfulton** [comment]
I see. From common.mk:
https://github.com/swig/swig/blob/64e2c43c93b66c406b90f7dfbac1fce581462352/Examples/test-suite/common.mk#L83-L91
it's in the broken list of tests, seems like it always has been.

Probably the area of code to look at the use of `popen` in `Swig_string_command` 

https://github.com/swig/swig/blob/64e2c43c93b66c406b90f7dfbac1fce581462352/Source/Swig/misc.c#L1144-L1185

**Comment by ojwb** [comment]
Still reproducible with current git master.

The problem is actually with the testcase, which uses the bashism `<<<`:

```
%define SedCmd "%(command:sed -e 's/\([a-z]\)/\U\\1/' -e 's/\(_\)\([a-z]\)/\U\\2/g' <<<)s" %enddef
```

and:

```
%define awk_cmd "%(command:awk '/^i/{print toupper($1)}' <<<)s" %enddef
```

Not sure I see an easy way to avoid this - it seems inherent in the design that the string to process can just be appended to the specified command string.  It also seems to suffer from potential quoting problems - while most valid C/C++ function names should be safe in shell, there are things like `operator>` which contain shell meta characters:

```
$ sed -e 's/\([a-z]\)/\U\1/' <<< operator>
bash: syntax error near unexpected token `newline'
```

In terms of exploits this probably isn't a big deal when you can just specify a command directly in the interface file, though it may provide scope for obscuring an evil command.

However, it's certainly unhelpful that some valid function names can't be fed to this.  Also while the shell error appears of `stderr`, SWIG ignores the failure it and will still exit with status 0.

The regexp support seems a much cleaner and more portable solution which addresses most of the use cases this can.  For the really complex and/or esoteric cases where you need a script to manage the renaming, perhaps we just suggest people write a script to generate a file of `%rename()` and then `%include` that.  That would also be a lot more efficient that running a command for every symbol being renamed - that only matters if you're renaming a lot of symbols, but you likely are in the cases where you can't just use a regexp rename.

So I wonder if it'd actually be best to deprecate or perhaps even just remove support for `%(command:...)`.  It seems unlikely it's widely used as it doesn't work on Unix-like platforms if `/bin/sh` isn't bash (which means it's not going to work on most non-Linux Unix-like OSes, nor on the Linux distros which have `/bin/dash` for `/bin/sh` - I know Debian and Ubuntu have for ages).  I'm not sure if it's usable at all on Microsoft Windows, but even if it is it seems you wouldn't be able to write a single command that works both there and on Unix-like platforms.

As a data point, Debian codesearch (which searches the sources of all packages in Debian) only finds swig and renderdoc (because it contains a copy of SWIG): https://codesearch.debian.net/search?q=%25%28command%3A&literal=1

If it isn't to be removed, I don't see a good way to fix it.  We could explicitly run the command under `/bin/bash`, except there are platforms which don't have `/bin/bash`.  We could redesign it to take the string on stdin (which would solve the bashism and quoting problems) but that would break any current uses and if breaking any current uses is OK then removal seems the better option to me.

**Comment by wsfulton** [comment]
Sounds like we should just remove this then if doesn't work. I doubt it will be missed given the problems in @ojwb's summary.

**Comment by ernestask** [comment]
How should advanced cases be handled now? I’m currently staring at one that requires stripping a prefix and camel-casing enum items, yet I don't see a way to chain rename functions or somesuch.

**Comment by ojwb** [comment]
Many cases can be handled with a regexp rename.

If that doesn't work for your use case, what I suggested above:

> For the really complex and/or esoteric cases where you need a script to manage the renaming, perhaps we just suggest people write a script to generate a file of %rename() and then %include that. That would also be a lot more efficient that running a command for every symbol being renamed - that only matters if you're renaming a lot of symbols, but you likely are in the cases where you can't just use a regexp rename.

**Comment by ernestask** [comment]
That is going to be… horrible. Might as well stick with the current version.

**Comment by ojwb** [comment]
The problem is that `%rename` with a command was horrible too, for the reasons discussed above.  If the suggested solution doesn't work for cases that `%rename` with a command did then I think a new feature that's at least portable and handles all valid C++ function names is needed rather than reverting this removal.

However if you're just wanting to remove a prefix and camel case enum items then that's entirely doable with a regex - e.g.:

```
%rename("%(regex:/^PREFIX_(.)([^_]*)_?(.)?([^_]*)?_?(.)?([^_]*)?_?(.)?([^_]*)?/\\1\\L\\2\\E\\3\\L\\4\\E\\5\\L\\6\\E/)s", %$isenumitem) "";
```

This maps `PREFIX_FOO` to `Foo` and `PREFIX_FOO_BAR` to `FooBar`.

This version works for up to 3 components, but you can add more of the repeated capture groups if you need to handle e.g. `PREFIX_ONE_TWO_THREE_FOUR`.

**Comment by ernestask** [comment]
I’m not advocating for a reversal, but a regex is clearly the less-maintainable option here.

I haven’t gone through the code yet to see what could be viable, but even the ability to apply a rename on a processed input (as opposed to the last one taking place) would be 👌. Not ideal performance wise, I’ll admit, though.
