### ISSUE TITLE
does swig support std::future for Java?

### ISSUE THREAD

**Issue by JacobVarghese1992** [swig/swig#1828]
Swig generates a SWIGTYPE_P_std__futureT_int_t object for std::future<int> but it just holds the C pointer and just gives me an option to retrieve it.  

I couldn't find documentation around this unfortunately.

**Comment by wsfulton** [comment]
There is no library support for this from SWIG, the `std::future` template can be wrapped like any other. I experimented and it was a little tricky due to the move only semantics. Here is an example:
```swig
%module example

%inline %{
#include <iostream>
#include <future>
#include <thread>
%}

namespace std
{
template <class R>
class future {
 public:
    future() noexcept;
    future(future &&) noexcept;
    future(const future& rhs) = delete;
    ~future();
    future& operator=(const future& rhs) = delete;
    future& operator=(future&&) noexcept;
//    shared_future<R> share();
 
    // retrieving the value
    R get();
 
    // functions to check state
    bool valid() const noexcept;
#if defined(SWIGJAVA)
    %rename(wait_future) wait() const; // Because of Java's Object.wait method
#endif
    void wait() const;
/*
    template <class Rep, class Period>
    future_status wait_for(const chrono::duration<Rep, Period>& rel_time) const;
    template <class Clock, class Duration>
    future_status wait_until(const chrono::time_point<Clock, Duration>& abs_time) const;
*/
};
}

%template(FutureInt) std::future<int>;

// Use the 'optimal' attribute to avoid the need for a copy constructor
%typemap(out, optimal="1") std::future<int>
%{ *($&1_ltype*)&$result = new $1_ltype($1); %}

%inline %{
std::future<int> makeFuture() {
  std::future<int> f2 = std::async(std::launch::async, []{ return 88; });
  return std::move(f2);
}
```
Java usage:
```java
    FutureInt f2 = example.makeFuture();
    f2.wait_future();
    System.out.println("Done!\nResults (from Java) are: " + f2.get());
```

**Comment by wsfulton** [comment]
I don't think these workarounds are needed now that I've put in much better move support. Needs checking by someone.

**Comment by ojwb** [comment]
With current SWIG your example above seems to still work with this part removed:

```
// Use the 'optimal' attribute to avoid the need for a copy constructor
%typemap(out, optimal="1") std::future<int>
%{ *($&1_ltype*)&$result = new $1_ltype($1); %}
```

I'm not sure whether we should be providing interface files in the library for classes like this - it would avoid users having to roll their own, but if the same approach is taken to other C++ standard library classes you can wrap by providing a (probably cut-down) version to SWIG that would add quite a lot of code to SWIG's library.  It should be fairly low maintenance, but there's still some overhead and someone needs to write suitable interface files and corresponding test coverage.

If we aren't aiming to provide explicit support for things like this it'd be helpful to have a coherent documented policy on what we do and don't aim to provide explicit support for.

I think `std::future` is worth at least a mention in the manual even if we don't provide explicit support so that users wanting to wrap code using it have a pointer for how to.  I can probably add something.

**Comment by matiaslin** [comment]
Hi, thanks for this thread. Just a follow up on the discussion, I see that as of SWIG-4.3.0 (master), there is still no `std_future.i` (and I'll be keeping my eye on `Library.html`). I'm just wondering if there is anybody already working on this, or if this is something that we can look forward to in future SWIG releases?
Thank you so much!

**Comment by WilliamTambellini** [comment]
Cool @matiaslin 
We are indeed interested.
@wsfulton  any comment?

**Comment by ojwb** [comment]
There's nobody working on `std::future` support built in to SWIG (at least nobody who has communicated that to the SWIG developers), but you can just wrap it from your interface file using the code shown in wsfulton's first comment above (as noted in later comments you can delete the `optimal` typemap part as that's no longer needed with more recent SWIG versions).  That's exactly what I did when I needed to wrap an API using `std::future`.

If somebody wants to clean that up and add it to SWIG's library along with testcases and suitable documentation, please open a PR.

**Comment by matiaslin** [comment]
Sounds good. Thank you @ojwb for the reply. I will give it a try.
