### ISSUE TITLE
How pass argument as NULL from python to C++.

### ISSUE THREAD

**Issue by myproject24** [swig/swig#1829]
Hi,

@joequant  I have issue while passing NULL to C++.
i have created python interface from C++ library but few API's in C++ need to **pass as NULL** some time, from python if i pass None as argument i am getting **TypeError**. Basically is C++ side argument type is **void pointer** for non NULL values i am passing object from python, if i want to pass NULL to C++ what i have to do please suggest me.

**Comment by ojwb** [comment]
Please use the mailing list for questions, rather than the bug tracker.  Many more people read the mailing list so you're likely to get an answer sooner.

As documented [in the manual](http://www.swig.org/Doc4.0/Python.html#Python_nn18), pass `None`:

<blockquote>
<p>
Note also that the '0' or NULL pointer is always represented by
<tt>None</tt>, no matter what type swig is addressing. In the
previous example, you can call:
</p>

<div class="targetlang">
<pre>
&gt;&gt;&gt; example.fclose(None)
</pre>
</div>
</blockquote>
