### ISSUE TITLE
How to enable just one class inside a namespace? (using ignore/rename)

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#1847]
Hi,

I've some c++ module (might be 3rd party so I cannot edit it) which defines a lot of symbols, classes, ... but everything in a namespace.
Now, I want to wrap just a selected class from this file but I couldn't find how to do it using ignore/rename. I don't know if I misunderstood the documentation or if this is a bug (or simply not possible currently).

Take the following file
```swig
%module someModule

%ignore foo::bar;
//%rename("%s") foo::bar::WantExport; // Have to rename the namespace, but that defeats the purpose if ignoring the namespace and manually enabling a single class
%rename("%s") foo::bar::WantExport;

%inline %{
namespace foo
{
namespace bar
{
class WantExport
{
public:
	WantExport() = default;
	~WantExport() = default;

	int getValue() const noexcept
	{
		return 5;
	}
};

void DontExport() noexcept;

}
}
%}
```

Let's assume there are a lot of symbols in 3rdparty foo::bar (and it might evolve a lot over time), so it's not practical to manually ignore all symbols except the ones I want. It's a lot easier to ignore the whole namespace and manually add just what I need to be wrapped.
Although `%ignore foo::bar;` correctly removes everything, renaming the class I want doesn't work. I tried to add constructor/destructor as well, no change.
I've read somewhere that you have to rename the namespace your class is in, but in this case it's not possible as it will just re-enable everything.

So my question is:
Is there a way to achieve what I need with current SWIG version? (is it supposed to work, or is it a limitation of the ignore/rename mechanism).
Thanks

**Comment by geefr** [comment]
I think this is the relevant bit of the docs: http://swig.org/Doc4.0/SWIGDocumentation.html#SWIG_chosen_unignore

And I think there's some quirk when mixing ignore/rename, like the ignore acts on the name after you rename it, not before (It's been a while since I used it heavily, but the docs are accurate).

If you're likely to hit other issues with the api, say strange ownership/type mappings it might be simpler to write a small C++ layer around the 3rd party code first, then you're free to have the few methods you actually need without needing a lot of swig declarations (Could do it in the .i files, as in your example).

**Comment by christophe-calmejane** [comment]
Thanks, I'll play around with it again. I wanted to avoid proxying the code, as it's a lot to copy/paste (it was merely a simple example to showcase the issue, my actual case has a lot of APIs, half of them to be "hidden").
Thanks again ;)
