### ISSUE TITLE
Nim module

### ISSUE THREAD

**Issue by tobimensch** [swig/swig#1852]
Nim is a neat language that could benefit a lot from having access to more wrappers for C++ libraries.

I highly encourage SWIG developers to dabble in the language, since you can already do many useful things with it, especially its macros are setting this language apart from others, and if you like python syntax, you will feel right at home, while the efficiency of the generated code is generally in the vincinity of C code.
https://github.com/nim-lang/Nim
https://nim-lang.org/
https://play.nim-lang.org/

Unfortunately I'm not able to write a SWIG module for Nim right now, so my hope is that someone else with an interest in Nim might do it.

This would really help the Nim ecosystem tremendously. C wrappers can already be generated with ease using c2nim and nimterop, however making wrappers for C++ libraries is relatively tedious at the moment, and so things like a Qt5 wrapper for Nim are missing.

I have looked into it a little bit, and it looks to me like the Go module could be a good starting point for writing the Nim module.

If you have any questions about Nim, Nim developers can be found on IRC freenode in #nim among other places.

**Comment by akavel** [comment]
I'd be interested to maybe try adding some very basic support for Nim, on the level outlined as "Experimental" in the docs. However, I'm pretty sure I won't have time to maintain it further onwards (I'm currently only interested in wrapping one specific library). Does it make sense for me to try and start doing this and then contributing? Or is the Team only open to contributors planning for some maintenance? I'd love to try breaking the ground in hope other potentially interested users might have it easier to slowly improve this in the future - but if the current maintainers don't want such partial support, I don't want to waste everyone's time - so before I start, I'd like to ask what's the Team's view on that?

**Comment by wsfulton** [comment]
Hi @akavel. I'm afraid the SWIG community is only going to be hindered if new modules are not well maintained and actively supported by module maintainers.

**Comment by akavel** [comment]
@wsfulton understood, thanks for the reply!

**Comment by kassane** [comment]
Wouldn't it be more interesting just C Backend?

- #2086

**Comment by ojwb** [comment]
Adding a new target language backend is a significant amount of work and SWIG is a volunteer project, so they only get implemented when somebody who wants the support actually does that work.

If that sounds like you then you can find the guide to adding support for a new target language here:

http://www.swig.org/Doc4.1/Extending.html#Extending_nn31

Particularly important to note are the criteria for merging a new target language:

https://www.swig.org/Doc4.1/Extending.html#Extending_language_status

Keeping a feature request ticket open for a new target language doesn't seem useful so I'm going to close this.  Realistically someone will implement support because they want it, not because they see a ticket open for it.
