### ISSUE TITLE
Node 14 Support

### ISSUE THREAD

**Issue by jeanlescure** [swig/swig#1898]
My company uses a paid geolocation library which uses SWIG to generate Node.js bindings.

They are currently using PR #1746 to generate bindings for Node.js v12, but if we try to use the library with Node.js v14 then we get multiple errors, most of them seem to stem from the following:

```
3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/***/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
```

It seems SWIG generates calls to `Set` with 2 arguments where there should be 3. The closest example to a possible fix I could find is the following:

https://github.com/abandonware/node-i2c/commit/5074fbac92c6b19125e809a7853f7e635b9a00a1

Hope this helps get the ball rolling for Node v14 support.

Thanks.

**Comment by wsfulton** [comment]
Good to hear. The SWIG test-suite also fully passes using Node 15. I don't recall anything extra being needed to be done for Node 15 once Node 14 was fixed.

The Set issues mentioned in this issue were fixed in a number of commits by using a  new SWIGV8_ARRAY_SET macro, starting with 11deb82354a47bb291c4e2d43751fe847d71ee58 and I think c4d003e4427af05c635f343b6ced44f793eed2c0 was the last one.
