### ISSUE TITLE
swig 4.0.2 assertion failed on OpenABM-Covid19 project

### ISSUE THREAD

**Issue by olegat** [swig/swig#1901]
SWIG 4.0.2 hits an assertion failure when generating R bindings for this project:
https://github.com/olegat/OpenABM-Covid19

SWIG 3.0.12 is not affect by hit and works as intended.

## Reproduction Steps
**Requisites**
- SWIG 4.0.2 in `PATH`
- make in `PATH` (optional)

**Steps**
```
git clone https://github.com/olegat/OpenABM-Covid19
cd OpenABM-Covid19
git checkout 860f4d32479e959a1eec0adedf41aee8306ee4a5
make Rswig
```
Alternatively instead of using `make`, you can run the SWIG command line directly:
```
swig -r -package OpenABMCovid19 -Isrc -o src/covid19_wrap_R.c -outdir R src/covid19.i
```

## Expected Result (swig 3.0.12)

`make Rswig` creates these files:
- R/OpenABMCovid19.R
- src/covid19_wrap_R.c

**Output** (using SWIG from Cygwin64 on Windows)
```
swig -r -package OpenABMCovid19 -Isrc -o src/covid19_wrap_R.c -outdir R src/covid19.i
src/model.h:101: Warning 314: 'next' is a R keyword, renaming to '_next'
src/constant.h:15: Warning 314: 'FALSE' is a R keyword, renaming to '_FALSE'
src/constant.h:16: Warning 314: 'TRUE' is a R keyword, renaming to '_TRUE'
src/individual.h:75: Warning 314: 'next' is a R keyword, renaming to '_next'
src/individual.h:80: Warning 314: 'next' is a R keyword, renaming to '_next'
src/individual.h:90: Warning 314: 'next' is a R keyword, renaming to '_next'
sed -i 's/R_registerRoutines/R_useDynamicSymbols(dll,0);R_registerRoutines/' src/covid19_wrap_R.c
sed -i 's/.Call("R_SWIG_debug_getCallbackFunctionData"/.Call("R_SWIG_debug_getCallbackFunctionData", PACKAGE="OpenABMCovid19"/' R/OpenABMCovid19.R
sed -i 's/.Call("R_SWIG_R_pushCallbackFunctionData"/.Call("R_SWIG_R_pushCallbackFunctionData", PACKAGE="OpenABMCovid19"/' R/OpenABMCovid19.R
sed -i 's/ans <- new("_p_char"/#ans <- new("_p_char"/' R/OpenABMCovid19.R
```

## Actual Result (swig 4.0.2)

No source files are generated.

**Output** (using SWIG from Homebrew on macOS)
```
swig -r -package OpenABMCovid19 -Isrc -o src/covid19_wrap_R.c -outdir R src/covid19.i
src/model.h:101: Warning 314: 'next' is a R keyword, renaming to '_next'
src/constant.h:15: Warning 314: 'FALSE' is a R keyword, renaming to '_FALSE'
src/constant.h:16: Warning 314: 'TRUE' is a R keyword, renaming to '_TRUE'
src/individual.h:75: Warning 314: 'next' is a R keyword, renaming to '_next'
src/individual.h:80: Warning 314: 'next' is a R keyword, renaming to '_next'
src/individual.h:90: Warning 314: 'next' is a R keyword, renaming to '_next'
Assertion failed: (0), function DohCopy, file DOH/base.c, line 71.
make: *** [src/covid19_wrap_R.c] Abort trap: 6
```

**Comment by xuruilong100** [comment]
Hi, I get the same "assertion failed" when I am making python wrapper of QuantLib on windows(64-bit). The swig.exe you download from swig.org is 32-bit, if it requires memory more than about 1700Mb, you will get "assertion failed". In fact, "assertion failed" is caused by failure of C function `realloc`.

To fix it, you can make a 64-bit swig.exe by yourself.

**Comment by xuruilong100** [comment]
Hi, I get the same "assertion failed" when I am making python wrapper of QuantLib on windows(64-bit). The swig.exe you download from swig.org is 32-bit, if it requires memory more than about 1700Mb, you will get "assertion failed". In fact, "assertion failed" is caused by failure of C function `realloc`.

To fix it, you can make a 64-bit swig.exe by yourself.

**Comment by ojwb** [comment]
_(I deleted a duplicate comment)_

Thanks @xuruilong100.  It seems there are two issues here then.

One is a lack of proper memory allocation failure handling.  I think that once a memory allocation has failed SWIG should give up with an error rather than attempt to fallback to working without that memory.  Further memory allocations are likely to fail too, and the fallback paths would inevitably end up less well tested.  The error reporting path used here should ideally avoid trying to allocate memory since that may also fail.  Better to report the allocation failure simply than to fail to report it at all.

The other is that it seems SWIG tries to allocate a lot of memory here.  This may be specific to SWIG/R or a general thing.  It does seem a large and complex API being wrapped, so maybe it would be hard to avoid.  I'm not intending to try to investigate this myself as I think bugs and missing functionality are more important concerns currently, but happy to review patches if someone wants to try to reduce SWIG's memory usage.

**Comment by xuruilong100** [comment]
Yes, you are right. It seems that a 32-bit software can not handle too much memory, 2Gb is the limit.
