### ISSUE TITLE
AIX 7.1: Tests with Python

### ISSUE THREAD

**Issue by trex58** [swig/swig#1920]
I've ported Swig to AIX 7.1 .

When testing with Python (v3.8 in my case), the following
  ./Examples/Makefile.in : 
       PYTHON_LINK   = @PY3LINK@
  ./Examples/Makefile : 
       PYTHON_LINK   = -lpython3.8
 is not passed when linking Python tests.
Thus, adding  $(PYTHON_LINK)  to the link done for "python:" and "python_cpp:" targets has fixed my issue.
See the attached patch.

[python.patch.txt](https://github.com/swig/swig/files/5796293/python.patch.txt)

**Comment by ojwb** [comment]
Thanks for these AIX fixes.  It's much more helpful to submit patches as pull requests instead of attaching them to an issue.  That way they get automatically tested for most target languages (and several versions of each) and on multiple platforms, and merging is just a matter of clicking a button.  Attaching a patch to an issue means someone needs to download, apply, test by hand, and write a commit message.  That increases the friction and is probably why these simple fixes have sat unapplied for a year.

I've applied the ones which only touch AIX-specific code or which are obviously safe, but the others would really be better resubmitted as PRs.  For example, this one would benefit from testing on more platforms.

**Comment by ojwb** [comment]
I think the fix here is the wrong approach.  The modified link lines already contain `$(PYTHON_DLNK)` which is set higher up to either `@PYTHONDYNAMICLINKING@` or `@PYTHON3DYNAMICLINKING@` and in `configure.ac` that gets set like so:

```
  # Cygwin (Windows) needs the library for dynamic linking
  case $host in
  *-*-cygwin* | *-*-mingw*)
    PYTHON3DYNAMICLINKING="-L$PY3LIB $PY3LINK"
    DEFS="-DUSE_DL_IMPORT $DEFS"
    ;;
  *)PYTHON3DYNAMICLINKING="";;
  esac
```

So I think the correct fix would be to add a case for AIX here.

@trex58 Can you try that and submit a PR with that change if it works for you?

**Comment by ojwb** [comment]
No response from submitter for months so I've pushed an adjusted fix I've not been able to test.

@trex58 Please can you test with SWIG git master and follow up if further changes are needed.
