### ISSUE TITLE
warning C4996: 'PyEval_InitThreads': deprecated in 3.9

### ISSUE THREAD

**Issue by jespergustinmsft** [swig/swig#1996]
Seems SWIG generates code that uses depcrecated methods with Python 3.9;
warning C4996: 'PyEval_InitThreads': deprecated in 3.9

Let me know if you need further information.

**Comment by wsfulton** [comment]
This has been addressed for the forthcoming 4.1.0 version, see 9c50887d

**Comment by jespergustinmsft** [comment]
Awesome! :) Thank you! (And I've learned to search better on GitHub now)

**Comment by bartoli** [comment]
Should this not also account for Py_Limited_API?

We know that for 3.9+, it would call nothing. But if building with 3.9+ a dll that will target an earlier version of the limited API, swig now does not anymore call the method that it should have called?

I just created a request so that PyDeprecated should account for PyLimited_API, if both are done, this should not avoid the warning from appearing back? https://github.com/python/cpython/issues/117927
