### ISSUE TITLE
Java Bindings for Templates in Namespaces

### ISSUE THREAD

**Issue by mauspacker** [swig/swig#2059]
I am trying to create some Java binding for a library using namespace and templates. Unfortunately I ran into a few issues with my template instantiations ending up in the wrong namespaces. I hope I can get some help here.

First of all on the C++ side the classes look like this:

```cpp
namespace foo
{
    class Type
    {};

    template <class T> class List
    {};

    namespace bar
    {
	class Type : public foo::Type
	{};

	using List = foo::List<Type>;
    }
}
```

I want to preserve the namespaces in Java, so what I want to archieve is something like this:

* `example.foo.Type`
* `example.foo.bar.Type`
* `example.foo.bar.List`

My first approach was using `%nspace`

```
// example.i
%module example

%nspace foo::Type;
%nspace foo::bar::Type;

namespace foo
{
    template <class T> class List{};

    class Type{};

    namespace bar
    {
	class Type : public foo::Type {};
    }
}

%template(List) foo::List<foo::bar::Type>;
```

with

```
swig -c++ -java -package example -outdir example example.i
```

This works, but of course I get this:

* `example.foo.Type`
* `example.foo.bar.Type`
* `example.List`

Another approach I tried was to split my namespaces into separate swig modules, like this:

```
// foo.i
%module foo

namespace foo
{
    template <class T> class List{};

    class Type{};
}

// bar.i
%module bar

%import "foo.i"

namespace foo
{
    namespace bar
    {
	class Type : public foo::Type {};
    }
}

%template(List) foo::List<foo::bar::Type>;
```

with

```
swig -c++ -java -package example.foo -outdir example/foo foo.i
swig -c++ -java -package example.foo.bar -outdir example/foo/bar bar.i
```

Now the Java types are at the right place. But `example.foo.bar.Type` is defined like this:

```java
public class Type extends Type {
// [snip] ...
}
```

which of course does not compile. I found out that I could fix this by adding
```
%typemap(javabase, replace="1") foo::bar::Type "example.foo.Type";
```
but for a large API this is cumbersome and feels wrong. And it wouldn't help if `Type` appears as a method parameter for example.

So, what is the right approach to take here? The `%nspace` approach looks promising but is there any way to move `example.List` to `example.foo.bar`? Or is there some `%typemap` magic that could help me? Any help would be highly appreciated.

**Comment by wsfulton** [comment]
C++ code may of course define hundreds of typedefs to the one definition of a class. There is (generally) no equivalent to typedefs in the various target languages including Java. Hence SWIG chooses the definition of the class rather than any of the typedefs to it as the proxy class. 

The following is just c++11 syntax for a typedef:
```c++
using List = foo::List<Type>;
```
For templates, the %template directive provides an instantiation and a proxy class name for that instantiation. A template instantiation is of course in the same namespace as the template definition. Like non-templated classes SWIG provides the proxy class for the instantiated template and not any parsed typedefs to it. The namespace normally does not matter because the namespaces are flattened, except of course, if you are using %nspace. This feature is quite simple and simply mirrors the C++ namespace in the target language equivalent (Java package in this case). There is currently no way to move definitions into another namespace equivalent (Java packages) other than moving the definition in C++ to the namespace that you want to wrap it into. I suspect that providing this support will open up a can of worms, which I think you've already found.

If you can't modify the C++, a typdef hacks will sometimes work. Get SWIG to parse the new namespace hierarchy you want (defining template <class T> class List{}; inside of foo::bar namespace), then adding in typedefs for the C++ compiler so that  any use of foo::bar::List (generated by SWIG) is typedef'd back to the real foo::List.

**Comment by wsfulton** [comment]
Issue #2782 has implemented an extension to the `nspace` feature called `%nspacemove` to move types into any other namespace equivalent in the target language (package for Java).

If you simply add this line before the two `%nspace` directives in your first approach:
```swig
%nspacemove(foo::bar) foo::List;
```
then you will be able to use `example.foo.bar.List` instead of `example.List` as desired.
