### ISSUE TITLE
Syntax error for sizeof("foo")

### ISSUE THREAD

**Issue by tomaszchrost** [swig/swig#2091]
Example of issue:

test.h:
```
#define SEPARATOR "-"
#define SEPARATOR_SIZE ((int)sizeof(SEPARATOR))
typedef char SEPARATOR_ARRAY [SEPARATOR_SIZE];
```

testi.i:
```
%module test
%{
  #include "test.h"
%}

%include "test.h"
```

The code is valid in C, but returns
`test.h:4: Error: Syntax error in input(1).`
When used with swig.

**Comment by ojwb** [comment]
Looking `Source/CParse/parser.y` it appears SWIG's parser doesn't currently handle `sizeof()` applied to a string literal.

**Comment by ojwb** [comment]
I had a quick try at supporting `sizeof <expression>` with the obvious approach:

```
diff --git a/Source/CParse/parser.y b/Source/CParse/parser.y
index c48d3a6f..fd4bebc7 100644
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -6541,6 +6541,10 @@ valexpr        : exprnum {
 		  $$.val = NewStringf("sizeof...(%s)",SwigType_str($6,0));
 		  $$.type = T_ULONG;
                }
+               | SIZEOF valexpr {
+		  $$.val = NewStringf("sizeof(%s)", $2);
+		  $$.type = T_ULONG;
+               }
                | exprcompound { $$ = $1; }
 	       | wstring {
 		    $$.val = $1;
```

Unfortunately this results in a lot of conflicts in the grammar:

```
Source/CParse/parser.y: error: shift/reduce conflicts: 12 found, 6 expected
Source/CParse/parser.y: error: reduce/reduce conflicts: 19 found, 0 expected
```

I suspect that this (combined with how rarely `sizeof` gets used in places that SWIG actually needs to parse it - I don't recall seeing a report of this issue before) probably explains why this didn't get implemented long ago.

**Comment by tomaszchrost** [comment]
I've had some success with the following:

```
diff --git a/Source/CParse/parser.y b/Source/CParse/parser.y
index c48d3a6..8f1e469 100644
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -6531,6 +6531,10 @@ valexpr        : exprnum {
                    $$.val = $1;
                     $$.type = T_STRING;
                }
+               | SIZEOF LPAREN string RPAREN {
+                 $$.val = NewStringf("sizeof(\"%s\")", $3);
+                 $$.type = T_ULONG;
+               }
                | SIZEOF LPAREN type parameter_declarator RPAREN {
                  SwigType_push($3,$4.type);
                  $$.val = NewStringf("sizeof(%s)",SwigType_str($3,0));
```

But this leads to an issues in the generated _wrap.c file; A full example is given below:

test.h
```
#define SEPARATOR "-"
#define SEPARATOR_SIZE ((int)sizeof(SEPARATOR))

typedef char SEPARATOR_ARRAY [SEPARATOR_SIZE];
SEPARATOR_ARRAY TestArray;
```

test.i
```
%module test
%{
  #include "test.h"
%}

%include "test.h"
```

segment of test_wrap.c
```
#ifdef __cplusplus
extern "C" {
#endif
SWIGINTERN int Swig_var_TestArray_set(PyObject *_val) {
  {
    int res = SWIG_AsCharArray(_val, TestArray, ((int) sizeof("-")));
    if (!SWIG_IsOK(res)) {
      SWIG_exception_fail(SWIG_ArgError(res), "in variable '""TestArray""' of type '""char [((int) sizeof("-"))]""'");
    }
  }
  return 0;
fail:
  return 1;
}
```

SWIG_AsCharArray is correctly formatted, but SWIG_exception_fail is not, due to unescaped " characters. Escaping these will reverse the problem, SWIG_exception_fail will be formatted fine, SWIG_AsCharArray will not. Other issues like this will exist.

At least with this I can %ignore TestArray and SEPARATOR_ARRAY and use swig effectively without changing my header file.

**Comment by ojwb** [comment]
FWIW, `sizeof "foo"` is valid too (the parentheses are only required when applied to a type).  It's probably more common to put in the parentheses though.

For a non-wide string literal something like `NewStringf("%lu", (unsigned long)(strlen($3) + 1))` might work.

More generally, it's unhelpful that an error parsing one declaration due to missing support in SWIG prevents generating wrappers at all, especially when it's a header for a library being wrapped which you can't just change and when it isn't declaring something you actually want to wrap.  There are a number of open bugs of this type, mostly for C++11 and later features (SWIG supports quite a lot of C++11 and later, but there are more gaps there).

Perhaps it would be helpful if SWIG could be told to report a warning for such a parse error and have the parser resynchronise and continue parsing.  Exactly how to resynchronise is perhaps a bit tricky - skipping tokens to the next end of line won't always work, nor will next `;` or `}`.

**Comment by tomaszchrost** [comment]
Had success with `NewStringf("%lu", (unsigned long)(Len($3) + 1))`
