### ISSUE TITLE
Swig unable to distinguish between overloaded C++ constructors

### ISSUE THREAD

**Issue by 3oheicrw** [swig/swig#2118]
This piece of code is from cd_plus.h from this project:

https://sourceforge.net/projects/canvasdraw/

```
class CanvasMetafilePS : public Canvas
  {
  public:
    CanvasMetafilePS(const char* filename, int paper, int res_dpi = 0, bool landscape = false)
      : Canvas() { char* landscape_str = "";
      if (landscape)
        landscape_str = "-o";

      char* res_dpi_str = "";
      if (res_dpi)
        res_dpi_str = "-s";

      canvas = cdCreateCanvasf(CD_PS, "\"%s\" -p%d %s%s %s", filename, paper, res_dpi_str, res_dpi, landscape_str); 
    }
    CanvasMetafilePS(const char* filename, double width_mm, double height_mm, int res_dpi = 0, bool landscape = false)
      : Canvas() { char* landscape_str = "";
      if (landscape)
        landscape_str = "-o";

      char* res_dpi_str = "";
      if (res_dpi)
        res_dpi_str = "-s";

      canvas = cdCreateCanvasf(CD_PS, "\"%s\" -w%g -h%g %s%s %s", filename, width_mm, height_mm, res_dpi_str, res_dpi, landscape_str); 
    }
    CanvasMetafilePS(const char* filename, int res_dpi = 0, bool landscape = false)
      : Canvas() { char* landscape_str = "";
      if (landscape)
        landscape_str = "-o";

      char* res_dpi_str = "";
      if (res_dpi)
        res_dpi_str = "-s";

      canvas = cdCreateCanvasf(CD_PS, "\"%s\" -e %s%s %s", filename, res_dpi_str, res_dpi, landscape_str); 
    }
  };
```

I have these lines in my cd.i module:

```
%rename(CanvasMetafilePS_ctor2) cd::CanvasMetafilePS::CanvasMetafilePS(const char* filename, double width_mm, double height_mm, int res_dpi = 0, bool landscape = false);
%rename(CanvasMetafilePS_ctor3) cd::CanvasMetafilePS::CanvasMetafilePS(const char* filename, int res_dpi = 0, bool landscape = false);
```

The problem is it doesn't work. Even though the arguments of the two CanvasMetafilePS constructors are clearly different swig seems unable to distinguish between them.

**Comment by wsfulton** [comment]
How does it not work? I think you mean the C++ compiler is unable to distinguish between two of the constructors when calling `CanvasMetaFilePS(const char*, int)` as this is ambiguous (both the 1st and 2nd constructor provide this signature).

You can use this to ignore the ambiguous constructors:
```swig
%ignore cd::CanvasMetafilePS::CanvasMetafilePS(const char* filename, int paper);
```

**Comment by ojwb** [comment]
William's right, this is a buggy API you're trying to wrap - to make his point clearer, trying to use it from C++ fails without SWIG involved - here I've added a dummy definition of the base class `Canvas` and stripped out the constructor bodies in order to get compilable code, but the constructor argument lists are preserved:

```
struct Canvas { };
  
class CanvasMetafilePS : public Canvas
  {
  public:
    CanvasMetafilePS(const char* filename, int paper, int res_dpi = 0, bool landscape = false)
      : Canvas() {
    }
    CanvasMetafilePS(const char* filename, double width_mm, double height_mm, int res_dpi = 0, bool landscape = false)
      : Canvas() {
    }
    CanvasMetafilePS(const char* filename, int res_dpi = 0, bool landscape = false)
      : Canvas() {
    }
  };

int main() {
    // Both the first and third overload work for (const char*, int)
    CanvasMetafilePS ambiguous("foo", 1);
}
```

Trying to compile this code:

```
$ g++ test.cxx
test.cxx: In function ‘int main()’:
test.cxx:19:40: error: call of overloaded ‘CanvasMetafilePS(const char [4], int)’ is ambiguous
   19 |     CanvasMetafilePS ambiguous("foo", 1);
      |                                        ^
test.cxx:12:5: note: candidate: ‘CanvasMetafilePS::CanvasMetafilePS(const char*, int, bool)’
   12 |     CanvasMetafilePS(const char* filename, int res_dpi = 0, bool landscape = false)
      |     ^~~~~~~~~~~~~~~~
test.cxx:6:5: note: candidate: ‘CanvasMetafilePS::CanvasMetafilePS(const char*, int, int, bool)’
    6 |     CanvasMetafilePS(const char* filename, int paper, int res_dpi = 0, bool landscape = false)
      |     ^~~~~~~~~~~~~~~~
```

To fix the C++ API, someone needs to decide whether `CanvasMetafilePS("foo", 1)` should set `res_dpi` to 1 or `paper` to 1 (or perhaps neither given it doesn't currently work so there's no existing code to be compatible with) and then rework the overload set to eliminate the other (or both)..

Such situations can lurk in an API for some time as they only manifest when someone tries to use an ambiguous case - with SWIG you're likely to hit them because SWIG essentially automatically generates code which calls the entire API.

I suppose SWIG could try to detect such cases and automatically do the appropriate `%ignore` with a warning.  I suspect it's quite tricky to get completely right though and it's an uncommon situation so it's probably not likely to get implemented.

Assuming the suggested `%ignore` works for you, I think we should just close this.
