### ISSUE TITLE
%attribute fails with template classes

### ISSUE THREAD

**Issue by keithmballard** [swig/swig#2142]
I have class ```NodeAccessorBase``` in the namespace ```mesh``` for which I would like to add an attribute based on the underlying C++ getter method.  So I added an attribute and templated type like:
```
%attribute(mesh::NodeAccessorBase, mesh::GlobalIndex, g, global_index);
%template(NodeAccessor) mesh::NodeAccessorBase<mesh::NodeContainer>;
```
However, I get the following compiler error in `_wrap_NodeAccessor_g_get`:
```
Error C3861 'mesh_NodeAccessorBase_Sl_mesh_NodeContainer_Sg__g_get': identifier not found <swig module>
```

I also tried the following:
```
%template(NodeAccessor) mesh::NodeAccessorBase<mesh::NodeContainer>;
%attribute(NodeAccessor, mesh::GlobalIndex, g, global_index);
```
But the Python class for ```NodeAccessor``` did not contain an attribute ```g```.

Am I missing something, or is this a bug with %attribute for templated classes?  Any help would be greatly appreciated.

Note: I am using the release version of Swig 4.0.2 on Windows 10 with Visual Studio 2022.

**Comment by ojwb** [comment]
`%attrbiute` is somewhat lacking in documentation (nothing in the manual) but from a comment in `Lib/typemaps/attribute.swg` (my emphasis):

> Use %attribute when you have a pair of get/set methods to a **primitive type** like in:

A templated class is not a primitive type!

You probably want:

> The %attributeval is the same as %attribute, but should be used when the type is a class/struct (ie a non-primitive type) and when the get and set methods return/pass by value.

Or `%attributeref` is it's passed/returned by reference.

**Comment by KrisThielemans** [comment]
@owjb's answer is about the return type (second argument), while the error message is about the template class in the first argument. I get the same error in a case like this
```c++
template <class T> struct A
{
  T a() const;
  void a(T&);
};
```
The following worked for me
```swig
%attributeref(A<unsigned int>, unsigned int, a)
```

Although having to do this for every instantiation is annoying, it seems quite hard to solve, so for me an update to the documentation could be sufficient.

I believe I can only get this to work if I use `%attribute` with a full specialisation for 2 reasons:
- otherwise the `%mangle(Class)` statements [here](https://github.com/swig/swig/blob/8ce010b915ce83e8c875901fdee1953eb4bcf85c/Lib/typemaps/attribute.swg#L41) do not use the full type specification, leading to a macro definition like `A_a_get` while in the function in the wrapper it is called `A_Sl_unsigned_SS_int_Sg_a_get` (for `A<unsigned int>`), leading to the error quoted by @keithmballard 
- it is unclear what to use as the 2nd argument anyway (the template argument name `T` wouldn't work for similar reasons)

**Comment by ojwb** [comment]
Sorry, looks like I failed to properly understand the problem - thanks for the correction and a solution.

#2170 has moved the `%attribute` docs into the manual since my comment above.  If you think they can be improved, a patch would be great.

**Comment by KeithBallard** [comment]
I am returning to this after a long time!  Sorry for the lack of response.   Specializing the template was the right direction, and the docs have since been updated to clearly reflect it.  However, I would like to point out that %attributeref2 is very useful yet completely absent from the docs.  It might be worth mentioning its existence.

**Comment by ojwb** [comment]
If you've managed to work out what it does a patch to the docs to record that would be great...
