### ISSUE TITLE
GCC 12 error: nested_class_wrap.cxx:2058:10: error: anonymous struct with base classes

### ISSUE THREAD

**Issue by marxin** [swig/swig#2145]
There's a new error reported with GCC 12:

```
[  126s] checking ruby testcase nested_in_template
[  126s] nested_class_wrap.cxx:2058:10: error: anonymous struct with base classes
[  126s]  2058 |   struct : public InnerMultiple {
[  126s]       |          ^
[  126s] nested_class_wrap.cxx:2062:9: error: anonymous struct with base classes
[  126s]  2062 |   class : public InnerMultiple {
[  126s]       |         ^
[  126s] checking perl5 testcase template_explicit
[  126s] checking ruby testcase nested_scope
[  126s] checking ruby testcase nested_template_base
[  127s] make[2]: *** [../../../Examples/Makefile:1015: ruby_cpp] Error 1
[  127s] make[1]: *** [Makefile:69: nested_class.cpptest] Error 2
```

**Comment by ojwb** [comment]
This is literally there in the testcase code rather than being something SWIG generates:

```
#if defined(__GNUC__) || defined(_MSC_VER) || defined(SWIG)
/* some compilers do not accept these */
  struct : public InnerMultiple {
    Integer xx;
  };

  class : public InnerMultiple {
  public:
    Integer yy;
  };
#else
  Integer xx;
  Integer yy; 
#endif
```

The GCC commit that added this warning was:

https://github.com/gcc-mirror/gcc/commit/3ead06c1cff8fb42b4e278c3624917e6b5477f12#diff-3e4dd2298180728f8241b61e9dbfba81913376c27c636d78d40984723f9c1513

It's unclear to me if this case is actually valid standard C++ or not from a brief look.

@marxin Do you know?  I noticed you seem to be a GCC developer while finding the commit above (the most recent commit on the source file where this error is issued was from you).

Some options:

* We could just drop the first part entirely if this isn't valid standard C++
* make the conditional `#ifdef SWIG`
* make it `#if (defined(__GNUC__) && __GNUC__ < 12) || defined(_MSC_VER) || defined(SWIG)` (note this will still trigger for all clang versions, since clang always defines `__GNUC__` to 4)

**Comment by wsfulton** [comment]
Am committing a change using the third option. When/if clang/cl does something similar, we can adjust testcase again.

**Comment by marxin** [comment]
> It's unclear to me if this case is actually valid standard C++ or not from a brief look.

We newly decided not to support it starting from GCC 12.

> 
> @marxin Do you know? I noticed you seem to be a GCC developer while finding the commit above (the most recent commit on the source file where this error is issued was from you).

I'm a GCC developer, but not a C++ front-end developer ;)

Anyway, thanks for the fix.
