### ISSUE TITLE
%newobject does not work with %attribute

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2156]
I chased this one for a while.

Consider the following swig code:
```
%module tst

%{
#include <iostream>
%}

%include <typemaps/attribute.swg>

%attribute(struct2, struct struct1 *, s1, s1_get);
%newobject struct2::s1_get;
%newobject struct2::s1_get2;

%inline %{

struct struct1 {
    struct1(const char *iname): name(iname)
    { std::cout << "alloc " << name << std::endl; }

    virtual ~struct1() { std::cout << "destroy " << name << std::endl; }
    std::string name;
};

struct struct2 {
    struct2(const char *iname): name(iname)
    { std::cout << "alloc " << name << std::endl; }
    virtual ~struct2() { std::cout << "destroy " << name << std::endl; }

    struct struct1 *s1_get() { return new struct1("attr"); };
    struct struct1 *s1_get2(const char *name) { return new struct1(name); };
    std::string name;
};
%}
```
And the following python code to use it:
```
import tst
a = tst.struct2("two")
b = a.s1
c = a.s1_get2("one")
del c
del b
del a
```
Compiled and run with:
```
$ swig -python -py3 -c++ tst.i
cminyard@t560:~/t1/tst4$ g++ -fPIC -g -shared -I /usr/include/python3.8 -o _tst.so tst_wrap.cxx 
cminyard@t560:~/t1/tst4$ python3 usetst.py 
alloc two
alloc attr
alloc one
destroy one
destroy two
```
There should be a "destroy attr" after the "del b" call, but it doesn't get destroyed.  Looking in the wrapped code, it's not a new pointer event thought it's declared as such.  I also tried using:
```
%newobject struct2::s1
```
but that didn't help either.

**Comment by ojwb** [comment]
`attribute.i` is the public interface file here, but including the internal implementation doesn't seem to be the cause of the problem here.

`%attribute` seems to be under-documented (nothing in the manual), but the comment in the implementation header says (my emphasis):

> Use %attribute when you have a pair of get/set methods to a **primitive type** like in:

A `struct` isn't a primitive type.

There's:

> The %attributeval is the same as %attribute, but should be used when the type is a class/struct (ie a non-primitive type) and when the get and set methods return/pass by value.

But you aren't returning by value.  Also:

> Use %attributeref when you have const/non-const reference access methods for primitive types or class/structs

But you aren't returning by reference.

So I think your case isn't actually supported by the %attribute family of macros currently.

**Comment by cminyard** [comment]
Ok.  I'm implementing this another way, anyway.  If you want I can write a new issue to document %attribute and friends.

**Comment by ojwb** [comment]
> If you want I can write a new issue to document %attribute and friends.

Yeah, I think it'd be better to move the docs to the manual rather than having them as comments in `Lib/typemaps/attribute.swg`.  There may also be useful stuff in `CHANGES` entries as well (there's way too much stuff that **only** got documented in `CHANGES` so `%attribute` is better in that regard at least).
