### ISSUE TITLE
Move %attribute documentation into the main documentation

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2166]
We talked about this in #2156, here is a reminder to move the documentation.

**Comment by ojwb** [comment]
Oh I thought you were offering to do this, but maybe I misunderstood.

If it's just a reminder for one of the existing active developers to do it, realistically it's not going to happen as unfortunately we're already drowning in open bugs (815 open tickets here and in the old SF trackers currently, and that's after a concerted campaign recently to close those which have have since been fixed or are invalid).  At least there is currently documentation of this, just not in the most helpful place.

**Comment by cminyard** [comment]
On Tue, Jan 25, 2022 at 03:29:33PM -0800, Olly Betts wrote:
> Oh I thought you were offering to do this, but maybe I misunderstood.
> 
> If it's just a reminder for one of the existing active developers to do it, realistically it's not going to happen as unfortunately we're already drowning in open bugs (815 open tickets here and in the old SF trackers currently, and that's after a concerted campaign recently to close those which have have since been fixed or are invalid).  At least there is currently documentation of this, just not in the most helpful place.

Ok, I can look at doing this.  I was already thinking about modifying
the documentation for %ignore, since this would be mostly cutting and
pasting, I can probably do this pretty easily.
