### ISSUE TITLE
Support for luau

### ISSUE THREAD

**Issue by smokhov** [swig/swig#2177]
Hello, any chance to support the https://github.com/Roblox/luau Lua extension? What would it involve? Thanks!

**Comment by ojwb** [comment]
Your link says:

> The runtime mostly preserves Lua 5.1 API, so existing bindings should be more or less compatible with a few caveats.

Have you tried the current SWIG generated bindings?  If so, what fails?

If changes are needed to SWIG's lua support for this, it really needs someone who knows luau and is motivated to get it to work to contribute a patch.

**Comment by smokhov** [comment]
I see, do you have a list of active maintainers for each language and who is the current maintainer for Lua proper? The main addition Luau added is type annotations. I am working to create a minimum working example to test atm. I have my .i file that I otherwise use for for C#, Java (and partially Python) for a C++ library, and started toying with the built-in SWIG backend for Lua. Let me wrap my mind around it and get back on this. Feel free not to keep this issue open so it doesn't clutter your already busy issues list; can re-open later if anything fruitful comes up. Thank you!

**Comment by ojwb** [comment]
There's a kind of list in `COPYRIGHT` but it's woefully out of date as people have tended to fade out rather than explicitly retiring or resigning, and new people often fail to be added.  Currently the copyright year there is 2011 which is a bit of an indication about how much love that file gets.

We also have a lot of casual but recurring contributors, and with git making the "commit bit" less of a necessity it's harder to pin down who's a "maintainer" exactly.

Something like `git log --format='%C(auto) %h %ci %an %s' Lib/lua Source/Modules/lua.cxx` can offer clues about who's actually active.

From the look of that we don't really have an active SWIG/Lua maintainer currently.  Clean patches with a sensible intent should still get merged though.

Depending how the type annotations work, you might find the recently added PHP type declaration support a useful approach - each `in` and `out` typemap can have a `phptype` attribute giving a PHP type or list of PHP types that it accepts, which are carried through to the generated wrapper code.

**Comment by ojwb** [comment]
Closing as suggested.  If this gets to the point where a ticket would provide a useful point to coordinate efforts feel free to get someone to reopen it.
