### ISSUE TITLE
Segmentation fault when running PDFNetWrapper [PHP8] 

### ISSUE THREAD

**Issue by mnguyenpdftron** [swig/swig#2201]
OS: Ubuntu 18.04/Linux
Target: PHP 8.0.13
Problem:  We still experienced `Segmentation fault` when running PHP8 PDFNetWrapper using the current swig master branch (`4.1`). We had no issues with 4.0.2 or previous releases with PHP7.
```
mitch@mitch-VirtualBox:~/PDFNetWrappers/Samples/AddImageTest/PHP$ sh ./RunTest.sh 
PHP Fatal error:  Declaration of Popup::Create(SDFDoc $arg1, Rect $arg2): Popup must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
PHP Fatal error:  Declaration of FileAttachment::Create(SDFDoc $arg1, Rect $arg2, $arg3, string|int $arg4): FileAttachment must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
PHP Fatal error:  Declaration of Ink::Create(SDFDoc $arg1, Rect $arg2): Ink must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
PHP Fatal error:  Declaration of Caret::Create(SDFDoc $arg1, Rect $arg2, Rect $arg3): Caret must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
PHP Fatal error:  Declaration of Circle::Create(SDFDoc $arg1, Rect $arg2): Circle must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
PHP Fatal error:  Declaration of HighlightAnnot::Create(SDFDoc $arg1, Rect $arg2): HighlightAnnot must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
PHP Fatal error:  Declaration of LineAnnot::Create(SDFDoc $arg1, Rect $arg2): LineAnnot must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
PHP Fatal error:  Declaration of FreeText::Create(SDFDoc $arg1, Rect $arg2): FreeText must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
PHP Fatal error:  Declaration of Link::Create(SDFDoc $arg1, Rect $arg2, Action $arg3): Link must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
PHP Fatal error:  Declaration of Movie::Create(SDFDoc $arg1, Rect $arg2): Movie must be compatible with Annot::Create(SDFDoc $arg1, int $arg2, Rect $arg3): Annot in Unknown on line 0
Segmentation fault (core dumped)
```
Steps to reproduce:  https://github.com/PDFTron/PDFNetWrappers

**Comment by ojwb** [comment]
Can you reduce the problem to a small self-contained reproducer?  (Or maybe problems to reproducers - it seems there's the fatal errors and the seg fault, though perhaps the latter is fallout from the former.)

I had a quick look and the codebase you link to seems to be (a) enormous and (b) to contain custom typemaps.  I don't really have the time or enthusiasm to dive into a large codebase I don't know at all I'm afraid.

You can disable generation of type declarations completely with:

```
%feature("php:type", "0");
```

That should make the fatal errors go away.  The default `compat` setting of this is meant to work with existing wrappers though, so it'd be good to get to the bottom of what's going on there.

**Comment by mnguyenpdftron** [comment]
I added  `%feature("php:type", "0");` and rebuilt. I noticed the difference:
```
mitch@mitch-VirtualBox:~/PDFNetWrappers/Samples/AddImageTest/PHP$ sh ./RunTest.sh 
PHP Fatal error:  Declaration of Popup::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of FileAttachment::Create($arg1, $arg2, $arg3, $arg4) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of Ink::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of Circle::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of HighlightAnnot::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of LineAnnot::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of FreeText::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of Movie::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of RedactionAnnot::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of Screen::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of Square::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of Squiggly::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of StrikeOut::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of Underline::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0
PHP Fatal error:  Declaration of Watermark::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0

PDFNet is running in demo mode.
Segmentation fault (core dumped)
```
Some APIs were running (`PDFNet is running in demo mode.`) but some weren't.
I also ran into errors like
```
free(): double free detected in tcache 2
Aborted (core dumped)
```
I will try to make a small self-contained reproducer.

**Comment by mnguyenpdftron** [comment]
Hello, this is the link to download the file. You can than unzip it and run `build.sh`. If you have any question, please let me know.
https://drive.google.com/file/d/1cA_HNsKCX5zN_ZGnj7G8Ptusp7U8IAqD/view?usp=sharing

**Comment by ojwb** [comment]
> PHP Fatal error:  Declaration of Popup::Create($arg1, $arg2) must be compatible with Annot::Create($arg1, $arg2, $arg3) in Unknown on line 0

Oh, the problem here is that the number of arguments in the overridden version is different which was made into an error in PHP 8.0 (in 7.4 it was a warning):

```
$ php7.4 -r 'class Popup {function Create($a, $b){}} class Annot extends Popup {function Create($a, $b, $c){}}'
PHP Warning:  Declaration of Annot::Create($a, $b, $c) should be compatible with Popup::Create($a, $b) in Command line code on line 1
$ php8.0 -r 'class Popup {function Create($a, $b){}} class Annot extends Popup {function Create($a, $b, $c){}}'
PHP Fatal error:  Declaration of Annot::Create($a, $b, $c) must be compatible with Popup::Create($a, $b) in Command line code on line 1
```

I'm not sure SWIG can do much about that automatically.  You may have to `%rename` the method in either the parent class or the subclasses (or `%ignore` one of them if it's better not to wrap it at all than to rename it).

> this is the link to download the file.

A 45MB zip file is very much not a **small** self-contained reproducer.  From a brief look, it looks a lot like you've just put the repo contents in a zip file.  The issue here is not that I can't use `git clone` but rather that digging through a large code base to narrow down the cause of the problem is going to be a lot more work for someone completely unfamiliar with it (like me) than it would be for someone familiar with it (presumably you).

Trying deleting large parts of it and check if the problem remains (pro-tip: `git commit` after each successful reduction to a scratch branch so you can back up if the problem goes away, or if you realise you stopped reproducing the real problem a few changes ago).  Repeat such deletions until you have something where you can't remove anything that remains and still reproduce the problem.

**Comment by mnguyenpdftron** [comment]
@ojwb I saw changes in typemaps https://github.com/swig/swig/blob/master/Lib/php/typemaps.i
We have custom typemaps for example for Unicode:
```
	%typemap(in) UString, const UString
	{  
#if PHP_MAJOR_VERSION >= 7
		convert_to_string_ex(&$input);
		char* temp$argnum = Z_STRVAL_P(&$input);
#else
		convert_to_string_ex($input);
		char* temp$argnum = Z_STRVAL_PP($input);
#endif
		$1 = UString(temp$argnum);
	}
```
Does that mean we need to make changes accordingly? It seems to work fine when we commented out our custom typemaps above.

**Comment by ojwb** [comment]
I think your problem is actually due to that preprocessor conditional.  As written it'll be evaluated when SWIG is run, but you presumably want that conditional in the generated code so you can use a single generated wrapper for all PHP versions - that means you need to use `%#if`, etc:

```
	%typemap(in) UString, const UString
	{  
%#if PHP_MAJOR_VERSION >= 7
		convert_to_string_ex(&$input);
		char* temp$argnum = Z_STRVAL_P(&$input);
%#else
		convert_to_string_ex($input);
		char* temp$argnum = Z_STRVAL_PP($input);
%#endif
		$1 = UString(temp$argnum);
	}
```

`PHP_MAJOR_VERSION` is probably not defined at SWIG time, in which case you'll be trying to use the code for PHP5 here for all PHP versions.

There are also a few things that could be cleaned up too for PHP >= 7:

* `convert_to_string_ex(x)` is just an alias for `convert_to_string(x)` in PHP8.  In PHP7 it looks like they also end up doing the same thing, but less directly so.
* `Z_STRVAL_P(p)` is defined as `Z_STRVAL(*(p))` so `Z_STRVAL_P(&$input)` -> `Z_STRVAL(*(&$input))` -> `Z_STRVAL($input)`.
* You could make it `%typemap(in, phptype="string")` and then SWIG will add a suitable PHP type declaration for this parameter for PHP8.

**Comment by mnguyenpdftron** [comment]
@ojwb Thanks for the feedback. `PHP_MAJOR_VERSION` is our preprocessor that we define during compile time. 
I also noticed there is a double deletion :
```
free(): double free detected in tcache 2
Aborted (core dumped)
```
In our typemap, we do define:
```
	%typemap(freearg) UString const &
	%{
		delete($1);
	%}
```
I wonder if there is any change internally.

**Comment by ojwb** [comment]
What's your typemap for `UString const &`?

It shouldn't need to allocate an object with `new` so I wouldn't expect you'd want a `freearg` typemap that calls `delete`.

E.g. SWIG's built-in typemap for `std::string` for PHP is:

```
    %typemap(in, phptype="string") const string & ($*1_ltype temp) %{
        convert_to_string(&$input);
        temp.assign(Z_STRVAL($input), Z_STRLEN($input));
        $1 = &temp;
    %}
```

Here `temp` will be a `std::string` created local to the wrapper function and `$1` is set to point to that.

**Comment by mnguyenpdftron** [comment]
%typemap(in) UString const &
	{  		
#if PHP_MAJOR_VERSION >= 7	
		convert_to_string_ex(&$input);
		char* temp$argnum = Z_STRVAL_P(&$input);
#else
		convert_to_string_ex($input);
		char* temp$argnum = Z_STRVAL_PP($input);
#endif
		$1 = new UString(temp$argnum);
	}
	
	%typemap(freearg) UString const &
	%{
		delete($1);
	%}

**Comment by mnguyenpdftron** [comment]
@ojwb : https://github.com/swig/swig/blob/master/Lib/php/typemaps.i @line 287 
```
#ifdef __cplusplus
    ptr=new $*1_ltype();
#else
    ptr=($*1_ltype) calloc(1,sizeof($*1_ltype));
#endif
    $1=&ptr;
```

**Comment by ojwb** [comment]
The typemap you're linking to is for a very different case to the one you're trying to handle - it's for the "opaque handle passed as `void**` situation" and needs to create a new C/C++ object if PHP `Null` is passed.  We can't allocate that on the stack because the object needs to live on after the function call (notice there's no corresponding `freearg` typemap).

A much better model for your `UString` typemap is the `std::string` typemap.  It seems your `UString` constructor doesn't take a length (but instead presumably relies on a terminating zero byte to determine the length) but otherwise the typemaps can probably be identical.

There doesn't seem to be a SWIG bug here, so closing.

**Comment by mnguyenpdftron** [comment]
@ojwb I figured it out why there was a double deletion.
Before, it was:
```
delete(ptr);
thrown: (no delete here)
return;
fail:
delete; 
SWIG_FAIL();
```

now (swig 4.1):
```
delete(ptr);
fail:
delete(ptr); 
return;
```
A fix is :
```
%typemap(freearg) UString const &
	%{
		if($1) { delete($1); $1=0;}
	%}
```

**Comment by mnguyenpdftron** [comment]
I also noticed it properly returns in Python3 wrapper code using swig 4.1:
```
delete(ptr);
return resultobj;
fail:
delete(ptr); 
return NULL;
```

**Comment by ojwb** [comment]
Heh, coincidentally I pushed 1707d6b89ba63d4bca1fc2d841a7e879b5ed2c6e which should fix that just over an hour ago.  Can you retry with current git master?

**Comment by mnguyenpdftron** [comment]
yes, I can

**Comment by mnguyenpdftron** [comment]
@ojwb : it's working fine now.
