### ISSUE TITLE
Output file is too big to compile

### ISSUE THREAD

**Issue by xuruilong100** [swig/swig#2236]
I am using swig to make a python wrapper of QuantLib, while the output file is more than 50Mb now, and clang can not compile it on my laptop.

So, is there a way to generate smaller output file, that clang can handle it?

**Comment by ojwb** [comment]
There's `-fcompact` but that just makes the output file smaller, it doesn't make the code simpler:

> It simply removes blank lines and joins lines of code together.
> This is useful for compilers that have a maximum file size that can be handled.

If the problem is the complexity of the code rather than the size of the file in bytes, turning down the optimisation level may help (e.g. `-O1` or `-O0` instead of `-O2`) and turning of debug symbols (don't use `-g`) may too.  Otherwise you might just have to use a build machine with more memory.

**Comment by xuruilong100** [comment]
Thank you @ojwb 

I turn off `-Ofast`, and it works.

**Comment by ojwb** [comment]
Great.

Another thought occurred to me - if you're using `%exception` then the trick shown here of pulling out the exception handling into a helper function which rethrows and recatches the exception can help:

https://survex.com/~olly/talks/pythonic-swig/pythonic-swig/#slide20
https://survex.com/~olly/talks/pythonic-swig/pythonic-swig/#slide21

**Comment by wsfulton** [comment]
Also look at using fragments to reduce the amount of code generated  if you have custom typemaps.

**Comment by ojwb** [comment]
@wsfulton Do we have a place in the docs for such tips?

**Comment by wsfulton** [comment]
Not really. There are suggestions throughout the docs, fragments and the motivation for them are clearly documented, perhaps that could be improved. The %exception idea you mentioned above is a C++ trick, not dissimilar to advising to use a function instead of copy/paste code. SWIG shouldn't be advising how to write obvious C++ code like this, but I suppose in this case, it is combined with a SWIG feature, so enhancing the %exception section with this suggestion and an example would be useful.

Suggestions around build systems and compiler specific info is what the https://github.com/swig/swig/wiki/ is for and easily modified by users.
