### ISSUE TITLE
Go Shared Pointer

### ISSUE THREAD

**Issue by ted537** [swig/swig#2250]
If a C++ function returns a shared pointer, is there any way to access the methods directly from Go, or is it necessary to bind some kind of `Get()` method first?

**Comment by ojwb** [comment]
SWIG has support for `std::shared_ptr` (and the earlier boost version) for some target languages and can generate wrappers which hide the `shared_ptr`, but this functionality hasn't been implemented for Go so far.  There's already #2030 open for that, so closing this issue as a duplicate.

There was a PR for a more limited form of `std::shared_ptr` support (#2041) but it lacked test coverage and the submitter decided to close it rather than bring it up to the standard required to be merged.  If the functionality that provides is enough for you, you could probably just copy the typemaps from there into your project.
