### ISSUE TITLE
%shared_ptr breaks with C++ class inheritance by making swigCMemOwn private

### ISSUE THREAD

**Issue by wolski** [swig/swig#230]
see:
https://github.com/swig/swig/blob/master/Lib/java/boost_shared_ptr.i#L149

I noticed it by having a class B inheriting from A.
As soon as I made
%shared_ptr(A)
the java code breaks with:

Description Resource    Path    Location    Type
The field DllVersion.swigCMemOwn is not visible DllVersionUEye.java /uEyeSwig/src/ch/imagic/imagesource/idsueye line 29 Java Problem

**Comment by haseebq** [comment]
+1

**Comment by wsfulton** [comment]
The derived class should be using `swigCMemOwnDerived` instead of `swigCMemOwn`. Both are private by design. What is a full use case that you are seeing? We already test for B inheriting from A in the test-suite, so there must be something else you are doing. Do you perhaps not have `%shared_ptr` for both A and B? If not, there should be a warning telling you so though.

**Comment by haseebq** [comment]
Here's what I have in the .i file:

```
%shared_ptr(xxx::yyyy::LogSink)             // <-- Base
%shared_ptr(xxx::AndroidLogCatSink)    // <-- Inherits from xxx::yyy::LogSink
%shared_ptr(xxx::DailyFileSink)                // <-- Inherits from xxx::yyy::LogSink
```

**Comment by twankamp** [comment]
Are you sure you didnt use director with your derived class? Then it would be exactly #759  which I'm also encountering.
