### ISSUE TITLE
Java: size_t (64bit unsigned) is converted to jlong (64bit signed)

### ISSUE THREAD

**Issue by Basskrapfen** [swig/swig#2307]
Hi,

while generating some C++ to Java interfaces with SWIG, I've realized that SWIG is converting a size_t (64bit, unsigend on a Linux64 machine) to a jlong (long) which is a 64bit signed value. When returning max_value of size_t, Java sees this value as -1.
If uint64_t is used, the type is converted to BigInteger which is a more bulky but can cover the full range.

The change seems to come from this line and has been added somewhere before 2004:
https://github.com/swig/swig/blob/5e06e0931edee5d102ef45fa74ed805368cb22dd/Lib/java/java.swg#L1374

Is this a conscious decision to use unsigned long or is this decision from a time when 64bit machines were not around?

Thanks

**Comment by wsfulton** [comment]
Yes, this is so that it works on 32-bit systems by default. You can change the behaviour via these typemaps:
```
%apply unsigned long long { size_t };
%apply const unsigned long long & { const size_t & };
```
This then provides the 64-bit equivalent mappings, that is, BigInteger Java instead of Java long mappings everywhere. It causes problems compiling the STL containers if you are using those though. Fixed in 280b3a908ed23c14aac4ce8a3a10d003f64fbbd0 though. Alternatively you can just apply the typemaps selectively to named variables, such as: 
```
%apply unsigned long long { size_t a, size_t func }; // 64-bit mapping only applies to return of func, the input variable a, but not b and c below
size_t func(size_t a, size_t b, size_t c);
```
Please take a closer look at the Typemaps chapter in the documentation for more on using typemaps with %apply and %clear.
