### ISSUE TITLE
PHP -noproxy option missing in release v4.1.0

### ISSUE THREAD

**Issue by twistdroach** [swig/swig#2419]
We use this option today with previous versions, but need php8 support.

It is still in the documentation: https://www.swig.org/Doc4.1/Php.html#Php_nn2_6_1

**Comment by ojwb** [comment]
It seems it got removed in aa180f2c4da83893e56c44c7bf60bd16a8e1128d leaving the (undocumented and non-standard compared to other target languages) `-noshadow` option which has exactly the same effect.

I don't understand why it was removed (the commit message isn't helpful) - I'd understand more if we'd removed `-noshadow`.

Neither option is/was tested by the testsuite, and a lot has changed in the PHP support code in SWIG 4.1.0, but please try `-noshadow` and if that works we can just add `-noproxy` back controlling the same internal mechanism in 4.1.1.

**Comment by ojwb** [comment]
I tried `Examples/php/class` with `-noshadow`.  It produces slightly different wrapper code, but not the desired flattened function API.

Looking at `Source/Modules/php.cxx`, this option just sets `shadow` to `0` and that only gates adding the symbol for the class and finding the base class to inherit from.  The PHP class is still created, so all it really does is create code that's probably wrong in at least some cases.

Unfortunately a working `-noproxy` option is not a trivial change as the PHP backend has changed hugely since SWIG 4.0.2.

We used to wrap by creating an extension exporting a flat function API, which was then wrapped to PHP classes by a generating those classes as a `.php` wrapper file, which called the flat function API, but now we directly create the PHP classes using PHP's C API.  Overall this is a big improvement - it's simpler, lower overhead, and has solved various corner case bugs which were previously in the "too hard to fix" pile.

However, that flat function API is no longer there for `-noproxy` to simply expose.

We also have no testsuite coverage of `-noproxy` that I can see, except for a single Perl5 example (`Examples/perl5/reference`) so there's not even a useful existing set of testcases to test a new `-noproxy` implementation against.

I'm afraid I can't make any promises as to if/when I would be able to work on this.  The PHP backend overhaul for 4.1.0 already ate up far more time than I really had to spare and I need to catch up on other projects.

I can try to review a patch if someone wants to work on this (and if you've have a project using this you can at least confirm it works well enough to wrap that).

We should at least update the documentation to reflect reality for 4.1.1.

**Comment by twistdroach** [comment]
Thanks for looking into this -  I think we are going to port over to the newer non-functional style since that seems to be the best tested/supported path.

**Comment by ojwb** [comment]
I think wrapping C++ classes as PHP classes will produce a more satisfactory PHP API in general.  The only real downside of switching an existing SWIG-wrapped API away from using `-noproxy` is that it's not compatible for existing PHP code using that API, but at least the updates required are mechanical and could be automated with a script.

I'm leaning towards declaring that support for `-noproxy` in SWIG/PHP is gone for good (which is a regression from older versions, but it happened in 4.1.0 and breaking changes are allowed in x.y.0 releases).

Restoring it at this point seems a lot of work, the lack of test coverage is problematic and makes it hard to reimplement (while adding the missing test coverage as part of restoring it means even more work), and it's only supported for a small minority of other SWIG target languages (C#, Java, Perl and Python).

**Comment by twistdroach** [comment]
Sounds good to me - I removed the `-noproxy` flags from my builds and refactored the PHP code to use the "new" interface style.  Appreciate your help & consideration on this.

**Comment by wsfulton** [comment]
Not yet in release-4.1 branch.

**Comment by wsfulton** [comment]
Now added into release-4.1 branch.
