### ISSUE TITLE
Forward declarated types

### ISSUE THREAD

**Issue by vakokako** [swig/swig#2436]
I have two classes that use each other in their interfaces like this:

```cpp
// A.h

class B;

class A {
public:
    void use(B b);
};
```

```cpp
// B.h

class A;

class B {
public:
    void use(A a);
};
```

And I want to generate c# bindings for both `A` and `B`. Swig generates bindings for class `B` and I can use it in other places, but because `B` comes after `A` in swig code, instead of `A::use(B)` swig generates an unknown type `A::use(SWIGTYPE_...B)`. For `B::use(A)` everything is generated correctly.

Is this expected? and is this somehow solvable?

**Comment by ojwb** [comment]
I can't reproduce.  You don't show the interface file you're using, so I made a simple `test.i`:

```
%module test
%{
#include "A.h"
#include "B.h"
%}
%include "A.h"
%include "B.h"
```

Testing with SWIG 4.1.0:

```
$ swig -c++ -csharp test.i
$ grep -r SWIGTYPE .
$ 
```

**Comment by wsfulton** [comment]
The code provided is not valid C++. If you run it through gcc, you get:
```
error: ‘b’ has incomplete type
     void use(B b) {}
                ^
```
You do need to use valid C++ code with SWIG. SWIG is more forgiving for missing type info compared to a C++ compiler. It generates a SWIGTYPE_ class due to incomplete type info and so is behaving as expected.

**Comment by ojwb** [comment]
@wsfulton The code you quote is invalid, but it isn't the same as the code in the reported example - you've added a method body inline.

A declaration with an incomplete parameter type should be OK, so the provided `A.h` and `B.h` seem fine to me, and GCC is happy if you instead add the definition of the methods after both classes have been declared, e.g.:

```
$ cat foo.cc
#include "A.h"
#include "B.h"

void A::use(B b) { }
void B::use(A a) { }
$ g++ -Wall -O2 -std=c++98 -pedantic -c foo.cc
$
```

Closing the issue seems reasonable, though not because the example is invalid C++ but rather because I couldn't reproduce and the submitter hasn't responded for just shy of 6 months.
