### ISSUE TITLE
virtual explicit operator failed to parse

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#2474]
Hello,

this code fails to parse

```c++
class TestVirtualExplicitOperator
{
public:
	virtual ~TestVirtualExplicitOperator() = default;

	virtual explicit operator std::string() const noexcept = 0;
};
```

Thanks!

**Comment by ojwb** [comment]
Essentially this is another instance of #302.

**Comment by christophe-calmejane** [comment]
Thanks for the heads up, I searched the opened issues but failed to properly identify 302 as fully related ;)
Glad to see you are working on it, and let me know if you want me to test something, I've quite a few big projects that fails to parse due to heavy C++11/14/17 syntax usage.

**Comment by ojwb** [comment]
I'm working on it, but hitting strange testcase failures I don't understand.  I'll try to look again next week with a fresher mind, and if I still can't work out what's up try to push a cleanish branch for others to take a look.

It'd be helpful if the parser could recover from a parse failure and skip the problematic declaration with a warning, since at least then you could wrap the parts of a header SWIG can parse.  The tricky part for doing that seems to be finding a decent strategy for resyncing.  After the next `;` will work in many cases, but sometimes it really needs to be after a `}`, and I think not necessarily the next one (even ignoring balanced pairs of `{`...`}`).  Also it probably should error out in some cases.
