### ISSUE TITLE
Support for HHVM extension

### ISSUE THREAD

**Issue by ogarbe** [swig/swig#249]
Hello,

Do you think you can provide php hhvm extension connexion as you provide php "standard" extension ?

HHVM is a JIT compiler for PHP created by Facebook (https://github.com/facebook/hhvm)

Here is the explanation on how HHVM extensions works with C/C++ https://github.com/facebook/hhvm/wiki/Extension-API 

Thanks in advance

regards

**Comment by ng420** [comment]
Hi! I'm working on this issue. Refer https://github.com/ng420/swig-hhvm

**Comment by lsySenior** [comment]
hi ng420, how can I genetate hhvm extension using swig-hhvm?

**Comment by ng420** [comment]
Hi lsySenior, you need a config.cmake file and a usual swig interface file to compile the extension. Look at https://github.com/ng420/swig-hhvm/tree/master/Examples/hhvm for examples. If you need more help, https://github.com/ng420/swig-hhvm/tree/master/sample has build.sh and test.sh which contain the commands I run to build and execute an extension.

**Comment by lsySenior** [comment]
hi ng420, thanks for your reply. The version of hhvm is 3.0.1 in my enviroment. I figured out that the cpp file generated by swig-hhvm had included some headers existing in higher hhvm versions, like native-prop-handler.h. So I think if used it in the wrong way or some other reasons. have any suggestions?

here are some code from the generated cpp file:
HHVM_MALIAS(AdminWrap, __construct, _wrap_AdminWrap, __construct);
HHVM_MALIAS(AdminWrap, code, _wrap_AdminWrap, code);
HHVM_MALIAS(AdminWrap, msg, _wrap_AdminWrap, msg);
HHVM_MALIAS(AdminWrap, submit_sql, _wrap_AdminWrap, submit_sql);
HHVM_MALIAS(AdminWrap, __destruct, _wrap_AdminWrap, __destruct);
Native::registerNativePropHandler<AdminWrapPropHandler>(_wrap_AdminWrap::s_className);
Native::registerNativeDataInfo<_wrap_StringVector>(_wrap_StringVector::s_className.get());

**Comment by ojwb** [comment]
It seems the C++ API to HHVM is still evolving significantly, so at this stage you are probably best off using a newer version of HHVM (I've tested with 3.12 with success), unless you are up for the job of sorting out compatibility with older HHVM versions and providing a clean patch.

Right now the key goal is to get the branch into a state where we can get it merged to git master.

**Comment by ojwb** [comment]
The HHVM support unfortunately never got finished (though it was mostly functional and mainly needed documenting properly) and so never got merged.  I think ng420 got a job with Facebook and that ate all his spare time and energy.

HHVM has since evolved and AIUI now only support the "Hack" language.  This doesn't seem to see much active use outside Facebook which makes HHVM support less useful for SWIG.  The other issue is I don't think anyone active in SWIG development knows much about HHVM or Hack.

So this really needs somebody knowledgable about HHVM who to pick up the existing work and push it through to completion.

**Comment by ojwb** [comment]
> HHVM is a JIT compiler for PHP

This was essentially the premise of this feature request, but HHVM has evolved since (as I noted in my last comment above) to the extent that this premise is no longer true.  HHVM's git repo README now says:

> HHVM is an open-source virtual machine designed for executing programs written in Hack.

The Hack language doesn't seem to have any notable use outside Facebook. We've not had anyone actually request support for Hack and it doesn't seem very useful for SWIG to target.  We also don't have anyone volunteering to work on support for it.

So I'm closing this issue.
