### ISSUE TITLE
How to rename a automatically generated swig class

### ISSUE THREAD

**Issue by Tunaaaaa** [swig/swig#2516]
I have a function which return a pointer of a self-defined class. When I tried to convert c++ to java by swig, it automatically generate a type of "SWIGTYPE_p_xxxx", how to rename this class?

my function is `Session* Interpreter::createSession(const ScheduleConfig& config),` here Session is a class I defined, the function return a ptr which is not support in java.

after convert, swig will generate a type called "SWIGTYPE_p_Session", how to rename this to "Session_p" or anything else? (just for neat and clean, I don't need to access details through this pointer)

I tried `%rename(Session) SWIGTYPE_p_MNN__Session;` It doesn't work.

Thank you very much.

**Comment by ojwb** [comment]
If you get `SWIGTYPE_p_xxx` in the generated wrappers that means that SWIG hasn't seen a definition for class `xxx`.  Unless this is really meant to be an opaque type, exposing the class definition to SWIG is the solution.  (If it really is meant to be an opaque type, I'm not sure how to rename the wrapper for it.)

SWIG **can** wrap a function returning a pointer to an object.  Unless the method name is misleading, you'll also want to mark this method with `%newobject` so that SWIG knows it's a factory function.  See the Java chapter of the manual for details.

**Comment by ojwb** [comment]
The target of `%rename()` is a name in the API being wrapped, whereas `SWIGTYPE_p_MNN__Session` is a target language (Java in this case) name, so that wouldn't make sense as a way to specify an alternative name here, but conceptually we could support some way of renaming these for the case where they're really an opaque type, but a quick look at the code suggests that wouldn't be easy to implement.  If you do have an opaque type and want to give it a nicer name your best option is to hit the SWIG-generated code with a regexp hammer, e.g.

```
perl -pi -e 's/\bSWIGTYPE_p_Session\b/Session/g' *.java
mv SWIGTYPE_p_Session.java Session.java
```

No response for 2 months so assuming my original answer solved the reporter's problem and closing.
