### ISSUE TITLE
-swiglib is absolute

### ISSUE THREAD

**Issue by ibell** [swig/swig#253]
I have built versions of swig using scilab and matlab support, but 

swig -swiglib

points to the location of the share folder when swig is built, and means that the binary code is not relocatable.  I need to have several versions of swig on my computer to built stock swig builds, swig+scilab builds, and swig+matlab builds.  CMake chokes on swig if swig -swiglib doesn't point to a valid path containing swig.swg

FWIW, swigwin is relocatable (swig -swiglib always points to the right place), I wonder why that isn't possible on linux.

**Comment by ton** [comment]
Would it not be possible for an additional option that searches/reports the SWIG library using `-swiglib` relative to the location of the `swig` executable itself?

**Comment by nightlark** [comment]
I also ran into this -- it would be nice if other platforms besides just Windows did something similar to looking for a `Lib` folder relative to the executable (except using `../share/swig/<version>`), thought a search for this indicates that it looks like every OS (macOS, Linux, FreeBSD, Solaris) have their own quirks for finding the executable location.

As an alternative, I think for what I'm trying to do the ability to set a custom location relative to the install prefix would be quite helpful (e.g. instead of `<prefix>/share/swig/<version>` set the location to `<prefix>/bin/Lib`).

**Comment by PatTheMav** [comment]
FWIW, we build SWIG on CI as part of our build-dependencies for [obs-studio](https://github.com/obsproject/obs-studio) and the current behaviour requires us to fudge around with the `SWIG_LIB` environment variable on macOS, because the swig library directory is hardcoded to the build directory from the CI runner.

The reason for pre-compiling swig on CI is to allow our contributors to just download these packages and _not_ compile them locally again and also not having to mix specific versions of libraries and binaries required to build OBS with "official" variants installed system-wide.

While using `SWIG_LIB` works, it requires our contributors to find the necessary documentation about it and setting it manually, while being mindful of path changes with every new version. Searching relative to the binary path on systems using GNU paths (e.g. `<BINARY_DIR>/../share/swig/<SWIG_VERSION>` would be a big help.

**Comment by VestniK** [comment]
Non relocatable swig package adds some problems to maintain conan package. Right now conan recipe patches swig before build: https://github.com/conan-io/conan-center-index/blob/master/recipes/swig/all/patches/0001-swig-linux-library-path.patch to make binary package relocatable.

**Comment by leleliu008** [comment]
may be read a environment variable likes `SWIG_DATA_DIR` at run time is a better solution, likes git does https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

sometimes we need download prebuild binary not want to build from source especily writting script. because build from source need install C compiler, install C compiler usually should ues system's default package manager, there are many package managers to be used, it's not a easy thing.
