### ISSUE TITLE
Throwing random objects

### ISSUE THREAD

**Issue by mmomtchev** [swig/swig#2536]
Consider the `catches_strings.i` unit test:

```cpp
struct StringsThrower {
  static void charstring() {
    throw "charstring message";
  }
  static void stdstring() {
    throw std::string("stdstring message");
  }
};
```

Here is the corresponding JS test:

```js
exception_thrown = false;
try {
  catches_strings.StringsThrower.charstring();
} catch (e) {
  if (!e.message.includes("charstring message"))
    throw new Error("incorrect exception message " + e.message);
  exception_thrown = true;
}
if (!exception_thrown)
  throw new Error("Should have thrown an exception");
```

JS expects an error containing a string? However C++ doesn't throw an `std::exception`, it throws a string - shouldn't JS receive a plain string object? Or is expected that any object thrown from C++ should get transformed to a JS `Error` instance?

**Comment by ojwb** [comment]
If a target language allows a native string to be thrown as an exception, that seems a reasonable way to wrap it (at least provided it's something users of the language would expect rather than something that's technically possible but nobody would ever do).  The current Javascript implementation may have copied from another target language as some require that an exception derive from a particular base class, e.g.:

```
$ python -c 'raise "hello"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: exceptions must derive from BaseException
```

```
$ php -r 'throw "hello";'
PHP Fatal error:  Uncaught Error: Can only throw objects in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code on line 1
```

(Meanwhile Ruby seems to implicitly wrap the thrown string in an object:

```
$ ruby -e 'raise "hello"'
-e:1:in `<main>': hello (RuntimeError)
```
)

**Comment by ojwb** [comment]
Also, see `git grep 'typemap.*throws.*string'` for existing target language support for automatically wrapping `std::string` C++ exceptions to target language string exceptions.

**Comment by wsfulton** [comment]
I added the throws typemaps to handle thrown strings (char * and std::string) as a lot of the handling was previously was missing and it made handling errors in a runtime testcase across all languages much easier. We only throw a very few different target language exceptions and doing something different will create extra handling required on the user side. I suppose that if a language does support throwing a string instead of an exception an alternative could be implemented. As the implementation is in typemaps, a user is free to do what they like! 

I threw target language exceptions for consistency and we have never previously thrown a string instead of an exception. I don't think it is really even possible for most languages to throw a string instead of an exception (as you show for PHP and I take it that Ruby is actually converting the string into a RuntimeError from the info above). If I recall correctly, it was quite hard getting anything to work for JS across the different types of JavaScript interpreters.

**Comment by ojwb** [comment]
> I threw target language exceptions for consistency and we have never previously thrown a string instead of an exception.

FWIW, at least Lua appears to throw as a Lua string:

```
// for throwing of any kind of string, string ref's and string pointers
// we convert all to lua strings
%typemap(throws) string, string&, const string&
%{ lua_pushlstring(L,$1.data(),$1.size()); SWIG_fail;%}

%typemap(throws) string*, const string*
%{ lua_pushlstring(L,$1->data(),$1->size()); SWIG_fail;%}
```

We don't seem to have such typemaps for Perl, but Perl exceptions are just strings in my experience (looking at `perldoc -f eval` it seems you can call `die` with an object reference, though I don't think I've ever seen that; I'm not a hardcore Perl coder though).

**Comment by mmomtchev** [comment]
Ok, I will keep the current implementation in NAPI - throwing the actual underlying object - instead of its string representation
