### ISSUE TITLE
Renaming is mostly broken in JavaScript

### ISSUE THREAD

**Issue by mmomtchev** [swig/swig#2542]
`constructor_rename` and `overload_rename` produce invalid code that compiles but the tests pass because there is no `_runme.js`.

`rename_cameltest` works because of a coincidence:
```
$ ENGINE=node make rename_camel.cpptest
```
```
$ grep _wrap_hello rename_camel_wrap.cxx
```
```cpp
static SwigV8ReturnValue _wrap_hello(v8::Local<v8::Name> property, const SwigV8PropertyCallbackInfo &info) {
static SwigV8ReturnValue _wrap_hello(const SwigV8Arguments &args) {
  if(args.Length() != 0) SWIG_exception_fail(SWIG_ERROR, "Illegal number of arguments for _wrap_hello.");
SWIGV8_AddStaticVariable(exports_obj, "HELLO", _wrap_hello, JS_veto_set_variable, context);
SWIGV8_AddStaticFunction(exports_obj, "hello", _wrap_hello, context);
```

There is a name collision on `wrap_hello` which works through overloading because a getter and a method have slightly different call signatures.

**Comment by mmomtchev** [comment]
Maybe if tests like this one are supposed to work, `Swig_name_wrapper` should probably take renaming into account? Or, renaming should also create a new full `name` instead of changing only `sym:name` which might not be unique, this is something that should be valid for all languages?

**Comment by ojwb** [comment]
Re: the rename_camel part, I think the problem is in this code calling `Swig_name_wrapper()`:

```
int JSEmitter::emitConstant(Node *n) {  
  // HACK: somehow it happened under Mac OS X that before everything started  
  // a lot of SWIG internal constants were emitted  
  // This didn't happen on other platforms yet...  
  // we ignore those premature definitions  
  if (!State::IsSet(state.globals(HAS_TEMPLATES))) {  
    return SWIG_ERROR;  
  }  
  
  Wrapper *wrapper = NewWrapper();  
  SwigType *type = Getattr(n, "type");  
  String *name = Getattr(n, "name");  
  String *iname = Getattr(n, "sym:name");  
  String *wname = Swig_name_wrapper(name);  
  String *rawval = Getattr(n, "rawval");  
  String *value = rawval ? rawval : Getattr(n, "value");  
  
  // HACK: forcing usage of cppvalue for v8 (which turned out to fix typedef_struct.i, et. al)  
  if (State::IsSet(state.globals(FORCE_CPP)) && Getattr(n, "cppvalue") != NULL) {  
    value = Getattr(n, "cppvalue");  
  }  
  
  Template t_getter(getTemplate("js_getter"));  
  
  // call the variable methods as a constants are  
  // registered in same way  
  enterVariable(n);  
  state.variable(GETTER, wname);  
  // TODO: why do we need this?  
  Setattr(n, "wrap:name", wname);  
```

This seems wrong - `wname` is being constructed using `name` (which is the C/C++ name being wrapped i.e. `hello`) rather than `iname` (which is the `sym:name` attribute) which is the target language name i.e. `HELLO`:

```
String *wname = Swig_name_wrapper(name);  
```

In `JSEmitter::emitFunction()` we use `iname`/`sym:name` for the wrapper function (which is correct) hence the collision:

```
String *wrap_name = Swig_name_wrapper(iname);
```

The `name` and `sym:name` attributes are typically the same unless `%rename` is used, so it's an easy pitfall for new target language backends to be using the wrong one in more obscure cases without it being spotted for a while.

However, arguably this is really the wrong function to be calling as this isn't a function wrapper but a getter, so I think this should ideally be changed to:

```
Swig_name_get(getNSpace(), iname);
```

That might need further fixes elsewhere in the backend code though.
