### ISSUE TITLE
swig3.x python generated code segfaults

### ISSUE THREAD

**Issue by vigsterkr** [swig/swig#256]
We are currently experiencing some problems with the swig3.x generated python interface. Namely, when a wrapped object's destructor, i.e `_wrap_delete_<object>` is being called we are getting a segfault, see my last 3 comments in shogun-toolbox/shogun#2313

Basically when we generate the swig interface with `-modern -modernargs` arguments due to commit 8998f11ca39d60ae4593a3fab2fc86ab92439003 the following line is being added, to every function that is being wrapped in case of swig3.x:
```
if(!PyArg_UnpackTuple(args,(char *)"delete_CSVFile",0,0)) SWIG_fail;
```
if `args` is actually `NULL` this call will cause a `SEGFAULT`. this does not happen in swig2.x...

**Comment by besser82** [comment]
@wsfulton: It looks like it is related to `-modernargs`.  Without that switch or explitly specifying `-nomodernargs` segfaults are gone.

**Comment by ptomulik** [comment]
Hi, some time ago I was working on #250 and have seen several segfaults during test suite run with ``-builtin -modernags``. I remember it was this specific combination of flags causing problems. Maybe it's the same issue?

**Comment by besser82** [comment]
Thanks for your remark…  Lemme try adding `-fastunpack`…  Let's see what the outcome is…

**Comment by besser82** [comment]
So…  I just experimented using ´-fastunpack´ with the following outcome:

  * Using `-builtin -modernags` results in segfaulting as described by @vigsterkr.
  * Using `-builtin -nomodernags` results in working binaries.
  * Using `-builtin -modernags -fastunpack` results in working binaries, too.

@wsfulton:  Any suggestions / ideas about how to fix that inside of SWIG?

**Comment by besser82** [comment]
@ptomulik can you try to recompile swig with my patch from #372 and see if `-builtin -modernags` still crashes your testsuite for #250?

**Comment by ptomulik** [comment]
Sorry, but I'm short of time and can't do it ATM.  Please ping me back in a week or two if you'll still  need assistance.

**Comment by wsfulton** [comment]
Is this the normal SWIG test-suite that is being referred to? If so, I can run it with -builtin -modernargs with this patch and report back.

**Comment by besser82** [comment]
Closed https://github.com/swig/swig/pull/372, because branch-name changed.  See the difference in TravisCI-Python-tests between:
* no-changes to code-base:  https://github.com/swig/swig/pull/381
* one-line change to code-base:  https://github.com/swig/swig/pull/382

**Comment by wsfulton** [comment]
My goodness, do you want to use every computer on the Travis infra? 11 hours later and your commits are still queued up! You've kicked off heaps of unnecessary long running tests. We need to use the free Travis resources respectively, if you want to test lots of flags on Travis, then at least remove the non-python tests from .travis.yml, so that they aren't needlessly run. 

I'm not going to test -builtin with any other flags on an ongoing basis, but I would like to add just -O (which implies -modern etc). Please don't open any more tickets for this one line change, I'll close #381 and #382 and apply the actual code change myself once all the Travis boxes have finished testing.

Have you tested any additional flags without -builtin with your changes?

**Comment by besser82** [comment]
Yes, I've tested `-modern(args)`-flags without `-builtin` as well. They work as expected like before the patch.

The additional tests shouldn't take that much additional time on TravisCI…  The last triggered test are not finished so far, because I rebased the commits three times and couldn't cancel the previously invoked tests.  See: https://travis-ci.org/swig/swig/pull_requests

**Comment by wsfulton** [comment]
I just cancelled builds 1351 and 1352 so that just one more of #381 and #382 will now run.

**Comment by wsfulton** [comment]
The test-suite is now passing using '-builtin -modernargs' as well as just '-modernargs'.

**Comment by besser82** [comment]
Thanks a lot!  Tested with backported patch and swig-3.0.5.  Now all works fine.
