### ISSUE TITLE
No documentation in manual for ccomplex.i and complex.i

### ISSUE THREAD

**Issue by nschaeff** [swig/swig#2560]
The following line in the header file parsed by swig was working just fine with swig 4.0.2:

     typedef complex double cplx;

This is standard C99, but now fails with swig 4.1.1 with error:

>  Error: Syntax error in input(1)

**Comment by ojwb** [comment]
You don't say when this used to work, but you're presumably hitting this change in 4.1.0:

```
2020-10-10: lpsinger
            #1770 Correct C complex support.
            _Complex is now parsed as a keyword rather than complex as per the C99 standard.
            The complex macro is available in the ccomplex.i library file along with other
            complex number handling provided by the complex.h header.
```

The situation now is that `_Complex` works by default.  If you want `complex` to work you need to either `#define complex _Complex` or (for languages which support it) `%include ccomplex.i` (which defines it for you, amongst other language-specific handling).

Recognising `complex` by default doesn't really work because it breaks being able to use `complex` as a normal identifier (see e.g. #252).

I would close this as not-a-bug, but it seems that `ccomplex.i` (and also `complex.i`) aren't documented in the manual, only in CHANGES and `Lib/python/README` (which realistically close to no users are going to be looking at), so I'm not sure how we really expect users to know they need to include them.

**Comment by nschaeff** [comment]
Thank you very much for the quick answer. I'm happy to use _Complex.
(For the record, I mention in the OP that it used to work 4.0.2. I did not test anything between 4.0.2 and 4.1.1)

**Comment by ojwb** [comment]
Oh, so you did.  Sorry, somehow I managed to read around that.
