### ISSUE TITLE
Ruby 3.2.2/Swig4.1.1 symbol not found in flat namespace (_st_delete)

### ISSUE THREAD

**Issue by mnguyenpdftron** [swig/swig#2587]
Swig 4.1.1
Ruby 3.2.2 macOS
Error: symbol not found in flat namespace (_st_delete)
I ran into the error when using ruby 3.2.2 to build a ruby wrapper. Previously, it built and ran successfully using ruby 2.6.
Steps to reproduce:
https://github.com/PDFTron/PDFNetWrappers#macos

**Comment by ojwb** [comment]
I'm no expert on Ruby and I don't use macos, but a quick poke shows the ruby headers have:

```
/usr/include/ruby-3.1.0/ruby/st.h:int rb_st_delete(st_table *, st_data_t *, st_data_t *); /* returns 0:notfound 1:deleted */
/usr/include/ruby-3.1.0/ruby/st.h:#define st_delete rb_st_delete
```

It seems `st.h` is not getting included for you (some platforms add a `_` prefix on external symbols, so that's probably where that is from).

The only use of `st_delete` in SWIG is in `Lib/ruby/rubytracking.swg` which conditionally does:

```
#if !defined(ST_DATA_T_DEFINED)
/* Needs to be explicitly included for Ruby 1.8 and earlier */
#include <st.h>
#endif
```

Hopefully that's enough of a clue for you to debug what's going on.

**Comment by rchennafi** [comment]
Thanks for the suggestion.

We came to the realization that the find_ruby directive in CMake does not respect RVM environments unless using FIND_VIRTUALENV. This lead to us build with the incorrect version headers.

**Comment by ojwb** [comment]
Thanks for following up.  Not a SWIG bug so closing.
