### ISSUE TITLE
std::map for type with no default constructor

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#2625]
Hi,

currently, this doesn't compile
```swig
%module test

%include <std_map.i>

%inline %{
struct NoDefaultConstructorStruct final
{
	int value{0};
	NoDefaultConstructorStruct(int v) : value(v) {}
};
using NoDefaultConstructorStructMap = std::map<int, NoDefaultConstructorStruct>;
%}

%template(NoDefaultConstructorStructMap) std::map<int, NoDefaultConstructorStruct>;
```

Because there is no default constructor for the struct, the typemaps for std::map generates code in wrap.cxx file using c++11 code that do not support this.
Using c++17 `insert_or_assign` in std::map typemaps solves that issue.

Does it make sense to require c++17 for the generated wrap.cxx file? (in this case I may be able to make a PR fixing the typemap)
Is there a mechanism to select the c++ version based on the user's project c++ version?
Is there a way, on a per project basis, to override the default typemaps for std::map and replace `operator[]` with `insert_or_assign`?

Thanks,
Chris

**Comment by ojwb** [comment]
> Does it make sense to require c++17 for the generated wrap.cxx file?

SWIG aims to generate C++98/C90 code, unless wrapping C/C++ language features that inherently require a newer standards version (e.g. `std::unordered_set` is a C++11 feature).  Even then it's sometimes many versions between a compiler implementing some of a new standard version and implementing all of it so best to limit the newer language features used to those actually required.

I'd think in this case you could use something like this construct:

```
#if __cplusplus >= 201703L
      self->insert_or_assign(key, x);
#elif X_IS_DEFAULT_ASSIGNABLE
      (*self)[key] = x;
#else
      if (self->find(key) != self->end()) self->erase(key);
      self->insert(std::pair(key, x));
#endif
```

`X_IS_DEFAULT_ASSIGNABLE` really needs to be hooked up somehow if this is to go in the default typemaps as the fallback is less efficient when we don't need to use it.  Maybe there's a better fallback version, but I'm not seeing one for C++98.  In C++11 one could gdo:

```
     auto r = self->emplace(key, x);
      if (!r.second) *(r.first) = x;
```

However, it seems there are further compilation errors due to other code so more work would be needed:
```
test_wrap.cxx:4360:29: error: no matching function for call to ‘std::pair<int, NoDefaultConstructorStruct>::pair()’
 4360 |           value_type *vp = (new std::pair<T,U>());
```

**Comment by christophe-calmejane** [comment]
Thanks for the info about C/C++ target version.

Since the typemaps for `std::map` are already using `operator[]`, maybe this solution would be enough for the time being
```
#if __cplusplus >= 201703L
      self->insert_or_assign(key, x);
#else
      (*self)[key] = x;
#endif
```

And later add `X_IS_DEFAULT_ASSIGNABLE` is doable.
(C++17 has been there for quite some time now, and all major compilers fully support basic STL improvements, so I suppose it shouldn't be an issue to introduce more advanced/efficient code now).

**Comment by ojwb** [comment]
Good point - just using `insert_or_assign` for a C++17 compiler and the current code otherwise fixes this for the majority of users (and increasingly so as time passes).  Also if you're wrapping such a `std::map` then you're presumably using a C++17 compiler as otherwise it's going to be awkward to use from hand-written C++.

To get preprocessor directives copied to the output, either use `%{`...`%}` to delimit the block (such blocks aren't preprocessed by SWIG), or if using `{`...`}` delimiters prefix each directive inside you want copied with a `%`, e.g.:

```
%fragment("SWIG_FromCharPtrAndSize","header",fragment="SWIG_pchar_descriptor") {
SWIGINTERNINLINE PyObject *
SWIG_FromCharPtrAndSize(const char* carray, size_t size)
{
  if (carray) {
    if (size > INT_MAX) {
      swig_type_info* pchar_descriptor = SWIG_pchar_descriptor();
      return pchar_descriptor ?
        SWIG_InternalNewPointerObj(%const_cast(carray,char *), pchar_descriptor, 0) : SWIG_Py_Void();
    } else {
%#if PY_VERSION_HEX >= 0x03000000                                               
%#if defined(SWIG_PYTHON_STRICT_BYTE_CHAR)                                      
      return PyBytes_FromStringAndSize(carray, %numeric_cast(size, Py_ssize_t));
%#else                                                                          
      return PyUnicode_DecodeUTF8(carray, %numeric_cast(size, Py_ssize_t), "surrogateescape");                                                                  
%#endif                                                                         
%#else                                                                          
      return PyString_FromStringAndSize(carray, %numeric_cast(size, Py_ssize_t));                                                                               
%#endif                                                                         
    }                                                                           
  } else {                                                                      
    return SWIG_Py_Void();                                                      
  }                                                                             
}                                                                               
} 
```

See the manual for full details.
