### ISSUE TITLE
C/C++ standards versions required for compiling SWIG itself

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2628]
I know we aim to support compiling generated wrappers as C90/C++98 - to be clear this is **NOT** about changing that.

Is that requirement also meant to apply to compiling SWIG itself?  I'd vaguely assumed so, but after a `git bisect` run I somehow ended up with `-ansi -pedantic` having been automatically added to my `CFLAGS` and `CXXFLAGS` even after resetting to HEAD and accidentally discovered there are multiple places where this isn't currently the case, e.g.:

```
CParse/templ.c: In function ‘Swig_cparse_template_expand’:
CParse/templ.c:488:11: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  488 |           Parm *parm = ParmList_nth_parm(templateparms, index);
      |           ^~~~
CParse/templ.c:576:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  576 |             Node *tynode = Swig_symbol_clookup(s, 0);
      |             ^~~~
```

The first was introduced by 817c700ced95b2fc615e1619c89fcec21f66af55, the second by 674abaddbf854e2374f115ef08e59fa79702e19a, both changes authored by @wsfulton (not pointing fingers here - my point is that if wsfulton is not keeping to strict C90 that makes me wonder if that's actually an aim).

There are some in parser.y too (one introduced by me, another by wsfulton).

It looks like these are all since the last release.

On the C++ side, there's also a use of `nullptr` in `javascript.cxx` introduced very recently.

If it is genuinely important to non-hypothetical users to be able to compile SWIG itself as C90/C++98 we should fix these and add flags to CI to enforce (ideally to developer builds too so you don't have to wait for CI to fail to find transgressions).

I think my view is that requiring declarations before code is not helpful and adds extra friction during development.  Especially given the mix of C and C++ code in SWIG , it's hard to always remember that you're meant to do last-century-style declaration at the top of the block while also thinking about actually getting everything else right about the code.

Having to split declaration and assignment in C code introduces scope for bugs as uses of the unassigned variable can accidentally be introduced someone changing the code.

Mixed declarations and code are supported by many C compilers as an extension before C99 (GCC, clang and MSVC all allow them without even a warning with `-std=c90`/`/std:c90` - I tested MSVC 19 using godbolt.org).

There are several ways to formally legitimise declarations after code.  We could:

* say "C90 but with declarations after code allowed"
* say "C99"
* just compile everything (or much more of the code) as C++

Mostly separately to this, there's the question what the C++ baseline should be for compiling SWIG itself.  C++ has evolved significantly since C++98 and there's an increasing amount of nicer ways of doing things that aren't valid C++98 and that I find myself having to remember not to do, which is extra cognitive load I could do without.

**Comment by ojwb** [comment]
I'm sticking this on the 4.2 milestone since if the aim is to be compilable with a strict C90 compiler then we've regressed on that and it seems we've done so since the last release.

**Comment by ojwb** [comment]
We also ought to have a CI build that enforces whatever the requirement is (e.g. `-std=c99` in `CFLAGS`, `-std=c++98` in `CXXFLAGS` if that's what we're aiming for) or else we're going to regress on this again.  Wecan probably just add extra flags in one of the existing jobs.

**Comment by ojwb** [comment]
> I think my view is that requiring declarations before code is not helpful and adds extra friction during development. Especially given the mix of C and C++ code in SWIG , it's hard to always remember that you're meant to do last-century-style declaration at the top of the block while also thinking about actually getting everything else right about the code.

For similar reasons, I think formally allowing `//` comments in C code would be helpful (e.g. I just spotted 5b9179ea7e2e8b18d8b44e5d5e271e2168606197 added one in `Source/CParse/templ.c` back in July and nobody seems to have noticed until now).  Like mixed declarations and code, most C compilers have accepted them as an extension even before C99 so allowing them doesn't limit portability much if at all in practical terms.  (And again I'm not talking about generated code here.)

**Comment by wsfulton** [comment]
The SWIG code base is quite clearly C90 with a token amount of C++98 thrown in. I understand it is like this as the original team of authors tried full-on C++ back in the nineties and made a complete mess and then converted it to C. I'd love to convert it to something more modern, but think that my time is better spent on providing useful improvements to users rather than going on a developer self-gratification journey with a complete redesign of DOH and all the subsequent knock-ons, I know exactly what I want to do for this, but one day I might resist though! Meanwhile, using C90 is the way it is, most of the UNIX space still uses C, it isn't ideal but not controversial nor a major problem. Supporting C90 and C++98 is much easier for users who compile SWIG so the fact that the code base really is this is a bonus for users. I unfortunately still need it for RHEL6 and more recently another user requested it, see #2762.

On the subject of coding to the right _last-century-style_ standard, we all get this wrong. There are countless times I code up some C++11 into a testcase when it should be C++98. While somewhat frustrating that there isn't just one standard to code to, it is a fact of life that one has to code to the appropriate style for any given project that one works on. And in SWIG's case one has there are many different places that one has to think about which standard is relevant. Any standards blunders indeed should be caught by the CI system, it's one of the primary reasons we have CI testing.

SWIG's standards testing is comprehensive and non-trivial, as it needs to be. I've restored C90 and C++98 into our CI testing in cb5ac19ab5f640ed12280c69499dabbbe154780e as it got lost. The only reason some non-conformance slipped in is because it isn't being tested.

I think we could consider a switch from C90 to C99 though in a future release, but for swig-4.2.x we are still C90.

**Comment by ojwb** [comment]
You've ignored a couple of key points I made above which are:

* Mixed declarations and code in C are in reality supported very widely (because most compilers supported them as an extension well before they were standardised).
* `//` comments in C seem to have ubiquitous support in practice (they actually come from C's ancestor BCPL).

The vast majority of so-called C portability problems are instances of these, which don't actually harm portability in practice.  In the case of mixed declarations and code, this actually helps to avoid bugs because you can initialise a variable fully at the point of declaration and avoid the possibility of use of an undefined value (or use of a dummy initialised value like `0` or `NULL` which is only set so the variable isn't undefined between declaration and being properly initialised).

Moreover, RHEL 6 has GCC 4.4 (https://access.redhat.com/solutions/19458) which seems to support C99  (https://en.cppreference.com/w/c/compiler_support#C99_features) so the oldest case you raise would actually even have standardised support for these two.

**Comment by wsfulton** [comment]
Yes we agree, let's think about changing it to C99 for swig-4.3 as stated. I don't see a reason to change it for swig-4.2.x as as the goal has always been C90 compliance and it is already C90 compliant.

**Comment by ojwb** [comment]
Sounds good - sorry, I had interpreted "in a future release" as you putting this off until the long term, not just until 4.3.0.
