### ISSUE TITLE
Consts with 'valuetype' returning NULL pointer crash SWIG

### ISSUE THREAD

**Issue by rokj-isystem** [swig/swig#2766]
SWIG 4.2.0, with command line:
`swig -java -c++ consts.i`
will crash given interface file with the following contents: 
```
/* consts.i */
%module consts
%javaconst(1);
struct S {
  static const uint16_t C1 = 0x1000;
  static const uint16_t C2 = C1 | (1  << 2);
};
```
Issue happens because when handling constant C2, a NULL pointer is returned on call from java.cxx line 1532:
`SwigType *valuetype = Getattr(n, "valuetype");`
Which then on call in java.cxx line 1633:
`if (SwigType_type(valuetype) == T_CHAR)`
crashes in typesys.c an line 1402 because strncmp is called with c being a NULL pointer:
```
1397    int SwigType_type(const SwigType *t) {
1398      char *c;
1399      /* Check for the obvious stuff */
1400      c = Char(t);
1401    
1402      if (strncmp(c, "p.", 2) == 0) {
```
Best regards,
RokJ

**Comment by ojwb** [comment]
Reproduced, but worked with SWIG 4.1.0.  Seems to be specific to Java (notably works with `-csharp` and `%csconst(1);`).

`git bisect` shows this started failing with 3a6d12475141cbace350d1ef7cddd38232c2a7eb.  I'll investigate further.

**Comment by ojwb** [comment]
In `csharp.cxx` there's an additional check so the NULL pointer isn't used, at least in this case.

This fixes the crash here:

```
--- a/Source/CParse/parser.y
+++ b/Source/CParse/parser.y
@@ -3162,10 +3162,12 @@ c_decl  : storage_class type declarator cpp_const initializer c_decl_tail {
              if ($5.val && $5.type) {
                /* store initializer type as it might be different to the declared type */
                SwigType *valuetype = NewSwigType($5.type);
-               if (Len(valuetype) > 0)
-                 Setattr($$,"valuetype",valuetype);
-               else
+               if (Len(valuetype) > 0) {
+                 Setattr($$, "valuetype", valuetype);
+               } else {
+                 Setattr($$, "valuetype", $2);
                  Delete(valuetype);
+               }
              }
              if (!$6) {
                if (Len(scanner_ccode)) {
```

I've not yet tested it more widely yet.

I wonder if we should also/instead make `SwigType_type()` more robust and return `T_USER` for a `NULL` input (like it does for anything else there isn't a suitable type code for).  That should be correct here as `uint16_t` is an unknown type here (because `stdint.i` hasn't been `%include`-d).

**Comment by ojwb** [comment]
Working on merging my fix above, but struggling to turn the reproducer here into a testcase.  The problem is that it only fails if SWIG doesn't know about `uint16_t`, but in that case the generated code with `%javaconst(1);` doesn't compile.

I guess it could be an error testcase, but that seems clumsy.

**Comment by ojwb** [comment]
Looking harder, I'm still not seeing how to trigger this with a testcase which can actually be compiled once generated.

> I guess it could be an error testcase, but that seems clumsy.

Error testcases are hardwired to run with `-python`.  I could invent more testsuite machinery to allow that to be varied, but that seems overkill without more motivating examples where we want an error testcase to run with another target language, so I'm going to commit the fix without a regression test.
