### ISSUE TITLE
Fix Java static inspection warning: finalize() does not call super.finalize()

### ISSUE THREAD

**Issue by ekeithkw** [swig/swig#278]
A proxy class currently (in SWIG 3.0.2) is generated with a finalize() method as follows:

  protected void finalize() {
    delete();
  }

Static code inspections flag this method because it doesn't call the super method.  The fix would be to generate it as follows:

  protected void finalize() throws Throwable {
    super.finalize();
    delete();
  }

**Comment by ojwb** [comment]
It looks to me like these warnings are false positives since (unless `%typemap(javabase)` is used to make a SWIG-generated proxy class inherit from a non-SWIG generated class) SWIG also generated the parent class.  A SWIG generated parent class will have a `finalize()` method but it's not useful to call it since it also just calls `delete()`.  It looks like it `delete()` is at least idempotent, but this would still add some overhead (unless the compiler is smart enough to eliminate the redundant call).

If `%typemap(javabase)` is used and the specified class has a `finalize()` method it looks like it won't get called.

I think the best answer to this is probably to stop using finalizers.  I did attempt that (see #1550 and my working patch to use a cleaner instead in #1554) but it's really blocked on how to transition to it.

**Comment by wsfulton** [comment]
Yes, adding in `super.finalize()` would add a small overhead and be quite pointless. If a user decides to remove the base class's finalize() method, the code also won't compile, so this has a chance of breaking some existing typemaps. But, primarily, closing as the static code inspection tool is generating a false positive.

**Comment by wsfulton** [comment]
Oh also, any user can provide their own typemaps to implement the suggestion above if they value keeping the static code analysers happy.
