### ISSUE TITLE
Using %nspace with std templates

### ISSUE THREAD

**Issue by ojwb** [swig/swig#2782]
I'm using `%nspace` so C++ `My::Foo` is wrapped as `My.Foo` in C# (picking an affected target language to make the examples here concrete - I think the problem I described below is also the case for any language which supports `%nspace`, though it's arguably worse for statically typed languages as you more often need to write out the actual type in those).

Say I have an API which uses C++ `std::vector<My::Foo>` - if let `%nspace` also apply to `std::vector` (e.g. via `%nspace;`) then for

```
%template(FooVector) std::vector<My::Foo>
```

the C# wrapper is named `std.FooVector`.  While there's a certain logic to that if you're thinking about the C++ side, I really want to wrap as `My.FooVector` instead as that seems more natural in the target language (where `std::vector` is just an implementation detail), but I can't seem to persuade SWIG to do that.  The only other choice I seem to have is to wrap as just `FooVector` in C# (with no namespace) by not letting `%nspace` apply here.

https://www.swig.org/Doc4.2/SWIGPlus.html#SWIGPlus_renaming_templated_types_namespaces seems relevant, but I couldn't seem to find anything there which helps.

**Comment by ojwb** [comment]
Reproducer:

```
%module x
%include std_vector.i
%nspace;
// Uncomment to get FooVector instead of std.FooVector in C#
// %nonspace std::vector<My::Foo>;
namespace My { struct Foo {}; }
%template(FooVector) std::vector<My::Foo>;
```

Process with:

```
../preinst-swig -csharp -c++ test.i
find . -name FooVector.cs
```

**Comment by ojwb** [comment]
Seems to be closely related to #2427.

**Comment by ojwb** [comment]
@wsfulton I'd really like to find a solution for this - I'm happy to try to work on a patch, but I don't even have a clear idea of how this ought to be solved which makes it hard to do anything.

You said in #2427 "perhaps not too hard to implement if based on something like %rename", but I'm not clear what this should actually look like in the interface file.  Did you literally mean a use of `%rename` or just something using the same or similar machinery?  Can you show an example of what the solution might look like.

I wondered about allowing a namespace on the identifier created by`%template` which seems fairly natural (unless the name in the parentheses in `%template` is considered to be a target language name):

```
%module x
%include std_vector.i
%nspace;
namespace My { struct Foo {}; }
%template("My::FooVector") std::vector<My::Foo>;
```

**Comment by wsfulton** [comment]
Hi @ojwb, I'll take a good look at this after I have finished up a couple of things. One is raising a decent bug report for a syntax error parsing template expressions which I would like to see fixed and is more your area. Maybe I can trade you that bug for solving this %nspace for template :) Details to follow...

**Comment by ojwb** [comment]
Sounds good, unless it involves `<` and `>` operators...

**Comment by ojwb** [comment]
@wfulton Did you get a chance to have a better look at this?  Or to write up that other bug?

**Comment by wsfulton** [comment]
I am sorry, no real focus on this yet, I wanted to get some SWIG code reviews first out of the way first, but those are dragging on. Also, alas will also not be around for a couple of weeks, so am only likely to comment again at the beginning of May.

**Comment by wsfulton** [comment]
Consider a simpler non-templated case, which would also apply when using `%template`:
```swig
%nspace A::B::C;
namespace A {
  namespace B {
    class C {};
  }
}
```
Currently, this places C into a target language 'namespace' A.B.

Maybe we could add:
```swig
%rename("BB") A::B;
```
to rename namespaces. This would attach to the namespace node in the parse tree and ultimately would place C into target language namespace A.BB.  All symbols in A::B parsed after this would then move into this new target language namespace.

However, this only allows namespaces to be renamed and not collapsed or expanded, so C would be confined to being in a namespace that was always two deep. It couldn't for example be in a target language namespace that was one deep such as, XXX nor three deep such as, XXX.YYY.ZZZ.

A more workable and powerful approach would instead be to add a feature that provides the target language namespace.  This would attach to the specified symbol node in the parse tree (class node in this case), not the C++ namespace node.  For example:
```swig
%newnspace(XXX) A::B::C; // puts C in target language namespace XXX
%newnspace(XXX::YYY) A::B::C; // puts C in target language namespace XXX.YYY
%newnspace(XXX::YYY::ZZZ) A::B::C; // puts C in target language namespace XXX.YYY.ZZZ
```
Using C++ syntax with a double colon is intentional for the new nspace name as each target language currently converts the C++ namespace separators into something appropriate for the target language. The languages that have implemented this happen to all be dot separated atm, but a new target language implementation may use something else. I'm not sure `newnspace` is a good name, so please make better suggestions.

Currently we have:
```swig
Lib/swig.swg:#define %nspace      %feature("nspace") // same as: %feature("nspace", "1")
Lib/swig.swg:#define %nonspace    %feature("nspace","0")
Lib/swig.swg:#define %clearnspace %feature("nspace","")
```
We could provide:
```c++
#define %newnspace(NAME) %feature("nspace", #NAME)
```
and then the nspace feature becomes a flag or an attribute and might make the implementation a bit easier.  If the flag version is used, then the name is automatically calculated as it is now from the C++ namespaces, so is backwards compatible, assuming users have only set it as documented to one of "1", "0" or "" as per the %nspace macro. I've just been looking at the code and I think this could be quite easy to implement. I'll have a go at implementing it, but will probably only be on Wed.

**Comment by ojwb** [comment]
Limiting to the same depth of namespaces would solve the two reported cases, but does seem arbitrary and unhelpful more generally, so the second approach seems better.

> I'm not sure newnspace is a good name, so please make better suggestions.

Perhaps `%renamenspace`?

Or maybe just make `%feature("nspace", "XXX::YYY::ZZZ") A::B::C;` the defined interface?

**Comment by wsfulton** [comment]
I've got something that seems to work and wasn't too hard to implement. It includes renaming, collapsing and expanding the namespace. I've decided to call it `%renamemove` as a simple description for the feature as is it allows the targetted symbol to be moved to a different target language namespace. Next I will need to do lots more testing before committing next week.

**Comment by ojwb** [comment]
I don't want to get into bikeshedding too much, but seeing `%renamemove` my initial thought is that it's going to be something related to C++ move semantics.

**Comment by wsfulton** [comment]
Oh dear, I must have had a mental aberration, that's definitely not what I meant to write. I had decided on `%nspacemove` and have adjusted the original posting. Hopefully that makes more sense, but improved names are welcome. Move might be an overloaded term, but the idea is to move the symbol to a new namespace and that is what the two combined words are indicating.

**Comment by ojwb** [comment]
`%nspacemove` seems OK to me (certainly much better than `%renamemove`!)  The C++11 meaning of move doesn't seem so liable to mislead.

**Comment by wsfulton** [comment]
The `nspace` feature has now been extend to support `%nspacemove`. See the commits leading up to the merge commit a3682dd3e529318b07982095a1b5c243fcb544ef. Please see the updated docs in the SWIGPlus.html file, view latest master version online: [The nspace feature for namespaces](https://htmlpreview.github.io/?https://github.com/swig/swig/blob/master/Doc/Manual/SWIGPlus.html#SWIGPlus_nspace).

Javascript has implemented nspace in a non-standard way and still has a bit of work to do.

**Comment by wsfulton** [comment]
> Maybe I can trade you that bug for solving this %nspace for template :) Details to follow...

@ojwb, #2919 if you have some time.
