### ISSUE TITLE
Assertion failed: (!SwigType_isvariadic(s)), function Swig_cparse_template_expand in v4.2.0

### ISSUE THREAD

**Issue by iurii-provizio** [swig/swig#2794]
Dear SWIG team,

Macos Brew recently updated its SWIG version to 4.2.0, and our Github CI jobs started failing with the following error:

`Assertion failed: (!SwigType_isvariadic(s)), function Swig_cparse_template_expand, file templ.c, line 582.` on swig compiling for Python of this file: https://github.com/eProsima/Fast-DDS-python/blob/v1.2.1/fastdds_python/src/swig/fastdds.i.

It was all fine with 4.1.1.

**Comment by wsfulton** [comment]
This will be due to the improved variadic templates and parameter packs. I will need to replicate this assertion in order to see the code that is causing it. fastdds seems to use colcon for building, which isn't something I plan to figure out. Can you please provide the complete swig command line that uses fastdds.i as input and I can then run that after cloning the repo.

**Comment by wsfulton** [comment]
I've managed to replicate this. It's this variadic template within an instantiated template: 

https://github.com/eProsima/Fast-DDS/blob/6b484da8f70d16ce4b8537c9faeeb14a3c70685b/include/fastrtps/utils/collections/ResourceLimitedVector.hpp#L216-L218
