### ISSUE TITLE
Syntax error when using explicit + constexpr

### ISSUE THREAD

**Issue by ptomulik** [swig/swig#284]
I try to compile this simple snippet:

```swig
%module test
%inline {
  struct T1 { 
    int _x;
    explicit constexpr T1(int x) noexcept // line 5
      : _x(x)
    { };
  };
}
```

but swig is unable to parse it:

```shell
ptomulik@barakus:$ swig -c++ -python -o test_wrap.cxx test.i
test.i:5: Error: Syntax error in input(3).
```

The above class compiles well with gcc.

**Comment by wsfulton** [comment]
Can you also add in support for 'constexpr explicit'. It should just be:
```cpp
 | CONSTEXPR EXPLICIT { $$ = "explicit constexpr"; }
```
note "explicit constexpr" and not the other way round "constexpr explicit" for consistent ordering

**Comment by ojwb** [comment]
There are a number of other cases which aren't currently handled, notably we handle `static constexpr` but not `constexpr static`.

The approach of adding every valid combination of qualifiers explicitly isn't going to work out well due to the combinatorial explosion.  I think the parsing of strorage classes here needs to be smarter - e.g. parse an arbitrary list of storage classes, with checks for invalid combinations.

I've fixed the case you requested and also the `constexpr static` one in bfa570e and I'm going to close this ticket as the reported issue has been addressed.  Further cases we currently fail to handle are best handled as a separate ticket - I've opened #302 for that.
