### ISSUE TITLE
Installation fails with "cannot stat ‘./ccache-swig.1’: No such file or directory" if yodl2man isn't available

### ISSUE THREAD

**Issue by michael-schaller** [swig/swig#286]
If the yodl2man binary is not available the SWIG installation fails with the unexpected error "cannot stat ‘./ccache-swig.1’: No such file or directory". IMHO the SWIG installation should already fail earlier and with a better error if yodl2man is not available.

Relevant bits from the SWIG installation log:
```
make[1]: Entering directory `.../CCache'
yodl2man -o ./ccache-swig.1 ./ccache.yo
make[1]: yodl2man: Command not found
make[1]: [ccache-swig.1] Error 127 (ignored)
Installing ccache-swig
Installing /usr/local/bin/ccache-swig
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -m 755 ccache-swig /usr/local/bin/`echo ccache-swig | sed 's,x,x,'`
Installing /usr/local/share/man/man1/ccache-swig.1
/usr/bin/install -c -d /usr/local/share/man/man1
/usr/bin/install -c -m 644 ./ccache-swig.1 /usr/local/share/man/man1/`echo ccache-swig | sed 's,x,x,'`.1
/usr/bin/install: cannot stat ‘./ccache-swig.1’: No such file or directory
make[1]: *** [install] Error 1
make[1]: Leaving directory `.../CCache'
```

**Comment by xantares** [comment]
definetely a bug ; configure should fail if ccache is enabled and yodl not found.

proper detection is made in configure.ac
```
AC_CHECK_PROGS(YODL2MAN, yodl2man)
if test -n "$YODL2MAN"; then
  AC_MSG_CHECKING([yodl2man version >= 2.02])
...
```

but hardwired in CCache/Makefile.in:
```
$(srcdir)/$(PACKAGE_NAME).1: $(srcdir)/ccache.yo
	-yodl2man -o $(srcdir)/$(PACKAGE_NAME).1 $(srcdir)/ccache.yo
```

**Comment by wsfulton** [comment]
I'm afraid that failing during configure is wrong as a normal build and install works for users when using the distributed tarball. yodl is not needed when building from the distributed tarball. This is the most important use case and as pointed out, if you want to build from git, then you need to install the prerequisites mentioned. This is standard practice for building unix packages.

When configure is run, it looks for yodl and you can see this in the output demarcated by blank lines:

```
Checking packages required for SWIG developers.
Note : None of the following packages are required for users to compile and install SWIG from the distributed tarball

checking for bison... bison -y
checking for ranlib... ranlib
checking for ar... ar
checking for yodl2man... yodl2man
checking for yodl2html... yodl2html
checking yodl2man version >= 2.02... yes
checking yodl2html version >= 2.02... yes
```

What I would like to see is a removal on the dependency on yodl altogether.

**Comment by wsfulton** [comment]
Reopened for discussion.

**Comment by michael-schaller** [comment]
Maybe the discussion went into the wrong direction the last time.  So let me be clear that I'm absolutely fine with yodl2man being optional during config.
IMHO if yodl2man is optional during config then it also should be optional during build and installation.  If yodl2man is mandatory then config should already fail if it isn't installed.

If yodl2man is optional and not installed how about creating a minimalistic 'ccache-swig.1' that mentions that yodl2man wasn't available during config/build?

**Comment by wsfulton** [comment]
There is a big difference between a developer building from git and a user building from the distribution tarball. In order to build from tarball you absolutely need some package as shown in configure:

```
Checking packages required for SWIG developers.
Note : None of the following packages are required for users to compile and install SWIG from the distributed tarball

checking for bison... bison -y
checking for ranlib... ranlib
checking for ar... ar
checking for yodl2man... yodl2man
checking for yodl2html... yodl2html
```

All of these are needed to build from git. Any logic for not requiring yodl must also apply to bison. You probably have bison installed so you didn't notice, but without bison you cannot get even close to building the code. Neither of these tools are at all optional in any way to build and install everything from git, but they are not required for builiding from the tarball. This is entirely normal and common for unix packages that the developer (git) builds require additional package for it to work.

We can't fail config if ether yodl or bison is not installed as that is completely unhelpfull for the most important use case... a user building from the tarball. I certainly have had trouble building a lot of unix packages from source (developer builds) because it isn't very clear what is always missing. However, I think the errors that SWIG give are a lot better than what is the norm. If there are other unix packages that deal with this problem better than we do, please point them out. 

I still think the best solution is to remove the dependency on yodl and is what I'd like to see done.

**Comment by Kagetsuki** [comment]
Just hit this but I agree with @wsfulton . I don't think configure should have to look at this and I think failing in this way is logical... BUT it would be nice to have a flag to not include document generation (I'm in the middle of doing a dynamic SWIG build for deploying a binary to a container-like architecture so there's no need to have man pages or documentation). I wouldn't say it's necessary and I don't think it's worth the effort to implement.

I'm thinking maybe this issue should be closed.

**Comment by wsfulton** [comment]
They havn't been fed back to the original ccache project. When I modified ccache for SWIG support the maintenance of ccache had stopped and was being maintained in an ad-hoc manner by the individual linux distros with heaps of individual patches. Since then has come back to life and a huge amount of development was done for ccache 3 and the code base is now quite different making a simple merge rather hard. It would be good to get this SWIG supported in to ccache, but would require quite a bit of work and I don't have the time to do this atm.

**Comment by Kagetsuki** [comment]
@wsfulton Rock ![sign_of_the_horns](https://raw.githubusercontent.com/emojidex/emojidex-rasters/master/emoji/utf/hdpi/sign_of_the_horns.png)

**Comment by michael-schaller** [comment]
@wsfulton Thanks!
