### ISSUE TITLE
error: use of undeclared identifier 'SWIGTYPE_p_unsigned_long

### ISSUE THREAD

**Issue by junjieqi** [swig/swig#2864]
We have used Swig in Faiss library to provide python interface with C++ implementation. However, we recently found an issue when we compile library and it errors out `error: use of undeclared identifier 'SWIGTYPE_p_unsigned_long'`

Here is the log information

https://app.circleci.com/pipelines/github/facebookresearch/faiss/5713/workflows/a74c44a3-e2a4-41c7-b3f0-fb6a856b490f/jobs/32825

Here is the code

https://github.com/facebookresearch/faiss/blob/main/faiss/python/swigfaiss.swig#L1025-L1036

Any help will be appreciated!

**Comment by wsfulton** [comment]
`unsigned long*` or a typedef to such a type needs to be used in your code in order to hard code `SWIGTYPE_p_unsigned_long` like this. You can force usage via:
```swig
%types(unsigned long*);
```
However, I think there might be something wrong in your build system as it looks like it fails only on Mac. It might be related to the typedefs to unsigned long in stdint.i and the definition of SWIGWORDSIZE64 in https://github.com/facebookresearch/faiss/blob/main/faiss/python/CMakeLists.txt#L27-L30.

**Comment by junjieqi** [comment]
@wsfulton thanks for replying! I think we have to force generate _long and _unsigned_long. That flag should not work anymore. We could remove it. I had a different issue now which may relate how swig generate the interface. I will continue looking into that part https://app.circleci.com/pipelines/github/facebookresearch/faiss/5759/workflows/4018e391-2a82-449b-9fa3-00f2a538ec65/jobs/33176/parallel-runs/0/steps/0-104
