### ISSUE TITLE
Organizing SWIG-Generated Java Classes into Different Packages from a Single Interface File

### ISSUE THREAD

**Issue by datNurd** [swig/swig#2904]
I'm currently exploring SWIG to facilitate wrapping around three C++ header files (file1.h, file2.h, file3.h). I've included these header files in my SWIG interface file using the `%include` directive.

```
%include "file1.h"
%include "file2.h"
%include "file3.h"
```

Now, I want to organize the generated Java classes into different packages, with each package corresponding to one of the header files (file1.h, file2.h, file3.h). I tried using the %module directive along with the package option to achieve this:

```
%module(package = "a.b.f1") f1_wrap
%include "file1.h"

%module(package = "a.b.f2") f2_wrap
%include "file2.h"

%module(package = "a.b.f3") f3_wrap
%include "file3.h"
```

However, this approach didn't seem to work as expected. The generated Java files didn't include the desired package declaration `(package "a.b.fxx")`.

_jniclasspackage_- This only packages intermediary JNI call into a package but does not package the Java proxy classes generated by SWIG. We would like to include the proxy classes into the package as well which -package argument does.

I've found that using the -package command-line argument with SWIG works, but it requires splitting the code into three separate SWIG interface files (.i files), which isn't great for my project's organization.

Is there a way to achieve the desired package organization within a single SWIG interface file (.i file)? Is there an equivalent directive or option within SWIG that allows specifying package names directly within the interface file?

**Comment by ojwb** [comment]
Multiple `%module` directives in one run don't define multiple modules - IIRC the second and subsequent `%module` directives are ignored except that any parameters are used.

You can use `%nspace` to map a C++ namespace to a Java package which would work if  `file1.h`, `file2.h`, etc were each in its own C++ namespace.

Otherwise you probably do need to use separate interface files, which seems a fairly natural organisation as it mirrors your 3 separate C++ headers.  Note you can share common typemaps, etc by putting them in their own file and `%include`ing it from the interface file for each package..
