### ISSUE TITLE
C++ preprocessor does not understand keyword logical operators

### ISSUE THREAD

**Issue by torokati44** [swig/swig#2914]
See for example:

```cpp
// swigtest.cpp
#define AA
#define BB

#if defined AA and defined BB // changing the `and` to `&&` fixes it
void foobar() { }
#endif
```

```
$ swig -java -module swigtest swigtest.cpp
swigtest.cpp:4: Warning 202: Could not evaluate expression 'defined AA and defined BB'
swigtest.cpp:4: Warning 202: Syntax error: expected operator
```

Up to SWIG 4.1 this went unnoticed.
SWIG 4.2 now errors out on expressions like this.

Note that compiling this piece of code does work as intended:

```
$ clang++ swigtest.cpp -shared -fPIC -o swigtest.o`
$ objdump -t swigtest.o | grep foobar
0000000000001100 g     F .text  0000000000000006              _Z6foobarv
```

**Comment by ojwb** [comment]
> Up to SWIG 4.1 this went unnoticed.

It didn't directly result in an error, but the expression still wouldn't be correctly evaluated and would just be treated as false, so in your example SWIG wouldn't see `foobar` so it wouldn't get wrapped.  Quietly doing the wrong thing seems much worse (which is why we changed to enable these errors by default).  You can restore the previous behaviour with command line option `-w202` or with `%warnfilter(SWIGWARN_PP_EVALUATION);` in your interface file.

The list of alternative operator names we should recognise here is at: https://en.cppreference.com/w/cpp/language/operator_alternative

They're currently handled in `cscanner.c` but I think they should be handled in `scanner.c` (which is what preprocessor expressions get scanned by).  It also looks like we fail to support most of these alternative tokens even in expressions in C++ code - only `and`, `or`, and `not` seem to be handled currently (I didn't test yet, but they only those three alternative operator names are in the list handled in `cscanner.c`).

As a workaround, you can define macros for these operators for SWIG, e.g. in your interface file:

```
#define and &&

%include "headertowrap.h"
```

(That's actually how these alternative names are implemented in C in the compiler-provided header `iso646.h`.)

**Comment by ojwb** [comment]
> They're currently handled in `cscanner.c` but I think they should be handled in `scanner.c` (which is what preprocessor expressions get scanned by).

I've made this change, which is all that was needed to fix this.

> It also looks like we fail to support most of these alternative tokens even in expressions in C++ code - only `and`, `or`, and `not` seem to be handled currently (I didn't test yet, but only those three alternative operator names are in the list handled in `cscanner.c`).

They indeed weren't handled in expressions, but are now thanks to the same change.

**Comment by torokati44** [comment]
> Quietly doing the wrong thing seems much worse (which is why we changed to enable these errors by default).

I agree.

> I've made this change, which is all that was needed to fix this.
> They indeed weren't handled in expressions, but are now thanks to the same change.

Awesome, thank you so much for the super quick fix!
