### ISSUE TITLE
SWIG (C++ to Java) problem with including same headers from different modules

### ISSUE THREAD

**Issue by AnDevi** [swig/swig#2971]
I got example header `Shape.h` with 2 enums like:

```
enum ShapeType {
    ShapeTypeRect,
    ShapeTypeCirle,
    ShapeTypeDefault,
};

enum ShapeStyle {
    ShapeStyleSolid,
    ShapeStyleDashed,
    ShapeStyleDefault,
};
```

And class which uses those enums:
```
class A {
ShapeType getShapeTyoe() const;
ShapeStyle getShapeStyle() const;
};
```

I wont to create separate modules to make wrappers for whose enums:
First:
```%module Module_ShapeStyle

%inline %{
#include <Shape.h>
%}

%rename("Solid") ShapeStyleSolid;
%rename("Dashed") ShapeStyleDashed;
%rename("Default") ShapeStyleDefault;

%include <Shape.h>
```
second: 
```%module Module_ShapeType

%inline %{
#include <Shape.h>
%}

%rename("Rect") ShapeTypeRect;
%rename("Circle") ShapeTypeCircle;
%rename("Default") ShapeTypeRect;

%include <Shape.h>
```

And in the end module for wrapping A class

which import modules with enum:
```%module Module_AClass

%import "Module_ShapeType.i"
%import "Module_ShapeStyle.i"

%inline %{
#include <A.h>
%}

%include <A.h>
```

The problem is that I got created Java classes for `ShapeType` and `ShapeStyle` enums, but Java methods of class `A` look like this:
```
public ShapeType getShapeTyoe()
public SWIGTYPE_ShapeStyle getShapeStyle()
```
despite import I added. 
If I change the order of imports:
```
%import "Module_ShapeStyle.i"
%import "Module_ShapeType.i"
```
Methods in class A look like this:

```
public SWIG_TYPE_ShapeType getShapeType()
public ShapeStyle getShapeStyle()
```

If I move second enum to separate files it works fine, but the problem is that I got a lot of places in code with many enums in one header and it needs to stay like this. 

Is there a way to fix this ? 

I also tried to use one module for enums, but there is another problem with renaming:

```
%rename("Rect") ShapeTypeRect;
%rename("Circle") ShapeTypeCircle;
%rename("Default") ShapeTypeRect;

%rename("Solid") ShapeStyleSolid;
%rename("Dashed") ShapeStyleDashed;
%rename("Default") ShapeStyleDefault;
```

I can't use rename to the same value of `Default` in single module, cuz generated Java class for one of enums misses a `Default` field.

I'd like to use enum from Java/Kotlin in a way like `ShapeStyle.Default` `ShapeType.Default` instead of `ShapeStyle.ShapeStyleDefault` and `ShapeType.ShapeTypeDefault` that way I also want to uses these renames. 

Is it possible to achieve what I described using separates modules, but I done something wrong ? 
Or can I use some trick with rename using single module ?

**Comment by wsfulton** [comment]
When using just one module, I see:
```
make -s clean check 
Shape.h:10: Warning 302: Redefinition of identifier 'Default' (Renamed from 'ShapeStyleDefault') ignored,
Shape.h:2: Warning 302: previous definition of 'Default' (Renamed from 'ShapeTypeRect').
```
which is arguably a bug in SWIG as the Default is unique within each of the Java wrapper enums. Is this the main reason that you are considering two modules, or is there some other reason?

I think the problem in your two module approach boils down to wrappring the two enums twice via `%include <Shape.h>` in creating your two modules. Trying to split one header file into multiple modules feel like it'll have a few problems and not something I've ever seen been tackled before.

One suggestion that works is to switch to enum classes instead of C style enums. That works.

**Comment by AnDevi** [comment]
Yeah, this ignoring of `Default` and others, which are unique for each of Java wrapper enums is main reason I started to try with two or more modules.
I forgot to tell that in each module I ignore everything `%ignore ""; ` and accordingly uncommenting it with `%rename` I mean, `ShapeType` is unignored in one module and `"ShapeStyle` in another. 
I thought that it will be fix/workaround for wrappring the two enums twice via `%include <Shape.h>`, but it's not. 

Changing it to `enum class` isn't also a fix for me, C style enums are used across my whole repo for multiplatform usage, in some cases C style enumes are the only way ;(

**Comment by wsfulton** [comment]
SWIG's symbol naming is based on C and C++'s. You cannot have a C style enum value with the same name in two different enums in the same scope. While Java's enums are scoped like a C++ enum class is, SWIG enforces the C symbol name scoping for C style enums, even after a %rename, because it is deeply rooted in C/C++ scoping. I can't really see how this can easily be changed for this one case. 

Another option you can consider is putting the C style enums into a differently named C++ namespaces and use the `%nspace` feature to scope the enums into another Java package.

Finally I found a pretty spectacular hack as an alternative. Just let SWIG think that the C style enums are actually C++ enum classes using:
```swig
#define enum enum class
%include <Shape.h>
#undef enum
```
There is no generated C++ code for handling the enum items and all the generated code is the same whether it is C style enums or C++ enum classes. However, if you use a default value for your enum items, then the value is assigned in C++ code, eg changing to:
```swig
    ShapeTypeDefault = 1234,
```
then the generated code contains:
```c++
  ShapeType result;
  ...
  result = (ShapeType)ShapeType::ShapeTypeDefault;
```
Interestingly `ShapeType::ShapeTypeDefault` is valid to use on a C style enum in C++11 onwards (not for C nor for earlier C++ standards). So the code will compile with C++11 and later standards. Enum values would only be a problem when explicit values are obtained from C++, but this can also be circumvented if needed by setting the value in Java with the `%javaconstvalue` feature.

You can get the same effect as the hack by instead defining the enum as an enum class in the interface file for SWIG to parse, then `%ignore` the actual C style enum in the Shape.h header:
```swig
enum class ShapeType {
    ShapeTypeRect,
    ShapeTypeCircle,
    ShapeTypeDefault,
};
%ignore ShapeType;
%include <Shape.h>
```

**Comment by AnDevi** [comment]
Cool, redefining it as `enum class` works perfectly of me, thanks!

**Comment by wsfulton** [comment]
Closing as I don't see how SWIG can implement anything better as it is fundamentally tied to C/C++ scoping.
