### ISSUE TITLE
Modifying/deleting wrap code

### ISSUE THREAD

**Issue by supsm** [swig/swig#2982]
I was wondering if it is possible to modify or remove portions of the swig wrapper code (xxx_wrap.cxx for c++ to java). Some issues I have come across with are infeasible to fix for swig code generation and cumbersome to edit manually:
- members whose type is non-copyable receive a generated setter which fails to compile
- types that require disambiguation through `struct` due to conflicts with similarly named functions

It would be helpful if there was some way to clear entire functions or have some find-and-replace (possibly through regex like %rename and %ignore) functionality for the wrapper code specifically. I couldn't find anything in the documentation, but that is quite lengthy and it is very possible I may have missed something.

**Comment by wsfulton** [comment]
Use `%ignore` to prevent code from being wrapped. Read the rules for this feature and it does include regex support.
use `%immutable` to prevent a setter from being generated.

> members whose type is non-copyable receive a generated setter which fails to compile

You may not have provided SWIG with the full type information for it to see this, perhaps you are missing a %template. Please raise a separate issue with a cut down testcase to replicate otherwise. A type should be immutable if it is not non-assignable (not non-copyable) and SWIG should detect this scenario, but you can use %immutable as a workaround.

**Comment by supsm** [comment]
It does seem that swig normally detects this scenario. I could not reproduce the issue on a smaller scale, but %immutable seems to work great as a workaround. Thanks!
