### ISSUE TITLE
Change of behavior in Python for wrapped `operator==` between SWIG 4.1 and 4.2

### ISSUE THREAD

**Issue by lballabio** [swig/swig#2987]
Minimal interface file to reproduce the issue:

```
%module foo

%inline %{
class C {
    int i;
  public:
    C(int i): i(i) {}
    bool operator==(const C& other) const {
        return i == other.i;
    }
    bool operator!=(const C& other) const {
        return i != other.i;
    }
};
%}
```

Both SWIG 4.1.1 and 4.2.1 generate an `__eq__` method that wraps `operator==` and works correctly when comparing two instances of the class:

```
>>> import foo
>>> foo.C(2) == foo.C(2)
True
>>> foo.C(2) == foo.C(3)
False
```

However, the wrappers generated with SWIG 4.1.1 are more permissive, and allow comparing an instance of C also with other objects, the same way the default Python comparison works, including `None`:

```
>>> foo.C(2) == None
False
>>> foo.C(2) == "abc"
False
```

Instead, the wrappers generated with SWIG 4.2.1 allow comparing with other objects, but not with `None`:

```
>>> foo.C(2) == "abc"
False
>>> foo.C(2) == 3
False
>>> foo.C(2) == None
Traceback [...]
ValueError: invalid null reference in method 'C___eq__', argument 2 of type 'C const &'
```

(the idiomatic `foo.C(2) is None` works as expected.)

Was this intended? Thanks!

**Comment by ojwb** [comment]
While `is None` is idiomatic, a pure Python class seems to support `== None` and given we used to this seems like a bug to me.

`git bisect` says this change was caused by d701f0b4b277976e882277c060cb8a4beb6f9123 from @wsfulton.

**Comment by wsfulton** [comment]
Hi @lballabio. The original issue that the commit addressed is #1783. The change converts all TypeError exceptions into a NotImplemented exception. Python documentation on these two exceptions [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError) and [NotImplemented](https://docs.python.org/3/library/constants.html#NotImplemented). 

Of interest is the TypeError and I quote the relevant/interesting snippets below:

> Raised when an operation or function is applied to an object of inappropriate type. 
> ...
> Passing arguments of the wrong type (e.g. passing a [list](https://docs.python.org/3/library/stdtypes.html#list) when an [int](https://docs.python.org/3/library/functions.html#int) is expected) should result in a [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError), but passing arguments with the wrong value (e.g. a number outside expected boundaries) should result in a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError).

Now then, SWIG currently raises a ValueError when `None` is passed and this is done more generally by the SWIG Python wrappers. Is this correct or should TypeError be raised instead? I'm not really sure as `None` could be interpreted as the wrong value (null C++ pointer instead of an instance) or it could be interpreted as the wrong type; type `None` instead of type `C`. Thoughts anyone?

I bring this up as the solution is either:

1. Change the typemaps (reference types and pass by value types) to raise a TypeError instead of ValueError. If this was done, the TypeError would correctly be converted into a NotImplemented error when wrapping `operator==` and this bug would be solved.

2. Convert ValueError into NotImplemented to fix this bug. However, this would convert all ValueErrors into NotImplemented. I'm not sure all ValueErrors should be converted into NotImplemented when wrapping `operator ==`, but would err on the side of probably they should. For example, when a more traditional ValueError is thrown to handle out of range values. Thoughts?

Anyway, workaround until fixed is quite simple, using the actual typemap being used:
```swig
%typemap(in,noblock=1,implicitconv=1) const SWIGTYPE & (void *argp = 0, int res = 0) {
  res = SWIG_ConvertPtr($input, &argp, $descriptor,  0  | $implicitconv);
  if (!SWIG_IsOK(res)) {
    SWIG_exception_fail(SWIG_ArgError(res), "in method '" "$symname" "', argument " "$argnum"" of type '" "$type""'"); 
  }
  if (!argp) { SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "$symname" "', argument " "$argnum"" of type '" "$type""'"); }
  $1 = reinterpret_cast< $ltype >(argp);
}
```
tweak slightly and target just the `const C& other` parameter, changing `SWIG_ValueError` into `SWIG_TypeError`:
```swig
%typemap(in,noblock=1,implicitconv=1) const C& other (void *argp = 0, int res = 0) {
  res = SWIG_ConvertPtr($input, &argp, $descriptor,  0  | $implicitconv);
  if (!SWIG_IsOK(res)) {
    SWIG_exception_fail(SWIG_ArgError(res), "in method '" "$symname" "', argument " "$argnum"" of type '" "$type""'"); 
  }
  if (!argp) { SWIG_exception_fail(/*SWIG_ValueError*/SWIG_TypeError, "invalid null reference " "in method '" "$symname" "', argument " "$argnum"" of type '" "$type""'"); }
  $1 = reinterpret_cast< $ltype >(argp);
}
```

**Comment by lballabio** [comment]
Hmm, I see.  Having myself one or two `operator==` that can throw (*), I'd be for throwing `TypeError` just for `None` and letting the other exceptions alone, so solution 1.  But I think it also makes sense in general to consider `None` as the wrong type, i.e., not an instance of `C`.

(*) For info, in my case the exceptions mean "can't compare" in case of a partially ordered domain.  Both values would be in range, but comparison is undecided.

**Comment by ojwb** [comment]
> But I think it also makes sense in general to consider `None` as the wrong type, i.e., not an instance of `C`.

Python already made a call on this point though - an object of a pure Python class supports `obj == None` so it seems surprising and unhelpful if an object of a SWIG-wrapped class doesn't too.

**Comment by lballabio** [comment]
Oh, yes, I'm for having `obj == None` work.  If I understand William's comment, throwing a TypeError from the typemap would have this effect.  I was trying to say that besides working, TypeError also makes sense.

**Comment by ojwb** [comment]
Ah right, yes I agree with that.  Indeed `None` in Python has its own type:

```
>>> type(None)
<class 'NoneType'>
```

**Comment by wsfulton** [comment]
Given the comments and especially given Python thinks `None` is its own type, I'm going to make changes to raise a TypeError instead of a ValueError when `None` is attempted to be used for a C++ reference.

**Comment by ojwb** [comment]
At least for PHP, this change better aligns with native behaviour where passing PHP `NULL` to a function which doesn't accept it raises `TypeError`:

```
$ php -r 'function f(int $x) {} f(NULL);'
PHP Fatal error:  Uncaught TypeError: f(): Argument #1 ($x) must be of type int, null given, called in Command line code on line 1 and defined in Command line code:1
Stack trace:
#0 Command line code(1): f()
#1 {main}
  thrown in Command line code on line 1
```

I'll adjust the CHANGES entry to use the PHP type names rather than the C API symbols for them which few PHP users will know.
