### ISSUE TITLE
Memory problems on Windows using `swig v4.2.1`

### ISSUE THREAD

**Issue by ralfkonrad** [swig/swig#3023]
I am trying to extend an already big python swig export, see [here](https://github.com/OpenSourceRisk/ORE-SWIG). The resulting python file has `~40,000` and the cpp file `~1,000,000` lines of code.

However, when I run the swig export extended by more classes it fails with the following message:
```
Failed to allocate 4194304*16 bytes
```

If I comment out dependent parts of the wrapper, the builds works fine without crashing. Also, the same works fine on the same machine, using `ubuntu-24-04` via `wsl`. So, it does not look like a syntax error in my code.

Am I hitting a memory boundary here on windows? Looking at the task manager is happens around `2G` of memory used by the swig process.

And if so: is there any way to circumvent it?

**Comment by ojwb** [comment]
The error means a call to `calloc(4194304, 16)` failed.  There aren't many places in swig which allocate memory using `calloc()`.  It's not a hash table trying to grow, because those always use a prime size, and it's not a list as those use a power of two size.  Also both of those allocate pointers so the second argument will be 4 or 8 bytes not 16.  It's also not going to be the place that allocates a flag array for command line processing because the second argument there is `sizeof(int)`.

That means it must be trying to allocate a new memory pool, and the default size matches:

```
#define DOH_POOL_SIZE         4194304
```

The pool code always uses a fixed size but seems to support a variable size so we could potentially retry with a smaller size if we can't allocate 4194304, but I think that will just push the point of failure a little further out (4194304*16 is ~64M).

> Am I hitting a memory boundary here on windows? Looking at the task manager is happens around 2G of memory used by the swig process.

From that I suspect you're using a 32-bit build, whereas the Linux build is probably 64-bit.

> And if so: is there any way to circumvent it?

I'd try a 64-bit build.  The platform's C library's malloc implementation will have an effect on when you run out (especially the overheads and how it reuses freed space) but the 2G threshold process size seems a smoking gun that this isn't a platform difference of that sort.

If that doesn't help, or you're wanting to help actually reduce the memory usage, SWIG isn't always great at releasing memory it is done with so running some sort of malloc heap profiler or leak checker to identify the worst offenders and add missing calls to `Delete()` or `Free()` might help significantly.

I have been working on a patch implementing SSO (short string optimisation) for SWIG's `String` which should reduce memory usage quite a lot too.  This should save a memory allocation per string <= 12 bytes (64-bit) or <= 8 bytes (32-bit) and SWIG creates a huge number of very short `String` objects.

**Comment by ralfkonrad** [comment]
Thanks @ojwb for the detailed analysis and explanation.

32-bit vs. 64-bit makes perfect sense, the 2GB boundary rings a bell from ancient times.

I'm using the official windows executable download [here](https://www.swig.org/download.html). I guess this is 32-bit then?

Is there a download for the 64-bit Windows version also available? I would like to avoid the burden of building it myself or to be more precise provide and maintain a company wide package for it.

**Comment by ojwb** [comment]
I don't know the details of that download - I think @wsfulton builds it.

**Comment by wsfulton** [comment]
> I guess this is 32-bit then?

Yes. 

Binary release build details for Windows releases of SWIG are mentioned at https://github.com/swig/swig/wiki/Getting-Started#windows. Take your pick for building on Windows from the multitude of methods mentioned there.

I wonder if I should switch these prebuilt versions to 64-bit? From what I can make out Windows 10 was available as a 32-bit OS up and until 2020, so not that long ago. We could just make the switch and anyone still requiring a 32-bit build can build it themselves. Probably a step forward for the majority of Windows users who are using a 64-bit OS.

**Comment by ralfkonrad** [comment]
Thanks Olly and William for the clarification!

> I wonder if I should switch these prebuilt versions to 64-bit?

Yes!? It wouldn't help if I build a 64er for myself. Using it in an open source project we would force everyone to start building its own one.

Also, I doubt it that there still many developers around using a 32-bit Windows. And it doesn't mean that you can't build 32-bit programs from it which are probably still much more important on Windows for legacy reasons than the underlying OS.

**Comment by wsfulton** [comment]
I've made the changes so that the 64-bit instead of 32-bit Windows executables are included in the distributed Windows zip file. Also improved the mkwindows.sh script, so that 32-bit can also be built if you have Linux and wine, see updates notes in https://github.com/swig/swig/wiki/Getting-Started#building-a-full-release.

**Comment by ralfkonrad** [comment]
Thanks William!

I guess this will become effective with the next release. Any rough idea when it will be released?

**Comment by ojwb** [comment]
In about a week probably - you can see milestone dates at https://github.com/swig/swig/milestones though they're not hard commitments.
