### ISSUE TITLE
Lib/swigwarnings.swg:39: Error: Unable to find 'swigwarn.swg'  (Javascript issue)

### ISSUE THREAD

**Issue by Andy-zhujunwen** [swig/swig#3029]
my Swig version is 4.2.1 . When i copy Lib directory in Swig to my local  project, and use it  by export SWIG_LIB=path_to_Lib , when i generate code ,there is a error:  swigwarnings.swg:39: Error: Unable to find 'swigwarn.swg'
i find there is no swigwarnings.swg in Swig , please tell me how to fix this issue?
(i use to generate javascript api)

**Comment by ojwb** [comment]
> i find there is no swigwarnings.swg in Swig

I think you must mean `swigwarn.swg` here?

`swigwarn.swg` is generated during the SWIG build and should be in the `Lib` directory itself.

Does it work if you just use SWIG as installed rather than trying to take a copy of `Lib` and use that by setting `SWIG_LIB`?

(Also, *WHY* do you want to take a copy of `Lib` instead of just using the installed one?)

**Comment by ojwb** [comment]
> When i copy Lib directory in Swig to my local project [...]

I realised what your problem probably is - do you mean you just copied `Lib` from the git repo?  If so that will be missing generated library files (such as the one you report is missing).

You should `make install` first, then if you **REALLY** need to copy, copy from the installed library file directory - but much better to just let SWIG use its own installed library.  If you take a copy you risk it getting out of step with the SWIG binary you're using, and if you don't use corresponding versions you're liable to hit problems which just don't exist if you use a consistent build of SWIG.

**Comment by Andy-zhujunwen** [comment]
> > When i copy Lib directory in Swig to my local project [...]
> 
> I realised what your problem probably is - do you mean you just copied `Lib` from the git repo? If so that will be missing generated library files (such as the one you report is missing).
> 
> You should `make install` first, then if you **REALLY** need to copy, copy from the installed library file directory - but much better to just let SWIG use its own installed library. If you take a copy you risk it getting out of step with the SWIG binary you're using, and if you don't use corresponding versions you're liable to hit problems which just don't exist if you use a consistent build of SWIG.

yes, you are right, thx~
