### ISSUE TITLE
swig error with trailing const reference types

### ISSUE THREAD

**Issue by k-joel** [swig/swig#3031]
Swig `4.2.1` doesn't seem to handle trailing const reference types. The following code works just fine:

```
class Foo
{};

auto getVal() -> Foo;

auto getRef() -> Foo&;

const Foo& getCRef();
```

But when I change the last function to a trailing type like this:

```
auto getCRef() -> const Foo&;
```

I get this error:

```
error : Syntax error in input(1).
```

Is there any workaround for this?

**Comment by ojwb** [comment]
SWIG's C++ grammar is just too restrictive here.  I'll take a look if it's easy to fix (if so it'll probably make it into 4.3.0).  The non-`const` reference case was fixed by 27a3d16ac6e1bf653d30fbf6b1de4f40b9c65691 (#231).

> Is there any workaround for this?

I can't think of a great one.

If you can modify the header being wrapped, rewriting as `const Foo& getCRef();` would work, and is probably the best solution for making this work with current SWIG releases, but if it's a third party header they may be reluctant to make such changes (somewhat understandably really).  You could perhaps run the headers through a suitable regexp replacement filter (e.g. `sed` or whatever tool you prefer) before you feed them to SWIG.

You might be able to `#define const` for SWIG while parsing this header (so SWIG doesn't see the `const`).  Whether that's workable depends on what other uses of `const` there are in the header and whether SWIG ignoring those is problematic.  Rather icky even if it works.
