### ISSUE TITLE
 error: use of deleted function

### ISSUE THREAD

**Issue by siddhsql** [swig/swig#3039]
Hello,

I am new to SWIG. I have following interface file:

```
%module example
%{
#include "example.hpp"
%}

%include "example.hpp"
```

I am able to  generate C++ code using following command:

```
 swig -c++ -java -package mypackage -outdir java_out example.i
```

but when I try to compile I get lots of errors like this:

```
error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = tashkeel::State; _Dp = std::default_delete<tashkeel::State>]’
```

the code at line where it complains is:

```
arg2 = *argp2; 
```

where

```
std::unique_ptr< tashkeel::State > arg2 ;
std::unique_ptr< tashkeel::State > *argp2 ;
```

I have hundreds of these errors. How can I fix them?

**Comment by ojwb** [comment]
That interface file tells us basically nothing - the contents of `example.hpp` is the interesting part.

From the error message I guess you're wanting the new `std::unique_ptr` support, which hasn't been in a release yet but is due to be in the next few days.  See 24a66e6125699499f4c6b7bf15df629e0655f0b7 and other commits from around then.

**Comment by ojwb** [comment]
No feedback so closing.

4.3.0 isn't quite out yet, but there's a release candidate you could try:

https://sourceforge.net/p/swig/mailman/message/58826001/
