### ISSUE TITLE
Reloaded function works wrong when using typemaps

### ISSUE THREAD

**Issue by Notify-ctrl** [swig/swig#3047]
There's a method `C::f(std::string s, int i = 0)` and a SWIG typemap that maps `std::string` to Lua string. However when I call `c:f('str')`, error occured:

```
[string "xpcall(function()..."]:3: Wrong arguments for overloaded function 'C_f'
  Possible C/C++ prototypes are:
    C::f(std::string,int)
    C::f(std::string)
```

My code:
```cpp
// main.h
#include <string>
class C {
public:
  C() {};

  void f(std::string s, int i = 0);
};
```

```cpp
// main.cpp
#include "main.h"
#include <iostream>

extern "C" {
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
int luaopen_main(lua_State *);
}

void C::f(std::string s, int i) {
  std::cout << s << i << std::endl;
}

int main() {
  lua_State *L = luaL_newstate();
  luaL_openlibs(L);
  luaopen_main(L);
  luaL_dostring(L, R"(xpcall(function()
    local c = main.C()
    c:f('str')
  end, print))");
}
```

```swig
// main.i
%module main
class C {
public:
  C();
  void f(std::string s, int i = 0);
};

%{
#include <string>
#include "main.h"
%}

%include <std_string.i>

// Typemap for std::string to Lua
%typemap(in) std::string {
    $1 = std::string($input);
}

%typemap(out) std::string {
    $result = $1.c_str();
}
```

Run with:

```shell
$ g++ main.cpp main_wrap.cxx -o main -llua && ./main 
```

SWIG version: 4.2.1
Lua version: 5.4.7

Here is the code that checks if the argument is the type `std::string`, which generated by SWIG:

```cpp
    if (_v) {
      {
        void *ptr;
        if (lua_isuserdata(L,argv[1])==0 || SWIG_ConvertPtr(L,argv[1], (void **) &ptr, SWIGTYPE_p_std__string, SWIG_POINTER_NO_NULL)) {
          _v = 0;
        } else {
          _v = 1;
```

With the help of typemap, when passing Lua string as the first argument, this check should pass and call `C::f` with the default argument `i = 0`.

**Comment by Notify-ctrl** [comment]
Edit: `c:f('str', 0)` doesn't work as well

**Comment by ojwb** [comment]
SWIG uses the typemaps in effect at the point it sees the function, so the problem is that your interface file is in the wrong order.  As a result SWIG is wrapping `std::string` as an opaque type, and that's why it can't convert a Lua string to it.

`%include <std_string.i>` should be enough - it just needs to be moved to the top.  You shouldn't need to provide custom typemaps for `std::string` (and yours result in code that doesn't compile).  This `main.i` works:

```
// main.i
%module main
%{
#include <string>
#include "main.h"
%}

%include <std_string.i>

class C {
public:
  C();
  void f(std::string s, int i = 0);
};
```

**Comment by ojwb** [comment]
BTW, generally better to use `%include main.h` in your interface file so SWIG parses the actual definitions in the header rather than repeating the contents of your header there.  If you duplicate the two can get out of step if the header changes.  If you're lucky it'll fail to compile, but it may build but misbehave in odd ways.
