### ISSUE TITLE
G++ error on python wrapper compilation for protected default constructor.

### ISSUE THREAD

**Issue by CoreFloDev** [swig/swig#322]
Hello,

I'm currently working with SWIG and I think that I found a bug but maybe it's only a parameter problem.

I write a little example to reproduce the bug.
**A.h**

<pre><code>#include "B.h"

class A {
    public:
        B getB();
};</code></pre>

**A.cpp**

<pre><code>#include "A.h"

B A::getB() {
    return B(1);
}</code></pre>

**B.h**

<pre><code>class B {

public :
    B(int a);

protected:
    B();

};</code></pre>

**B.cpp**

<pre><code>#include "B.h"

B::B(int a) {
}</code></pre>

**swig.i**

<pre><code>%module swig

%{
#include "A.h"
%}

%include "A.h";</code></pre>

**Command used**

<pre><code>swig3.0 -c++ -python -Wall swig.i
g++ -O2 -fPIC -c swig_wrap.cxx -I/usr/include/python2.7</code></pre>

My swig version is  3.0.2 with configured options: +pcre.

You will get this error :

<pre><code>In file included from A.h:1:0,
                 from swig_wrap.cxx:3038:
B.h: In function ‘PyObject* _wrap_A_getB(PyObject*, PyObject*)’:
B.h:8:2: error: ‘B::B()’ is protected
  B();
  ^
swig_wrap.cxx:3049:5: error: within this context
   B result;
     ^
</code></pre>

This error happens because the generated code create a variable B result which call the B default constructor. So is it really a bug or I miss something ?

**Comment by CoreFloDev** [comment]
Do you need more details to reproduce the bug ?

**Comment by ojwb** [comment]
The issue here is because (as documented) SWIG doesn't follow `#include` directives by default, so it doesn't see the definition of `B` and handles it as best it can without specific knowledge.

If you use `-includeall` then SWIG will follow `#include` (this isn't the default as it's problematic for SWIG to follow into system headers, but hard for it to determine what's a system header):

```
swig -includeall -c++ -python -Wall swig.i
```

The other option is to explicitly `%include "B.h"` in swig.i.
