### ISSUE TITLE
Go documentation - Please add a section about thread safety and thread-local storage

### ISSUE THREAD

**Issue by michael-schaller** [swig/swig#374]
As mentioned in issue #289 the SWIG Go documentation should have a section regarding thread safety and thread-local storage. IMHO this information should be documented for cgo and the SWIG Go documentation should only link to it.

FYI: @ianlancetaylor

**Comment by ojwb** [comment]
@ianlancetaylor @michael-schaller Has this information since been documented for cgo somewhere?

**Comment by ianlancetaylor** [comment]
I'm not sure what kind of docs are appropriate or necessary here.  Issues of thread safety (or, for Go, goroutine-safety) are general Go issues, not specific to SWIG or cgo.  For thread-local storage we have https://pkg.go.dev/runtime#LockOSThread, which is also not SWIG or cgo-specific.

**Comment by ojwb** [comment]
You and michael-schaller discussed what to document about this in comment https://github.com/swig/swig/issues/289#issuecomment-89229243 and the comments which follow.

Looks like #414 added a warning to `Go.html` that the finaliser can be called from any OS thread, but it seems from what I've read that issue is more general as a goroutine can actually be running on an arbitrary different OS thread for different calls to C/C++ functions - it's not specific to the finaliser.
