### ISSUE TITLE
Comments in %pythoncode damaged

### ISSUE THREAD

**Issue by notroj** [swig/swig#379]
There's an issue with whitespace handling in the Subversion SWIG bindings which seems to have regressed in SWIG 3.0.  This is one way to reproduce, though I think there is a slightly different issue with %extend which may be related.   Given input:

    %module foo

    %define %bar
    %pythoncode %{
       def one():
          # Comment XXXX
          return 1
    %}
    %enddef

    struct TYPE {
    %bar
    };

The output produced is:

    $ grep -5 XXXX foo.py 
        def one():
        mment XXXX
             return 1

The preprocessor trimmed whitespace before the "#" in the comment, and the %pythoncode whitespace adjustment then butchers that code.  python.cxx:pythoncode() does not check whether the "initial" whitespace for any given line is actually whitespace, instead it just skips characters.

**Comment by ojwb** [comment]
Here's a simpler reproducer:

```
%module foo

struct TYPE {
%pythoncode %{
   def one():
# Comment XXXX
      return 1
%}
};
```

Process with:

```
swig -python test.i
```

**Comment by ojwb** [comment]
Neither your example nor my simpler version have worked for a long time - I checked back as far as 1.3.37 (before that, modern bison won't generate the parser).  So this doesn't appear to be a regression, or at least not one that's happened at all recently.

**Comment by ojwb** [comment]
This patch fixes this, but blindly skipping the first `initial` characters doesn't seem a good idea at all.  It would be good to understand what's removing whitespace before the `#` too.

```
diff --git a/Source/Modules/python.cxx b/Source/Modules/python.cxx
index 0e4a402..b7a2cfc 100644
--- a/Source/Modules/python.cxx
+++ b/Source/Modules/python.cxx
@@ -1408,7 +1408,8 @@ public:
       s = si.item;
       if (Len(s) > initial) {
        char *c = Char(s);
-       c += initial;
+       if (*c != '#')
+         c += initial;
        Printv(out, indent, c, "\n", NIL);
       } else {
        Printv(out, "\n", NIL);
```

**Comment by notroj** [comment]
Thanks!  There is a bunch of code in the CPP which strips whitespace but I didn't work out if that is actually the culprit.

**Comment by wsfulton** [comment]
@notroj as you say this has regressed in SWIG 3.0, are you sure you have posted the right example? Or is it just that it hasn't regressed?

**Comment by notroj** [comment]
@wsfulton Sorry, yes, this wasn't really a regression.  The SVN code uses in this particular case:

%pythoncode {
...
   # Comments.
}

I understand this is now *expected* to break; it is rejected by the CPP with an error.  Changing it to "%pythoncode %{" is the advised fix for such cases, but that then breaks as described here for all versions of SWIG.

I'm also struggling with an issue exactly like issue 377, where a %typemap(default) is used but the Python wrapper code generated doesn't respect that and now fails for cases where the argument is not passed.  The old wrappers which passed *args worked.

**Comment by wsfulton** [comment]
Given the importance of whitespace in Python, I agree that understanding why and when whitespace is stripped out is needed as we have said that we aren't going back to allowing %pythoncode with {} delimiters for Python comments as they clash with preprocessor symbols.

**Comment by wsfulton** [comment]
I've looked at the space removal inside a %define ... %enddef macro. This is handled in 'case 150' in cpp.c where Preprocessor_define() is called. Towards the end of Preprocessor_define(), surrounding whitespace is removed around any '#'. This seems to be normal C preprocessor behaviour, try running
'g++ -E' on:
```
#define JOIN( a, b ) \
    a \
    ##   b

#define STR( s )   \
    \
   #   s

int main () {
    int JOIN(di,ng) = 1;
    cout << STR(ding) << " " << JOIN(di,ng) << endl;
    return 0;
}
```
You'll see the preprocessor just chews up all the surrounding whitespace:
```
int main () {
    int ding = 1;
    cout << "ding" << " " << ding << endl;
    return 0;
}
```

which is okay for C/C++ and in fact needed for the concatenation. 

With the multiline SWIG macros, behaviour has drifted quite far from the C preprocessor but not in this respect, I'm not sure it can depart from this fundamental handling, or not very easily anyway. 

One thing in the problem example I was thinking is that everything between %{...%} should not be preprocessed and hence the whitespace collapsing would not be needed. Clearly:
```
%define %bar
%pythoncode %{
   def one(self):
      # Comment XXXX
      return 1
%}
```
When run with 'swig -E' results in:
```
struct TYPE {
/*@SWIG:example.i,9,%bar@*/%insert("python") %{
   def one(self):
#Comment XXXX
      return 1
%}
/*@SWIG@*/
};

```
I modified the SWIG preprocessor so that %{...%} within a macro is not preprocessed so then the desired output is obtained:
```
struct TYPE {
/*@SWIG:example.i,9,%bar@*/%insert("python") %{
   def one(self):
      # Comment XXXX
      return 1
%}
/*@SWIG@*/
};
```
However, testing the test-suite shows that the SWIG library with this change shows that it relies on the preprocessor processing %{...%} blocks.

From Lib/attribute.swg:
```
%define %attribute_custom(Class, AttributeType, AttributeName, GetMethod, SetMethod, GetMethodCall, SetMethodCall)
...
  %{
    #define %mangle(Class) ##_## AttributeName ## _get(self_) GetMethodCall
    #define %mangle(Class) ##_## AttributeName ## _set(self_, val_) SetMethodCall
  %}

```
and I can't see an alternative approach that will work very well, maybe someone else can. Here is the source code patch:

```
diff --git a/Source/Preprocessor/cpp.c b/Source/Preprocessor/cpp.c
index a183eec..e4c07e7 100644
--- a/Source/Preprocessor/cpp.c
+++ b/Source/Preprocessor/cpp.c
@@ -435,6 +435,8 @@ Hash *Preprocessor_define(const_String_or_char_ptr _str, int swigmacro) {
          state = 20;
        else if (*cc == '\"')
          state = 30;
+       else if (*cc == '%')
+         state = 40;
        break;
       case 10:
        if (*cc == '*')
@@ -478,6 +480,24 @@ Hash *Preprocessor_define(const_String_or_char_ptr _str, int swigmacro) {
       case 31:
        state = 30;
        break;
+      case 40:
+       if (*cc == '{')
+         state = 41;
+       else
+         state = 0;
+       break;
+      case 41:
+       if (*cc == '%')
+         state = 42;
+       else
+         state = 41;
+       break;
+      case 42:
+       if (*cc == '}')
+         state = 0;
+       else
+         state = 41;
+       break;
       default:
        break;
       }
```

**Comment by ojwb** [comment]
What about the patch in my comment earlier in this discussion (4th comment, but github unhelpfully doesn't number the comments)?

If SWIG reliably removes whitespace before `#`, that does the right thing.

The existing code there could probably do with an overhaul though - skipping the first `initial` bytes without checking that they are actually spaces just seems to be asking for trouble.

**Comment by wsfulton** [comment]
Your patch does the job and I think we should use it given the current behaviour. Yes I think it should be reworked and not chomp characters from lines that are shorter than the initial indentation. A warning of some sort? I think documenting the %pythoncode family of directives and limitations is also needed.

It won't stop the preprocessor from altering code such as:
```python
def one():
  return 0 # comment
```
as it will change it into:
```python
def one():
  return 0#comment
```
but although annoying to the user, it is harmless. A more complex solution would be to only collapse the whitespace around macro variables that actually exist, rather than everything around any #.

**Comment by ojwb** [comment]
Your example doesn't actually seem to behave as you suggest - whitespace is preserved (tested with a89a4d9).

Here's a testcase that currently gets silently damaged, so a warning if the truncation would eat characters other than spaces sounds like a good idea:

```
%pythoncode %{
    def foo():
	a = 1 # This line starts with a tab instead of 8 spaces.
        return 2
```

While PEP-<whatever it is> frowns upon using tabs, they work (in Python 3 you have to use them consistently, while Python 2 is more forgiving) and the result isn't expected:

```
def foo():
 1
    return 2
```

Clearly you could construct examples which result in different yet valid Python code due to this truncation.

Additionally, perhaps `%pythoncode` should warn if it sees literal tabs, though it won't see any before `#` as things stand of course.

**Comment by wsfulton** [comment]
@ojwb, could you check again? I'm using this:
```
%define %bar
%pythoncode %{
   def one():
      return 1 # comment
%}
%enddef

struct TYPE {
%bar
};
```
results in:
```
    def one():
       return 1#comment
```

The warning would help with incorrect Python code too, for example the spacing is out by one character for the 2nd def:
```
%pythoncode %{
   def one():
      return 1
  def two():
    return 2
%}
```
resulting in the puzzling:
```
    def one():
       return 1
    ef two():
     return 2
```
I suggest we don't truncate, rather show the whole line and instead mess around with the whitespace.

Iit might be best to find the least indented line instead of the first line to work out the indentation (excluding lines starting with '#'). I'm not sure what to do about tabs though. How about work out the least indented line treating tab as say one space and use that as the expected indentation, then warn about any lines that don't start with this pattern.

**Comment by ojwb** [comment]
I tested the example you originally pasted, which works.

With the extra `%define bar` layer added, the spaces are indeed lost.  But that's a rather more obscure case at least.

**Comment by wsfulton** [comment]
This bug report is specifically about using macros for %pythoncode though and what I posted is a small variation on the original code reported. My point is when using *macros*, the spaces are lost.

The way I see the bigger problem is previously '%pythoncode { ... }' worked fine (but silently swallowed the comments), but now this fails with 'Error: Unknown SWIG preprocessor directive: comment (if this is a block of target language code, delimit it with %{ and %})'. Users are thus forced to use '%pythoncode %{ ... %}' which is what the bug is about. Hence we have a regression in that something previously worked and now can't be simply fixed (unless all comments are removed from within %pythoncode).

**Comment by ojwb** [comment]
While the original reproducer provided by the reporter used a macro, I wouldn't agree that this ticket is specifically about the use of macros.  My simplified reproducer (second comment) doesn't use one, and nobody's suggested that is a different issue.

`%pythoncode { ... }` was never really correct - it just happened to mostly work due to a bug (that SWIG silently ignored unknown directives), and it didn't work fine in all cases - a comment which happened to start with a word like `error` or `if` would misbehave.  And as you note yourself, comments were lost in the generated python wrapper.

Looking for the least indented line just seems to complicate things, and opens the door to allowing craziness such as:

```
%pythoncode %{
    def one():
        print "in one"
%}

%pythoncode %{
        print "still in one"

    def two():
        print "in two"
%}
```

I hope everyone agrees that this example should give an error (currently SWIG quietly generates a Python wrapper which gives `SyntaxError: invalid syntax` when run).

I propose the following:

Any lines which have `#` as the first character are left alone.  This is OK since Python doesn't actually care about the indentation of lines which only contain a comment, which is a consequence of this:

> A logical line that contains only spaces, tabs, formfeeds and possibly a comment, is ignored (i.e., no NEWLINE token is generated).

(see https://docs.python.org/2/reference/lexical_analysis.html#blank-lines and https://docs.python.org/3/reference/lexical_analysis.html#blank-lines)

Similarly, we can trivially deal with lines which are entirely whitespace.

Otherwise, we take the whitespace prefix from first line as now (except we consider the first line which isn't all whitespace and doesn't start with `#`), but check that this is an exact match for the prefix of subsequent lines before removing it.

If the prefix for a subsequent line isn't an exact match, we check if the prefix of the same length (i.e. what we'd remove in current releases) is all whitespace - if so, we issue a warning and remove that length prefix as currently (so we don't gratuitously break existing interface files); if not, we issue an error (since removing non-whitespace indicates a bug, and existing interface files where this happens are unlikely to be working as intended - this would give an error for my above crazy example).

I think this provides the right level of compatibility with existing interface files, and useful diagnostics for cases which deserve them.

If that all sounds reasonable, I can try to code this up.

The only remaining issue I can see is the loss of whitespace around `#` when a macro wrapper is used.  That also happens with `%pythoncode { }`, so isn't fallout from the new unknown directive error.  It also seems not to be specific to `%pythoncode`, and it is particularly going to be an issue for any directive which takes a block of target language code if the target language syntax makes use of `#`.  I haven't yet managed to think of an example where removing whitespace around `#` causes a change in the meaning of code (the preprocessor doesn't do it inside strings delimited by `'` or `"`), and I'm not sure how it could sanely be addressed, so I don't propose to try to address that as part of this.

**Comment by wsfulton** [comment]
Yes this all sounds good, please have a go at coding it up.

Regarding whitespace removal around '#', I think the behaviour is acceptable and we should simply document limitations of using the macro and %pythoncode as I suggested earlier. If this whitespace removal is undesirable, macros will simply have to be avoided QED.

**Comment by ojwb** [comment]
However, I've come up with some cases where it changes the meaning of the code - Lua's "long quotes" - for example:

```
%define %bar
%luacode %{
   function one ()
     print [[I am #1]]
   end
%}
%enddef

struct TYPE {
%bar
};
```

Interestingly, `[[I'm #1]]` works fine (because the SWIG preprocessor thinks the `#` is inside a single quoted string), which makes a patch to change "I am" to "I'm" potentially problematic.

There are also several cases for Perl - `qq`, regular expressions, etc:

```
%define %bar
%perlcode %{
   sub one {
     my $arg = shift;
     print qq(I am #1\n);
     $arg =~ s/# .*//;
     return $arg;
   }
%}
%enddef

struct TYPE {
%bar
};
```

On the plus side, there's also a reasonably nice way to protect the code while still allowing the use of macros - just put the target language code into a separate file and get `%perlcode` (or equivalent) to read that:

```
%define %bar
%perlcode "subone.pl"
%enddef

struct TYPE {
%bar
};
```

If it was just cosmetic in the sources, I'd totally agree that documenting it and moving on is fine.  I'm a bit less comfortable with doing so when there are cases like the above, though this has presumably been an issue for many years and I don't remember any reports of people hitting it.  I also still don't have a good suggestion for how to address it in the code.

**Comment by wsfulton** [comment]
I still think that these are limitations that users will have to live with. Using "" quotes as @ojwb suggested works with too 
```
%pythoncode "pycode.py"
```
and is a great idea as it will literally dump the contents of pycode.py into the proxy class. This is a reasonable alternative for those that really want to use the preprocessor and should also be clearly documented. Given this issue hasn't really been brought up before, I think the improvements discussed here will suffice.

I didn't follow your concern in the last sentence... you've analysed various problems well and come up reasonable solutions/workarounds.

**Comment by ojwb** [comment]
I've pushed branch issue-379-pythoncode-indent which implements this, and handles the three cases in comments here nicely.  I've not added any testcases for this yet though.

One thing I'm not sure how to deal with is finding the appropriate file and line number for error/warning messages.  Currently I call `Getfile()` and `Getline()` on the node the data was attached to, assume that line number refers to the last line in the block, adjust it to point to the first, then increment it as we process each line.  That reports an error on the `def two():` line in the case above (which is correct), but I feel it's not a very robust approach.  Any better ideas?

**Comment by ojwb** [comment]
https://github.com/swig/swig/tree/issue-379-pythoncode-indent

**Comment by ojwb** [comment]
And I get the same results from the existing python testsuite after these changes as before.

**Comment by wsfulton** [comment]
Are we going to try and indent comment lines which have been preprocessed? Only comment 1 below (if put in a macro like %bar above) is indented.
```
    # comment 1
    def one(self):
        # comment 2
        print "in one"
        # comment 3
        # comment 4
        print "still in one"
```
You are right about the line reporting for the error not being robust. If you modify the %bar macro example above with bad indentation, the line reporting is not right. I don't really know what the best thing is to fix this. How about reporting the end of the %pythoncode block as the main file and line number and mention the nth line as containing the error, so instead of:
```
example.i:21: Error: Line indented less than expected
```
Something like:
```
example.i:22: Error: Line 3 in the python code block ending here contains an indentation which is less than expected.
```
Where 22 is from Getline(n), ie the end of %insert("pythoncode") %{ ... %}

William

**Comment by ojwb** [comment]
I didn't (and don't) propose to try to adjust the indent of comments.  As I pointed out earlier, Python doesn't care about the indentation of lines which are just a comment, so it's just a cosmetic issue in the generated file.  But I wrote the code to handle them as other lines should SWIG's preprocessor change to not eating the whitespace before a `#` in this situation.

Actually, I was thinking more about this case - the file+line isn't right for the autodoc, but I'm not really sure what to put there:

```
+      Printv(doc, triple_double, "\n",
+	     pythoncode(autodoc, indent, Getfile(n), Getline(n)), "\n",
+	     pythoncode(str, indent, Getfile(n), Getline(n)), indent, triple_double, NIL);
```

I guess the autodoc we generate shouldn't be invalid, so this doesn't actually matter in practice.  It feels wrong to be processing the unquoted contents of the autodoc string with `pythoncode()` at all really - it's text not python code.

I don't really understand why SWIG gets the wrong line for your case - the `-E` output contains the appropriate `@SWIG` markers pointing to where `bar` was defined:

```
struct TYPE {
/*@SWIG:i379.i,3,%bar@*/%insert("python") %{
   def one():
#Comment XXXX
  return 1
%}
/*@SWIG@*/
};
%endoffile
```

So why isn't the llne number for the `%insert` taken from those markers?

**Comment by ojwb** [comment]
> So why isn't the line number for the %insert taken from those markers?

@wsfulton Any ideas about this?  It seems to me this should just work already, but testing shows it doesn't.

> Where 22 is from Getline(n), ie the end of %insert("pythoncode") %{ ... %}

When I test this, the line I get this reported at is the `%bar` line rather than the end of the `%pythoncode` block (if it was the end of the `%pythoncode` block, then my counting back would work).

I guess we can go with this and hope the user will realise that there's a pythoncode block inside the macro expanded there, rather than just assuming SWIG's pointing to the wrong place.  It's arguably better than the current situation at least.

**Comment by wsfulton** [comment]
The warnings and errors always report the line and file of the line invoking the macro and not the line number in the actual macro. This is for all warning and errors after the preprocessing stage.  The -macroerror option changes the line reporting behaviour along the lines you are thinking. Reworking the warning system to report all macro expansions in errors like newer gcc does would be a better approach. However, I would rather a quick fix using something like the wording suggestion I posted so we can make the release asap.

**Comment by ojwb** [comment]
Sorry, will try to get this sorted out.  Have been rather buried lately (and still am, but this isn't far from done so I should push it through).

**Comment by ojwb** [comment]
My work here is done.
