### ISSUE TITLE
CA1063 Implement IDisposable correctly

### ISSUE THREAD

**Issue by gpetrou** [swig/swig#421]
Running code analysis in Visual studio generates many of these warnings for swig generated code.

```
public virtual void Dispose() {
lock(this) {
  if (swigCPtr.Handle != global::System.IntPtr.Zero) {
    if (swigCMemOwn) {
      swigCMemOwn = false;
      TestWrapperPINVOKE.delete_Test(swigCPtr);
    }
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
  }
  global::System.GC.SuppressFinalize(this);
}
}
```

More details on the warning:
https://msdn.microsoft.com/en-us/library/ms244737.aspx

**Comment by wsfulton** [comment]
Visual Studio 2013 doesn't generate these warnings in our Appveyor testing, eg see https://ci.appveyor.com/project/swig/swig/build/job/vc3pfu03w2mii0yh. Do you have to do something to turn them on?

What are the proposed fixes? You can modify the source of this code in csdestruct and csdestruct_derived typemaps in Lib/csharp/csharp.swg.

**Comment by gpetrou** [comment]
I assume Appveyor outputs build warnings not Code Analysis warnings (FxCop etc...)?
Regarding the code modification I assume we could have for csfinalize something like:
    
        %typemap(csfinalize) SWIGTYPE %{
  
    // Dispose() calls Dispose(true)
    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }
    // NOTE: Leave out the finalizer altogether if this class doesn't 
    // own unmanaged resources itself, but leave the other methods
    // exactly as they are. 
    ~$csclassname()
    {
        // Finalizer calls Dispose(false)
        Dispose(false);
      }  
    %}

Regarding csdestruct and csdestruct_derived we would need to add a "bool disposing" parameter. Not sure how to do that with the existing code but it would end up like:
   
     protected virtual void Dispose(bool disposing)
    {
        if (disposing) 
        {
            // free managed resources            
        }

        // free native resources if there are any.        
    }

and 

       bool disposed = false;
       protected override void Dispose(bool disposing)
         {
            if (disposed)
             return; 

              if (disposing) {        
                  // Free any other managed objects here.        
        }

      // Free any unmanaged objects here. 
      //

      disposed = true;
      // Call base class implementation. 
      base.Dispose(disposing);
   }

for the derived case.
There is more information in the links.
https://msdn.microsoft.com/en-us/library/ms244737.aspx
https://msdn.microsoft.com/en-us/library/fs2xkftw%28v=vs.110%29.aspx

**Comment by wsfulton** [comment]
I suspect this will break existing code and it doesn't fix anything, so will mark this bug for consideration for swig-3.1. Patches for implementation are required. How about putting in warning suppression pragmas instead?

**Comment by gpetrou** [comment]
We could use System.Diagnostics.CodeAnalysis.SuppressMessage, but isn't better to follow the proposed pattern? If I knew how to add the disposing parameter csdestruct and csdestruct_derived I could probably make a small PR

**Comment by wsfulton** [comment]
I think this will require code changes to csharp.cxx and support for additional typemap attributes or additional typemaps. I still think keeping existing code working is more important than 'fixing' this as I don't see that there is actually any problem.

**Comment by mwpowellhtx** [comment]
Has this been fixed yet? I agree with @gpetrou, more or less, but to be fair I also haven't analyzed the generated disposable code.

Generally, from a best practices standpoint, the approach is exactly correct along these lines:

```C#
protected virtual void Dispose(bool disposing)
{
    if (disposing)
    {
    }
}

public void Dispose()
{
    Dispose(true);
}
```

Which also generally leaves room for the *C# Destructor*, *.NET finalizer*:

```C#
~MyClass()
{
    Dispose(false);
}
```

I generally like to include an ``IsDisposed`` flag as well.

```C#
protected virtual bool IsDisposed { get; private set; }

public virtual void Dispose(bool disposing)
{
    if (!IsDisposed && disposing)
    {
   }
}

public void Dispose()
{
    Dispose(true);
    IsDisposed = true;
}
```

I'll just conclude with the principle, if you don't want to "fix" the broken philosophical approach, then the code will not behave as expected under the .NET runtime. Simple as that. That's well worth correcting the course, because folks would otherwise be working around that broken philosophy.

**Comment by wsfulton** [comment]
I have a patch to implement this for swig-4.0.0. It is not backwards compatible for users that have defined their own "csfinalize", "csdestruct" or "csdestruct_derived".

The logic in the new generated code is nearly identical to the original generated code, so I'm not convinced it will make all that much difference. Nevertheless, I'm going to commit this change as the disruption will be very limited as the vast majority of users use the default versions of these typemaps and won't have to do anything. Only users that have written code for the aforementioned typemaps will need to implement the changes I'll describe in subsequent comment. The major new SWIG release provides a window of opportunity to address the concerns raised in this issue to implement the recommended IDisposable interface.

**Comment by wsfulton** [comment]
C# Dispose Upgrade Guide
========================

This upgrade is only for users that have defined their own "csfinalize", "csdestruct" or "csdestruct_derived" typemaps.

The changes are such that the recommended IDispose pattern is followed as suggested in this issue and described in https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose and https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1063-implement-idisposable-correctly.  In particular both the `Dispose()` and `Dispose(bool)` methods are generated and not just the one `Dispose()` method.

SWIG will now error out if one of the "csfinalize, "csdestruct" or "csdestruct_derived" typemaps are found as these are no longer used and need to be replaced. Example error messages:

```
foo.h:60 Error: A deprecated csfinalize typemap was found for Foo, please remove it and replace all csdestruct, csdestruct_derived and csfinalize typemaps by the csdispose, csdispose_derived, csdisposing and csdisposing_derived typemaps.
foo.h:78 Error: A deprecated csdestruct typemap was found for Foo, please remove it and replace all csdestruct, csdestruct_derived and csfinalize typemaps by the csdispose, csdispose_derived, csdisposing and csdisposing_derived typemaps.
foo.h:90 Error: A deprecated csdestruct_derived typemap was found for FooDerived, please remove it and replace all csdestruct, csdestruct_derived and csfinalize typemaps by the csdispose, csdispose_derived, csdisposing and csdisposing_derived typemaps.
```

A few simple changes are required for custom typemaps. The changes to swig.swg in https://github.com/swig/swig/commit/06462acdf9b7738a19dce5579d90b1c91b3f9cfb#diff-8356d5285b5b342a204d4ff54fc34973 contain the generic changes that were made and should be studied to obtain the detailed changes. A summary of the changes are:

1. The old "csdestruct" and "csdestruct_derived" typemaps need to be replaced respectively by the new "csdisposing" and "csdisposing_derived" typemaps.
- The old typemaps provided the `void Dispose()` method and the new typemaps provide the `void Dispose(bool disposing)` method.
- The old and new typemaps are very similar in content.
- Of note is the addition of the disposing parameter and a change to the base.Dispose call to include the disposing parameter and methodmodifiers change from public to protected.
- Also the GC.SuppressFinalize method has moved to the new "csdispose" typemap.

2. The old "csfinalize" typemaps need to be replaced by the new "csdispose" and/or "csdispose_derived" typemaps.
- The "csdispose" typemap implements the `void Dispose()` public method that used to be in the "csdestruct" and "csdestruct_derived" typemaps.
- It calls Dispose(true) as per the Microsoft recommendations.
- It should also contain the Finalize (destructor) C# method that used to be in the "csfinalize" typemap.

Inaccessible C++ destructors
============================
If the destructor cannot be wrapped, for example, when using %nodefaultdtor or the destructor is private or protected, a MethodAccessException("C++ destructor does not have public access") will be thrown when the finalizer calls Dispose. Before swig-4.0.0 the finalizer was not generated, but the exception would still be thrown when calling Dispose. In swig-4.0.0, both the finalizer and the Dispose method are generated by default and will throw the `MethodAccessException`. This is something that often needs to be addressed in some way, but really depends on why the destructor is not accessible. It could be handled by providing a "csdispose" or "csdispose_override" typemap that does not call Dispose, such as the following (but be sure to use "csdisposing_derived" instead of "csdisposing" if class F is not at the top of an inheritance hierarchy):

```swig
%typemap(csdisposing, methodname="Dispose", methodmodifiers="protected", parameters="bool disposing") F {
    // cannot access C++ destructor
  }

class F {
private:
   ~F();
public:
    ...
};
```
to generate:
```c#
public class F : global::System.IDisposable {
  ...
  protected virtual void Dispose(bool disposing) {
    // cannot access C++ destructor
  }
```
instead of the default:
```c#
public class F : global::System.IDisposable {
  ...
  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }
```
This may create a memory leak, or perhaps there is some other way that the C++ class' memory needs to be destroyed which can be coded into the C# Dispose method.

If you are using Visual Studio's static analyzer / FxCop, you may get the following warning if this is not addressed
```
F.cs(40,1) : warning  : CA1065 : Microsoft.Design : 'F.Dispose(bool)' creates an exception of type 'MethodAccessException'. Exceptions should not be raised in this type of method. If this exception instance might be raised, change this method's logic so it no longer raises an exception.
```

Legacy Dispose Code Upgrade Guide
==============================

If you absolutely have to have code that is identical to that generated in earlier versions of SWIG and have not defined your own "csfinalize", "csdestruct" or "csdestruct_derived" typemaps, then simply copy these typemaps to the top of your interface file:

```swig
%typemap(csdispose) SWIGTYPE %{
  ~$csclassname() {
    Dispose();
  }
%}

%typemap(csdispose_derived) SWIGTYPE %{
  ~$csclassname() {
    Dispose();
  }
%}

%typemap(csdisposing, methodname="Dispose", methodmodifiers="public", parameters="") SWIGTYPE {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          $imcall;
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

%typemap(csdisposing_derived, methodname="Dispose", methodmodifiers="public", parameters="") SWIGTYPE {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          $imcall;
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }
```
Similar typemaps will also need to be provided for the smart pointers though if you %included std_shared_ptr.i or boost_intrusive_ptr.i.
