### ISSUE TITLE
[Go] Public abstract method gets wrapped; Constructor gets wrapped on director enabled abstract class

### ISSUE THREAD

**Issue by michael-schaller** [swig/swig#435]
As discussed in issue #418, SWIG seems to wrap methods/constructors when it shouldn't.

Abstract C++ example class:
``` C++
class Abs
{
public:
	Abs() {};
	virtual ~Abs() {};
 
	virtual void MakeAbs() = 0;
};
```

Under all circumstances the Go wrapper includes a MakeAbs method albeit Abs::MakeAbs being abstract:
``` Go
type Abs interface {
	Swigcptr() uintptr
	SwigIsAbs()
	MakeAbs()
}
```

If the director feature is enabled for the Abs C++ class then the Go wrapper includes a NewAbs function to construct an Abs object:
``` Go
func NewAbs() (_swig_ret Abs) {...}
```
As the Abs C++ class is abstract this constructor function doesn't make sense and if someone tries to use the constructor function the Go panic "accessing abstract class or protected constructor" gets raised.

The complete example code can be found here:
https://gist.github.com/michael-schaller/05e2896c094b47dbbb22

This has been tested with the following versions:
```
~/git/go$ go version
go version devel +a1fe3b5 Sat Jun 13 04:33:26 2015 +0000 linux/amd64
```
```
~/git/swig$ git log -n1
commit b94820adcfe05b48c0e553e4e4fd0b32f385651f
Author: William S Fulton <wsf@fultondesigns.co.uk>
Date:   Fri Jun 12 23:37:08 2015 +0100

    Fix r.cxx build break
```

FYI: @ianlancetaylor

**Comment by michael-schaller** [comment]
@ianlancetaylor
Ian, do you think this is an issue with the Go wrapper code generation or do you think this is a general Swig issue that affects all target languages?

**Comment by ianlancetaylor** [comment]
I expect it's in the Go wrapper code, but I don't know for certain.

**Comment by wsfulton** [comment]
I'm not sure I can comment much on the Go wrappers, but this is needed for other languages, for example Java. I'll try explain why for Java and then hopefully that is useful for Go.

There is a Java constructor for Abs and you can indeed call the pure virtual methods. In the case of a Java class implementing the pure abstract method and deriving from C++ Abs, a Java Abs proxy still needs to be instantiated, hence a Java constructor is available for the Java Abs. The underlying C++ class also needs instantiating, hence the SwigDirector_Abs C++ class which provides the ability to instantiate what is not meant to be instantiated (the C++ Abs). 

The MakeAbs() must also be available when called from C++, as it can potentially make the upcall to Java in case a Java class has implemented this method. Note that SwigDirector_Abs::MakeAbs() will throw a runtime error if there is no Java class implementing MakeAbs() as a compile time error is not possible because of the need to call up to Java in case a Java class has implemented it.

**Comment by michael-schaller** [comment]
Thanks, Ian.
