### ISSUE TITLE
generated C# code has duplicate parameters size, rows and cols

### ISSUE THREAD

**Issue by tpokorra** [swig/swig#448]
We have this issue with Mono4, and shogun:

https://github.com/shogun-toolbox/shogun/issues/2425

The generated code looks for example like this:

  [global::System.Runtime.InteropServices.DllImport("modshogun", EntryPoint="CSharp_new_IndexBlockTree__SWIG_3")]
  public static extern global::System.IntPtr new_IndexBlockTree__SWIG_3(int size, [MarshalAs(UnmanagedType.LPArray)]double[] jarg1, int size, [MarshalAs(UnmanagedType.LPArray)]double[] jarg2);

or 

  [global::System.Runtime.InteropServices.DllImport("modshogun", EntryPoint="CSharp_ConvolutionalFeatureMap_compute_gradients")]
  public static extern void ConvolutionalFeatureMap_compute_gradients(global::System.Runtime.InteropServices.HandleRef jarg1, int size, [MarshalAs(UnmanagedType.LPArray)]double[] jarg2, int rows, int cols, [MarshalAs(UnmanagedType.LPArray)]double[,] jarg3, int rows, int cols, [MarshalAs(UnmanagedType.LPArray)]double[,] jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, int size, [MarshalAs(UnmanagedType.LPArray)]int[] jarg6, int size, [MarshalAs(UnmanagedType.LPArray)]double[] jarg7);

The template is here: [swig_typemaps.i](https://github.com/shogun-toolbox/shogun/blob/develop/src/interfaces/csharp_modular/swig_typemaps.i)

I tried to find the place in the swig code that does this replacement.
I have experimented with https://github.com/swig/swig/blob/master/Source/Swig/typemap.c#L961 but did not get anywhere.

Any ideas?

**Comment by wsfulton** [comment]
I don't have enough info from the above to replicate easily. Probably it is due to this line though in swig_typemaps.i:
```swig
%typemap(imtype, out="IntPtr", inattributes="int size, [MarshalAs(UnmanagedType.LPArray)]") shogun::SGVector<SGTYPE> %{CSHARPTYPE[]%}
```
That seems like an abuse of inattributes as it is adding in an additional parameter in addition to adding the attributes for the following parameter. Whoever wrote the typemaps ought to rethink this. If they really want to use this approach then provide different typemaps for each named parameter in the functions using this typemap. I expect this started to go wrong when someone added additional methods to the api being wrapped. Also consider just ignoring the method with %ignore.
