### ISSUE TITLE
Vector of enum class type generates code not accepted by MSVC

### ISSUE THREAD

**Issue by hacst** [swig/swig#464]
Given this .i file:

``` cpp
%module EnumClassGenerationIssue

%include <std_vector.i>

%inline {
enum class TestEnum {};
}

%template(TestEnumVector) std::vector<TestEnum>;
```

When building a wrapper for say java from this using SWIG 3.0.6 the native C++ part it generates contains snippets like:

``` cpp
std::vector< enum TestEnum >::value_type temp2 ;
```

Which trigger:

```
error C3431: 'TestEnum' : a scoped enumeration cannot be redeclared as an unscoped enumeration
```

In MSVC. From what I can tell what SWIG generates is valid C++11 but is neither accepted by VS 2013 nor the upcoming 2015. gcc and clang have no issue with the construct.

This has been reported as a bug against MSVC multiple times in the past but doesn't seem to be something they want to fix anytime soon:
https://connect.microsoft.com/VisualStudio/feedback/details/781517/enum-class-example-from-c-11-standard-produces-compilation-error
https://connect.microsoft.com/VisualStudio/feedback/details/771978/compiler-error-c3431-using-elaborated-type-specifiers-for-scoped-enumerations

I'm not sure what SWIG's policy is on working around such conformance issues in specific compilers. As it is enum classes in SWIG are not fully usable with MSVC and won't be for quite some time so as a user a workaround would be useful.

**Comment by hacst** [comment]
If you don't have a MSVC handy you can use http://webcompiler.cloudapp.net/ and paste
```cpp
#include <vector>

enum class Test {};

std::vector<enum Test> foo;
int main() {}
```
to see how visual studio 2015 behaves.

**Comment by wsfulton** [comment]
This also occurs with regular C++98 enums.

Unfortunately I can't think of a workaround for this. SWIG will try its best to use the types parsed in function definitions. Template parameter types provided in %template are a bit different and are expanded in many places. You'll notice that it is only for the typedef'd types within std::vector, eg size_type, const_reference, value_type etc. 

Generally SWIG will swallow 'enum ' in many places, so we could probably do better but this isn't going to be easy to fix. 

The only workaround I can think of that might work is to provide an alternative version of std_vector.i which avoids the use of the typedefs within std::vector. So for example, use size_t instead of std::vector::size_type.

**Comment by hacst** [comment]
Changing the vector to remove the typedefs is ok for me (not using the default one as it doesn't look like a normal collection in Java) and indeed seems to remove most occurrences for the issue. Unfortunately in my example one remains in the generated setter for the vector entries:
```cpp
TestEnum *arg3 = 0;
...
try {
     std_vector_Sl_TestEnum_Sg__set(arg1,arg2,(enum TestEnum const &)*arg3);
}
```
with the signature of the set method being:
```cpp
SWIGINTERN void std_vector_Sl_TestEnum_Sg__set(std::vector< TestEnum > *self,int i,TestEnum const &val)
```

Not quite sure what is causing it to be expanded this way here as the cast is redundant. If I change the signature of the set method to take a ```T& val``` instead of a ```const T& val``` the cast goes away so it's not like it's checking the underlying ```value_type& operator[](size_type n)``` and isn't able figure out the types are the same. I guess since Java doesn't know the concept of constness I might get away with removing the const but I'm not sure...

Before your reply my questionable workaround for the whole complex consisted of running two search and replaces (```s/< enum /< /g``` and ```s/\(enum /( /g```) on the generated wrappers to strip the enums from template parameters and casts. While that works I definitely would prefer an in-swig solution if that is doable though.

In any case I'll try to re-report the bug to Microsoft. Maybe they are more interested in standard compliance these days...

Can you elaborate a bit on why SWIG is adding the ```enum``` type specifier in the first place? While I do realize [elaborated type specifiers](http://en.cppreference.com/w/cpp/language/elaborated_type_specifier) have their uses SWIG doesn't seem to apply them consistently (well...it might if it actually knows whether it needs them in the other situations). Is it just a convenient thing to do design wise or is there a deeper reason?

Thanks a lot for your answer so far.

**Comment by wsfulton** [comment]
I'm not sure why ```enum``` is being added as a prefix without debugging it. Possibly during the resolution of the template parameters it adds the prefix. It feels like a bug to me.

Generally SWIG will generate code that uses the type as parsed without adding any elaborated type specifiers. However, elaborated type specifiers are discarded which is not ideal. Due to the implementation of the type system in SWIG means that it isn't possible to keep them.

**Comment by SamuelEnglard** [comment]
This seems to be fixed with MSVC 19.15.26730 (latest with VS 2017)

**Comment by wsfulton** [comment]
I'm going to close this as I can't in all honesty see it being fixed easily and MSVC is now standards conforming in this area.

**Comment by hacst** [comment]
Totally fine by me. I ended up using the regexes I mentioned in production and that has worked fine for the last three years ;) Now that I know it is fixed I can just ditch that workaround once we transition to the new compiler. Thanks for tracking the issue till now!
