### ISSUE TITLE
Python Error: Line indented less than expected...

### ISSUE THREAD

**Issue by blowekamp** [swig/swig#475]
I was just trying to upgrade to Swig 3.0.6. And I am getting errors when swig is run on my project. Errors like this:
  /home/blowekamp/src/SimpleITK/Code/Common/include/sitkVersion.h:33: Error: Line indented less than expected (line 4 of python code)
  https://open.cdash.org/viewBuildError.php?buildid=3918482

It appears to be related to using the docstring feature with classes and methods.

Working on minimal example...

**Comment by blowekamp** [comment]
Here is a minimal failure case:

%module xxx

%feature("docstring") xxx "
  Some docstrings.

Different indent.
";

%inline %{
  int xxx() { return 1;  };
%}

$ /dev/shm/SimpleITK/Swig/bin/swig -python swig_docstring.i 
swig_docstring.i:10: Error: Line indented less than expected (line 3 of pythoncode)
swig_docstring.i:10: Error: Line indented less than expected (line 3 of pythoncode)

**Comment by wsfulton** [comment]
The formatting in the failure case above isn't correct for viewing in Github markup, so here it is corrected

```
%module xxx

%feature("docstring") xxx "
  Some docstrings.

Different indent.
";

%inline %{
  int xxx() { return 1;  };
%}
```

**Comment by wsfulton** [comment]
For SWIG-3.0.5, the above resulted in the following generated code in the .py file:
```python
def xxx():
    """
    Some docstrings.

    fferent indent.

    """
    return _xxx.xxx()
```
Clearly this truncation is not correct/intentional. Hence in SWiG-3.0.6, there is the error, which is really saying that you should fix your indentation. The actual error message isn't very good though as it should refer to the docstring feature rather than reference ```%pythoncode```. This error message was specificallly implemented for ```%pythoncode```, but it is possible that docstrings were overlooked. @ojwb did most of this, but I believe is away on holiday at the moment, but I would appreciate some input from him. I will take a look though. @ojwb maybe we should turn this into a warning instead?

The build of plplot was also reported as broken on the swig-user mailing list for the same reason.

**Comment by blowekamp** [comment]
Great! Thanks for addressing this so promptly.

**Comment by wsfulton** [comment]
I plan to release this in 3.0.7 in the next few days. If you can test it asap and make sure this is fixed for you and that there are no other problems, that would be appreciated.

**Comment by blowekamp** [comment]
With the current master I am getting the following error running swig from build or installed:
[ 57%] Swig source to generate PYTHON wrapping
:1: Error: Unable to find 'swig.swg'
:3: Error: Unable to find 'python.swg'
/home/blowekamp/src/SimpleITK/Wrapping/SimpleITK.i:24: Error: Unable to find 'std_vector.i'
/home/blowekamp/src/SimpleITK/Wrapping/SimpleITK.i:25: Error: Unable to find 'std_string.i'
/home/blowekamp/src/SimpleITK/Wrapping/SimpleITK.i:26: Error: Unable to find 'std_map.i'
/home/blowekamp/src/SimpleITK/Wrapping/SimpleITK.i:28: Error: Unable to find 'std_complex.i'
/home/blowekamp/src/SimpleITK/Wrapping/SimpleITK.i:31: Error: Unable to find 'stdint.i'
/home/blowekamp/src/SimpleITK/Wrapping/SimpleITK.i:34: Error: Unable to find 'exception.i'
make[2]: *** [Wrapping/SimpleITKPYTHON_wrap.cxx] Error 1

I'll try again on monday.

**Comment by wsfulton** [comment]
You need to set the SWIG_LIB environment variable to the Lib directory

**Comment by blowekamp** [comment]
The patch seems to works. My tests for Python, Lua, Tcl, Ruby, Java and CSharp pass too. R continues to have stability issues.

**Comment by wsfulton** [comment]
Thanks for feedback. Please post details of any R problems in a separate issue.
