### ISSUE TITLE
Default golang typemaps treat signed/unsigned char* as string

### ISSUE THREAD

**Issue by demi-rluddy** [swig/swig#505]
I'm wrapping a library that makes heavy use of unsigned char arrays as arrays of 8-bit numeric values which often include zeroes.

The default golang handling of these is to treat them as a zero-terminated string: the same special handling that a char* gets. This leads to a lot of trouble wrapping it properly, as these are not really strings and the normal response of "tell swig to treat it like an explicitly signed or unsigned char" doesn't help.

It seems to me that the least surprising (and likely intended) default behavior would be to treat a char* as a string (as it already does) but do no special string handling for an unsigned char* or signed char*.

All tests still appear to pass when the behavior is changed to how I suggest, which makes me believe the current behavior was a minor oversight rather than intended functionality.

**Comment by wsfulton** [comment]
These should be handled by an opaque pointer wrapper by default, so agreed that they shouldn't be handled as a string by default. This is how all the other languages work.

If the typemaps.i library is used, the wrappers are then as a single number as either an input, output or input and output. Note that this is also not treating the pointer as a string. This isn't default handling though as it requires the use of %apply.

**Comment by ScarletTanager** [comment]
I've hit this as well, and I've got test code to demonstrate the bug [here.](https://github.com/ScarletTanager/tmlib)

To wit, using the typemap `%apply unsigned char *OUTPUT {unsigned char *buf};` will result in only a single byte/char buffer being allocated in the wrapper code, which is what @wsfulton is pointing out in his second comment above.  I've worked around this by writing this typemap:

    %typemap(gotype) char *outbuf %{[]byte%}
    %typemap(in) char *outbuf {
    	char tbuf[sizeof($input)];
    	$1 = (char *)&tbuf;
    }    
    %typemap(argout) char *outbuf {
    	memcpy($input.array, $1, $input.cap);
    	$input.len = strlen($1);
    }

I don't think your suggestion in your first comment will work in the case of an "output argument" (a writable buffer supplied to store output instead of passing it back as the return value) @wsfulton , since a gostring is actually a struct with both a pointer to the internal byte array and a length value.  I think you may need a memcpy() call somewhere in the typemap code any way you slice it.  The above is what I'm using for this case, YMMV.

**Comment by ScarletTanager** [comment]
I think this is related to [this issue I opened in early August.](https://github.com/swig/swig/issues/496)
