### ISSUE TITLE
static const data members overwritten by java wrapper

### ISSUE THREAD

**Issue by JasonCxx** [swig/swig#551]
I have a case where data members defined in the original C++ as "static const" are allowed to be overwritten in the Java:

```
    Vector3 v1 = Vector3.getCZero();
    v1.setX(1.0);

    // cZero.x should be zero, not 1.0.
    assertEquals(1.0, Vector3.getCZero().getX(), .000001);
```

where we had defined cZero as (0.0, 0.0, 0.0) as a static const. 

I am presuming this is a bug, unless we have defined something incorrectly. 

Thank you.

**Comment by ojwb** [comment]
It's a documented limitation - §5.2.4 of the manual (SWIG.html) says:

>Please note that for const parameters or return types used in a function, SWIG pretty much ignores
the fact that these are const, see the section on const-correctness for more information.

The linked section is: http://swig.org/Doc4.0/SWIGPlus.html#SWIGPlus_const

It was before my involvement in SWIG, but I assume this approach originated because scripting languages typically don't have the concept of const as part of the type system so SWIG would have had to implement tracking of an "is_const" flag on every wrapped object.  Support for strongly typed languages like Java was added later and followed the existing approach to `const` handling.

Languages like Java presumably could emit `const` on method declarations for return types and parameters which are `const` in C/C++, so I think the point raised here is valid.

**Comment by wsfulton** [comment]
Yes, handling of const has always been as documented and summarised in the link @ojwb gave. There are plenty of other limitations wrapping C++ into other languages and this seems bit of a cop out, but how one would implement const in languages that don't support const is an interesting problem that the core SWIG developers are not planning on solving, as mentioned in that link. Any user interested in putting forward and implementing a generic proposal is of course welcome to do so.

Ways around this limitation are perhaps to use different typemaps for const types where the types are mapped to a 2nd similar type that has all the setters removed. So for the example above, a Vector3_const Java type could be used where the set method has been removed.
