### ISSUE TITLE
Dart support

### ISSUE THREAD

**Issue by Scorpiion** [swig/swig#557]
Hi, I think it would be nice if swig also had support for Dart.

I tried to find some porting guide but could not find one, is there such a thing somewhere?

My guess is that one part is to provide a Dart version of the files listed here (Java used as an example):
https://github.com/swig/swig/tree/master/Lib/java

Is there many other places as well or is that directory the main part that is language specific?

**Comment by geefr** [comment]
The lib folder is all the base swig typemaps, and other macro-like
sections. There's also a C++ side to each module

See:
https://github.com/swig/swig/tree/master/Source/Modules
http://www.swig.org/Doc3.0/SWIGDocumentation.html#Extending_nn2


On 10 November 2015 at 07:46, Robert Åkerblom-Andersson <
notifications@github.com> wrote:

> Hi, I think it would be nice if swig also had support for Dart.
>
> I tried to find some porting guide but could not find one, is there such a
> thing somewhere?
>
> My guess is that one part is to provide a Dart version of the files listed
> here (Java used as an example):
> https://github.com/swig/swig/tree/master/Lib/java
>
> Is there many other places as well or is that directory the main part that
> is language specific?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swig/swig/issues/557>.
>



-- 
--------------------
Gareth Francis
www.gfrancisdev.co.uk

**Comment by Scorpiion** [comment]
Okay, thanks @geefr, good to know. 

It was the new TensorFlow project that made me looking at SWIG in the first place, had not heard about it before. 

If anyone is interested I also created a topic on one of Dart's mailing lists about this here:
https://groups.google.com/a/dartlang.org/d/topic/misc/Zsl3McEvxcE/discussion

**Comment by austincummings** [comment]
:+1:

**Comment by ojwb** [comment]
@austincummings This is an issue tracker, not an online poll.  "+1", "me too", etc comments are just useless noise, and won't make anything happen any faster.  We don't have a team of developers sitting waiting for a feature request to get enough votes.

A new language backend gets added to SWIG because somebody who wants it implements it and submits a patch.  If you actually want to help dart support to happen, work on a patch for it.  You can find the guide to adding support for a new language here:

http://www.swig.org/Doc3.0/Extending.html

**Comment by austincummings** [comment]
@ojwb I understand. I'm merely showing I'd like to see this added. I'm not trying to ask anyone to do it for me. Thank you for referring me to the guide, I'll take a look at it.

**Comment by Sach97** [comment]
Hi guys, since Dart 2.5 ffi is in technical preview, now might be the time to revive this issue

**Comment by ojwb** [comment]
It's still the case that a new language backend gets added to SWIG because somebody who wants it implements it and submits a patch. If you actually want to help dart support to happen, work on a patch for it.  That's the way to revive this issue.

**Comment by Sach97** [comment]
Hey sorry if it came wrong, English is not my native tongue. I didn't want to imply that it needs to be done, I just commented so that other people interested in this could be notified. I make bindings by hand for now so working on a patch is not on top of my priority list. I saw a repo that used swig and didn't have support for Dart and this is how I stumbled upon this issue. If you are a contributor of this repo thank you for your time in open source and sorry if I sounded rude.

**Comment by Sunbreak** [comment]
Anyone intereted in Dart interop with C should use [package:ffigen](https://pub.dev/packages/ffigen), according to https://github.com/dart-lang/sdk/issues/35843

**Comment by ojwb** [comment]
Support for a new target language really needs to be contributed by someone who knows that language.  Nobody has stepped forward offering to do that in 6.5 years, so closing.

If someone is genuinely interested in implementing this and getting it merged into SWIG we can reopen.  To be merged a patch needs to meet the requirements list for a new "experimental" target language: https://www.swig.org/Doc4.0/Extending.html#Extending_experimental_status so please see that to get some idea what you're signing up for.
