### ISSUE TITLE
JavaScript: V8_VERSION problem

### ISSUE THREAD

**Issue by xbolshe** [swig/swig#561]
There is a possibility to have the following V8 engine versions:

![ba93c89a-699e-11e5-9ab0-25bed575cbc9](https://cloud.githubusercontent.com/assets/10796236/11166183/1219f4c8-8b3b-11e5-9e23-d76abc0216c6.jpg)

So, is it correct that versions like 4.5.13.3 and 4.51.3.33 may have the same V8_VERSION value? No.
Or how about any checks for a version, when newer version like 4.51.3 will have lower value 0x4513 than older version 4.5.103 with 0x45103 ?

My proposal is to use V8_VERSION as a hexadecimal value. It means that a version like 4.100.100.100 will be like 0x046464.

This issue creates problems with updating NodeJS to newer version, where V8 engine version is changed.

**Comment by xbolshe** [comment]
Current V8 version is https://chromium.googlesource.com/v8/v8.git/+/4.8.294
May be there is a reason to introduce V8_VERSION_MOST_SIGNIFICANT and define it like 2 bytes of major version and 2 bytes of minor version. So like 0x00040008. A patch version 294 may be checked separately as needed.

**Comment by ojwb** [comment]
It doesn't seem to be clearly documented anywhere how to actually map a version number to a `V8_VERSION` value, but code and comments in `Lib/javascript/v8/javascripthelpers.swg` imply that 3.19 -> `0x031900`, so with the current scheme 4.5.13.3 -> `0x040513` while 4.51.3.33 -> `0x045103` - i.e. they don't have have same value of `V8_VERSION`.

It looks like this whole mechanism is just to work around V8's API not providing any version macros SWIG's generated code can check:

```
// v8 does not (until now) provide a version macro - which is still discussed and may come soon.
```

It looks like such macros were added in 4.3.0:

https://chromium.googlesource.com/v8/v8.git/+/9dac60ad2d38ae934ea37a5e90096cce8d950e08%5E!/

So really `SWIG_V8_VERSION` should just be deprecated, and `V8_MAJOR_VERSION` and `V8_MINOR_VERSION` checked in preference if they are set.

**Comment by xbolshe** [comment]
But what hexadecimal values will it be for V8 versions 4.5.103.33 and 4.8.294.xx ?

As I see SWIG has internal checks for V8_VERSION_MAJOR = 3 only. And there is a translation V8_VERSION -> JSV8_VERSION -> SWIG_V8_VERSION.

There are 3 ways to know V8 versions:
1. Check V8_MAJOR_VERSION/V8_MINOR_VERSION if version >= 4.3.0
2. Check a provided version string like V8_VERSION_STRING with SWIG internal parsing (but not V8_VERSION, because it cannot store a version number correctly as well as many people provides untrusted values)
3. Check a target NodeJS with V8 engine (like "node -p process.versions.v8")

Way #1 is limited. A lot of applications are written for a version < 4.0.0
Way #3 is the same as Way #2.

**Comment by ojwb** [comment]
> But what hexadecimal values will it be for V8 versions 4.5.103.33 and 4.8.294.xx ?

What values those should be is irrelevant, since we can check `V8_MAJOR_VERSION`, etc for V8 versions >= 4.3.0.  AFAICS, SWIG's `V8_VERSION` only exists because older V8 versions don't provide these macros, and we should just use the macros when they are set.

If any V8 version < 4.3.0 has a third version component > 99, then since the checks done against `V8_VERSION` never actually care about the last two hex digits of `V8_VERSION`, so you can really set them to whatever you like...

We need a preprocessor check, so the third approach doesn't work for this situation - the C preprocessor doesn't allow you to run an external command and inspect its output.

**Comment by xbolshe** [comment]
Here https://github.com/intel-iot-devkit/mraa/pull/363#issuecomment-157535673 and https://github.com/xbolshe/mraa/commit/cf71ec9ad4e100503b9ab098f2b656ceda2979e0 I have tried to get V8_VERSION number using 2 ways: 1) analyze v8-version.h file and 2) command line parameter (a version provided after execution 'node -e "console.log(process.versions.v8)" '.

**Comment by arfoll** [comment]
Thanks for the explanation, very helpful. I think there is a bug, https://github.com/swig/swig/blob/master/Lib/javascript/v8/javascriptrun.swg#L58, 0x032318 is then v8 3.35.24. Node 0.12.17 which is on v8 3.28.71 I think that seems like a better version. I've checked and if I change SWIG_V8_VERSION manually to 0x032319 in the wrapper then it builds well for 0.12.17.

Hopeflly that made sense :)

**Comment by ojwb** [comment]
I think `0x032318` is actually 3.23.18.  The format isn't documented anywhere I can see, but there is this comment and code in `Lib/javascript/v8/javascripthelpers.swg` (as I mentioned above):

```
// Note: since 3.19 there are new CallBack types, since 03.21.9 the old ones have been removed
#if (SWIG_V8_VERSION < 0x031903)
```

So `0x31903` is presumably `3.19.3` (not `3.25.3` as your hex interpretation would make it).

**Comment by arfoll** [comment]
Damn so whilst it has 0x it's not hex at all :/ Thanks!

**Comment by xbolshe** [comment]
Or it may be a version 3.190.3.  There is no unique version definition using decimal values as a string.

**Comment by xbolshe** [comment]
To move forward I think need to define a clear policy regarding V8_VERSION future and describe it in /Lib/javascript/v8/javascriptruntime.swg. It will allow to plan a migration of all SWIG related projects to new V8_VERSION definition.

**Comment by ojwb** [comment]
> Or it may be a version 3.190.3. There is no unique version definition using decimal values as a string.

It clearly isn't 3.190.3 - each pair of hex digits is a component of the version.  If each component took a variable number of digits as you suggest, that clearly doesn't work, but that's a strawman argument - nobody has suggested it should mean that except you.

The idea of representing a version number in a hex number like this is nothing new - many other C and C++ libraries provide something like this, which is because it makes for much clearer preprocessor conditional checks:

```
#if FOO_VERSION > 0x040506
```

versus:

```
#if FOO_MAJOR_VERSION > 4 || (FOO_MAJOR_VERSION == 4 && (FOO_MINOR_VERSION > 5 || FOO_MINOR_VERSION == 5 && FOO_PATCHLEVEL >= 6))
```

I certainly agree the format used should be documented.

The sanest migration plan I can see is essentially that SWIG should just use `V8_MAJOR_VERSION` and `V8_MINOR_VERSION` if they are defined.  There's no point coming up with our own new format when V8 has since added a native one.
