### ISSUE TITLE
Bad constant value with comparison in a #define

### ISSUE THREAD

**Issue by kankaristo** [swig/swig#635]
I'm getting `Warning 305: Bad constant value (ignored)` with a simple comparison in a `#define`.

``` c
// swig_test.i

%module test

#define TEST_A 1
#define TEST_B 2

// Warning 305: Bad constant value (ignored).
#define TEST_C (TEST_A < TEST_B)

// Warning 305: Bad constant value (ignored).
#define TEST_D (TEST_A > TEST_B)

// No warning for any of these
#define TEST_E (TEST_A <= TEST_B)
#define TEST_F (TEST_A >= TEST_B)
#define TEST_G (TEST_A == TEST_B)
#define TEST_H (TEST_A != TEST_B)

// No warning
#if (TEST_A < TEST_B)
#define TEST_I 1
#else
#define TEST_I 0
#endif
```

**Comment by ojwb** [comment]
The parser doesn't currently handle `<` and `>` as less-than and greater-than.  The relevant lines in `Source/CParse/parser.y` are commented out:

```
/* Sadly this causes 2 reduce-reduce conflicts with templates.  FIXME resolve these.
               | expr GREATERTHAN expr {
		 $$.val = NewStringf("%s < %s", $1.val, $3.val);
		 $$.type = cparse_cplusplus ? T_BOOL : T_INT;
	       }
               | expr LESSTHAN expr {
		 $$.val = NewStringf("%s > %s", $1.val, $3.val);
		 $$.type = cparse_cplusplus ? T_BOOL : T_INT;
	       }
*/
```

#80 is another consequence of this.

I suspect it'll need some non-trivial parser changes to fix this.

**Comment by kankaristo** [comment]
Why does it work in an `#if` but not in a `#define`?

Could all instances of `A < B` in a `#define` be automatically replaced with `!(A >= B)` (and the same for `>`)? This would be an ugly workaround and not a real fix, though.

P.S.
Sorry about the spam (the commit references above). GitHub doesn't seem to play nicely with rebasing, so I removed the link from the commit message.

**Comment by ojwb** [comment]
I think it works in `#if` because that's a "preprocessor expression", and there's no ambiguity there.

Values in `#define` are parsed as C/C++ expressions, not preprocessor expressions.

I don't think trying to manipulate the expression to work around this is a sane solution.  For a trivial case like `A < B` it's easy to do, but to handle arbitrary expressions you'll need to actually parse the expression, and I suspect it's likely to end up being a similar amount of work to just fixing the parser properly, but is a hacky solution which misbehaves in corner cases (e.g. in C++, `operator<` may be defined for the types involved, but `operator>=` might not be), and it wouldn't solve #80.

**Comment by ojwb** [comment]
Solved by the commit above - seems github doesn't understand "FIxes #n and #m" so it wasn't closed automatically.
