### ISSUE TITLE
Extra "enum" keyword when inheriting templated class which contains enum class parameter

### ISSUE THREAD

**Issue by zhiqiangxu** [swig/swig#675]
It can be reproduced with the following interface in both version 3.08 and the in-developing 3.09:

```
%module ReactHandler
enum class DispatchMode
{
    Base,
    Process,
    Remote,
    Proxy
};

template <DispatchMode m>
class DispatcherClientServer
{
};

%template(SoaProcessDispatcherClientServer) DispatcherClientServer<DispatchMode::Process>;

%inline %{
    class SoaProcessDispatcherServer : public DispatcherClientServer<DispatchMode::Process>
    {
    };
%}
```

Swig will generate an extra "enum" keyword, which causes syntax error:

`‘Process’ in ‘enum class DispatchMode’ does not name a type`

The problem code is:

```
static void *_p_SoaProcessDispatcherServerTo_p_DispatcherClientServerT_DispatchMode__Process_t(void *x, int *SWIGUNUSEDPARM(newmemory)) {
    return (void *)((DispatcherClientServer< enum DispatchMode::Process > *)  ((SoaProcessDispatcherServer *) x));
}
```

It compiles if manually change `< enum DispatchMode::Process >` to `< DispatchMode::Process >`

**Comment by ojwb** [comment]
I think this was already reported in #464.

**Comment by ojwb** [comment]
Still present in current git master.

**Comment by wsfulton** [comment]
I thought this might be a bug in Visual C++ given the information in #464 but the error message reported here is actually a gcc error message. The bug is not present with Java nor C# because they don't have the type tables for this upcast, so this test case is a scripting language problem.

@ojwb, I see you have a few 'extra-enum' github labels, I presume this is to mark out similar/same issues.

**Comment by ojwb** [comment]
> I see you have a few 'extra-enum' github labels, I presume this is to mark out similar/same issues.

Yes - as you must have noticed by now I've been trying to reduce the ticket mountain to manageable proportions - there were quite a lot of tickets that had been fixed since or were duplicates, and some that were easy to just address.  In the process I noticed quite a lot of bugs where SWIG generates code that doesn't compile due to an extra `enum`, so it seemed useful to tag them.  This should at least help identify which are duplicates of one another and to spot if a new report is actually a duplicate.  Hopefully it'll also help trying to actually solve them.  If nothing else it gives a ready made collection of potential testcases for a candidate fix, and a list of tickets which might be solved by a fix.
