### ISSUE TITLE
[Python] cannot import swig module in package using swig >= 3.0.9

### ISSUE THREAD

**Issue by m7thon** [swig/swig#691]
I have a SWIG python module named `module` that lives in a python package `pkg`. When swigging with swig 3.0.9, the module fails to load properly (using python 3.4).

Here is a minimal example:

```
mkdir pkg
echo "%module module" > module.i
echo "from . import module" > pkg/__init__.py
swig -python -builtin -outdir pkg module.i
gcc -shared -o pkg/_module.so module_wrap.c -I/opt/local/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m -L/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m -lpython3.4m
python -c 'import pkg'
```
gives:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mthon/dev/swigtests/pkg/__init__.py", line 1, in <module>
    from . import module
  File "/Users/mthon/dev/swigtests/pkg/module.py", line 42, in <module>
    from _module import *
ImportError: No module named '_module'
```

Without the `-builtin` option the above example seems to work, <strike>but `_module` nevertheless fails to import.</strike>

EDIT: Actually, this may indeed only be a problem when using `-builtin`, but I am unsure. mromberg mentions [here](https://github.com/swig/swig/pull/612#issuecomment-205490592) that he anticipated this failing and wants to use this code snippet
```
if __name_.rpartition('.')[0] != '':
    from ._foo import *
else:
    from _foo import *
```
This is essentially the code that fails, however, in my above example the wrapper code that is generated lacks a `.`:
```
if __name__.rpartition('.')[0] != '':
    from _module import *
else:
    from _module import *
```
Adding that '.' manually seems to do the trick. Don't know why that didn't make it into the pull request.

**Comment by wsfulton** [comment]
@mromberg, can you look at this please? Looks like this regression is due to #612.

**Comment by mromberg** [comment]
I have a branch in my repo which now has four new tests:

https://github.com/mromberg/swig/tree/impfix

  The new tests are Examples:
https://github.com/mromberg/swig/tree/impfix/Examples/python/import_packages/split_wrapper

  Right now two of the tests fail.  These are the cases where the swig generated module are split and 1/2 is in a python package and the other half is global.  I think these two failing tests cover the known regressions in swig with the implicit namespace package support.  I will submit a pull request on my branch once I've updated swig to make all tests pass.

**Comment by m7thon** [comment]
Great, thanks.

While you are at it, may I request to be extra thorough:

- Your "builtin" test (which is not split) currently fails on python 3 without the `-py3` switch. Even if this use is not intended, it complies with the current swig documentation and used to work with swig 3.0.8. *Pleeese* just fix this case, too.

- Also, as suggested by William, you should probably include tests with
    ```c++
    %pythonbegin %{
    from __future__ import absolute_import
    %}
    ```
    This possibility is also mentioned in the swig documentation [here](http://www.swig.org/Doc3.0/SWIGDocumentation.html#Python_absimport), but currently also fails with `-builtin` and python 2 (but works when using python 2.7 together with the `-py3` option...)

**Comment by mromberg** [comment]
I've yet to update swig itself in my branch.  I'm writing the tests first.  So, yes.  Some of the tests do fail at this time.  After I have updated swig itself, they should all pass.   If anyone knows of a case they do not cover I'll gladly add one.

  Specifically the builtin case that is not split does fail right now and is in there to reproduce the same conditions this bug report is about.   So, it should be expected to fail (with python3) until swig is updated in my branch. 

  The __future__ thing is an interesting idea.  Right now I don't think swig generates any code that does this.  So, I don't think there is a need to test it.

  It is an interesting idea to reduce the complexity of the runtime tests for various python versions in order to deduce the correct import syntax.   Swig could just add the "from __future__ ..." bit to the top of the wrapper and then always use absolute imports.  But I don't know how far back in time (python version wise) that will work.  And I am not brave enough to do it now.

**Comment by mromberg** [comment]
I'll update what I said about the from __future__ thing.  I don't think swig itself generates this code.  But the documentation does talk about a user of swig adding this to the interface file which would cause the wrapper to contain the line.  And this will have implications on the import syntax used by all the swig code which follows.

  Which I think means that a simple test for the python version is not enough because now there is another branch in the logic.  Is it python2.5?  Or is it python2.5 with future absolute imports?  I don't even know how one would tell if the statement "from __future__ import absolute_import" has been run in the current module.  And if it has been added to the module should the swig wrapper code continue to fall back to searching the global namespace if _foo is not found in the absolute package?  I'll think about this...

  It is another area that I bet is not currently covered by the swig test suite.

**Comment by mromberg** [comment]
Currently, every test in the Examples tree that uses python3 also gives swig the -py3 argument.  This means that pretty much every package related test in swig for python3 is done using this switch.   Which is why this bug was passed over.  The switch is added to the Examples/Makefile which all the submakes use.   I'll look into forcing a test or tests to not use this switch with python3.

  At some point I would guess that it would be reasonable break the distinction between python2 and python3 as far as swig is concerned.   The language itself is not backwards compatible.   Right now one can (with some effort) make code that works for both python2 and python3.  But as python3 evolves, how much longer should this be done?

  William mentioned that the -py3 switch was not optional with swig and python3.  But the docs do seem to support the idea of it only adding extra python3 only features.  Yet, at least all the Examples, only build/run with python3 and the -py3 switch.   So, the use of -py3 as being optional is not tested by swig in the Examples.

  To me the python2/python3 boundary seems like a good point for swig to do the same thing python did and make a split.  Otherwise the swig wrappers will always have to work in the strange world that is both python2 and python3.

**Comment by wsfulton** [comment]
The Travis tests have numerous additional Python tests. In particular '-py3 -builtin' and '-py3' are tested by setting the ```SWIG_FEATURES``` env variable so there is no need to add tests with these flags as they will be set in separate Travis runs. You can see which combinations are used from .travis.yml or looking at the output of a run at https://travis-ci.org/swig/swig.

**Comment by mromberg** [comment]
SWIG_FEATURES is nice to know about.  Thanks!  It looks like Examples/Makefile pays no attention to this.  It simply looks at PY3 and adds -py3 to SWIGPYTHON.  All the examples I've seen use Examples/Makefile to actually do the work.  So, every test in Examples pays no attention to any of the travis SWIG_FEATURES flags.  Which means that none of the python package tests use anything but -py3 with python3.

**Comment by m7thon** [comment]
How about replacing the statement that used to be inserted with `-builtin`:

    from _foo import *

with the following more general code snippet:

```python
for attr in _foo.__all__:
    globals()[attr] = getattr(_foo, attr)
```

This should always work, since:

* `_foo` is a variable referring to the *already imported* C extension module. We don't care if imported as a submodule or globally
* when using `-builtin`, SWIG will always add the `__all__` attribute to the extension module and list the public interface
* this is precisely what `from _foo import *` is intended to do, namely to make the attributes from the already imported module `_foo` that are listed in `_foo.__all__` accessible at the scope of the shadow module.

No more case distinctions needed for the additional code inserted by `-builtin` :-)

**Comment by mromberg** [comment]
Does your block of code work with all of the versions of python supported by swig?
for attr in _foo.__all__:
    globals()[attr] = getattr(_foo, attr)

  This sure looks cleaner than another messy import.   I'm just not sure if __all__ is implemented with C modules and if doing that operation with globals() works on all the pythons.  If it does then it seems the better option.  I'm just not sure if it works in all the cases.  And I don't think the swig test suite covers all of them.

  On that note, I've added four more tests to by branch.  These tests are copies of the four originals with the change that each makefile forces the removal of the -py3 switch when the test is run with python3.  So, many of them fail now just like this bug report shows.  It is kinda ugly and brute handed.  But the alternative is modifying the whole Examples test suite to be aware of SWIG_FEATURES.  That may break even more stuff.

**Comment by m7thon** [comment]
Yes, `__all__` is added by SWIG to C extension modules when using the `-builtin` flag [here](https://github.com/swig/swig/blob/6a1efc6c1d5738c4f9291d97c51b50d28eb7a025/Lib/python/pyinit.swg#L447-L456).

And yes, `globals()` is available for all of python 2 and 3, see the docs [here] (https://docs.python.org/2/library/functions.html#globals), and it is ok to modify it according to [this SO question and answer](http://stackoverflow.com/questions/5958793/is-it-safe-to-modify-the-output-of-globals).

**Comment by wsfulton** [comment]
SWIG_FEATURES is read by the swig executable, so it does not appear in the Makefiles, nor should it. See ```swig -help```
```
Options can also be defined using the SWIG_FEATURES environment variable, for example:

  $ SWIG_FEATURES="-Wall"
  $ export SWIG_FEATURES
  $ swig -python interface.i

is equivalent to:

  $ swig -Wall -python interface.i
```
All the examples under import_packages should support python2 and python3 tests like for example relativeimport1 does. The examples and test-suite use the PY3 env variable to handle this (calls 2to3 and invokes swig with -py3 and runs python code with python3 interpreter) ... I didn't realise there were some in the import_packages directory that didn't support the PY3 env variable, but they need to!

Travis sets ```SWIG_FEATURES``` and ```PY3``` and this is how the combinations of -builtin and -py3 are handled by the examples and test-suite.

**Comment by mromberg** [comment]
I don't think there is anyway to "unset" -py3 via SWIG_FEATURES after it has been set on the command line.  Examples/Makefile (the template used by most/all the examples) sets SWIGPYTHON and it adds -py3 as a command line option.   So, I think all of the examples are always built with -py3 for python3.  The case of using python3 but not giving swig the -py3 argument are never tested (by the examples at least).

**Comment by wsfulton** [comment]
We don't test using -py3 with python2 and we don't test python3 without -py3. Because this is not intended, despite what the docs say (I do believe they are wrong).

**Comment by mromberg** [comment]
>>>>> " " == William S Fulton <notifications@github.com> writes:

     > We don't test using -py3 with python2 and we don't test python3
     > without -py3. Because this is not intended, despite what the
     > docs say (I do believe they are wrong).

  Nice!  That simplifies things.  I'll remove the new tests that
remove the -py3 switch for python3.

Mike

**Comment by wsfulton** [comment]
@m7thon can you please check that latest swig master which includes #694 fixes this for you?

**Comment by m7thon** [comment]
Yes, that fixes it. Thanks!
