### ISSUE TITLE
[Python] %nondynamic nonsense

### ISSUE THREAD

**Issue by m7thon** [swig/swig#719]
This issue is for discussion about the "nondynamic" feature for Python, which currently is:
- not really documented
- unclear what it should do and not do (wrt. static/class variables and inheritance)
- broken (e.g., with `-modern -fastproxy`)
- annoying
- useless
- un-pythonic ("we're all consenting adults here")

In the interest of sanity of everyone involved, this "feature" should probably be removed asap.

**Comment by m7thon** [comment]
@mromberg: A better way to implement this for modern classes is to create a non-dynamic base class `_swig_non_dynamic_class` that all non-dynamic classes inherit from. The `_swig_non_dynamic_class` can then use whatever metaclass black magic it likes and be defined using a Python version switch.

**Comment by mromberg** [comment]
I agree with most all of your points.  I have been able to get all of its tests passing with the -O option with python2 and python3 in #718 .  I'm not sure if I will go down the road of fixing it for -classic.  I am not even sure if classic classes support metaclasses.

  The nondynamic thing might be useful in an application that stored or serialized data in some way where you want to ensure any "stored" data goes through a function instead of just being saved as an object attribute.  But, all the other points you make are valid.

  I'd especially like to point out the almost complete lack of documentation for most of the python features (here I mean %feature).  The autodoc and directors are covered.  But almost every other feature is lacking any docs at all.  The main swig docs describe what a feature is and then refer the user to the language specific section for details on the features for that language.  In python's case, there is not much there.  I'm not trying here to point fingers or anything.  Just pointing out that a swig user would have no way to know about them or figure out how they work other that looking at the source.

  For swig 3.1, I think it would be a good thing to create a list of both command line arguments and features.  This list could note the current working state of both the functionality and the documentation for each.  It might help prune those that don't work (or don't play well with others).

  On the play well, with others bit.  William has already mentioned the fifty or so command line arguments the python module supports.  Testing all the possible permutations of these (along with all the mostly undocumented features) is pretty intractable.   The python module is in desperate need of consolidation and pruning.  Dropping support for python versions even the python developers don't support any longer would help here.

   After a list of all options and features is created then it could be determined which stay and which go.  And I think it would be nice to have the end result be just a handful of options left for python.  Something along the lines of (-python2, -python3, -O, -builtin).  Here all the other options would either be rolled into one of these or dropped. 

  And features that are worth keeping could be documented or dropped.  This might even be a good way to determine how much they are needed.  If no one cares enough to document them then...  :)

Mike

**Comment by m7thon** [comment]
> The nondynamic thing might be useful in an application that stored or serialized data in some way where you want to ensure any "stored" data goes through a function instead of just being saved as an object attribute.

Cudos for actually trying hard to come up with a possible use for this, but I don't buy it. By *disallowing* new attributes you are somehow *enabling*, erm, what exactly?

**Comment by m7thon** [comment]
Just as another point, here is a quote appearing [here](https://bytes.com/topic/python/answers/820611-decorator-prevent-adding-attributes-class) from the original author of the Python recipe that this "feature" is based on:

> Of course using frozen [=nondynamic] classes is not Pythonic at all, and I wrote the recipe as
a proof of concept, not to use it.
>
> Michele Simionato

Ok, I'll stop ranting about this.

**Comment by ahnolds** [comment]
Completely agree on dropping this feature - I went down a rabbit hole several months ago trying to get the -O tests working after I looked at -classic, and I basically stopped in part because after days of thought and several pages of notes, I couldn't decide what the "right" thing to do in this case is.  The only real solution I came up with was a terrible hack that ensured the type of a variable was _swig_property before letting you set it.

Oh, and I'm pretty sure the way metaclasses work for old style classes is substantially different if it is available at all.  But since I would strongly favor dropping -classic as well in 3.1.x, that probably is irrelevant.

**Comment by ojwb** [comment]
Another data point - the `nondynamic` feature appears to be unused by anything packaged for Debian:

https://codesearch.debian.net/search?q=python%3A*dynamic&perpkg=1

The current matches are swig itself, 3 packages due to pygments providing syntax highlighting for SWIG interface files, and astrometry.net which explicitly specifies some types as dynamic, e.g.:

```
%pythondynamic qfits_header;
```

That presumably is a no-op at present, but is perhaps an argument for leaving a dummy `%pythondynamic` in place if/when nondynamic is removed.

**Comment by ojwb** [comment]
Is there consensus on removing `%nondynamic` support?  If we're going to remove it, 4.0 is a good time to do so; if we're going to keep it, this ticket should be closed.

**Comment by ojwb** [comment]
I've added this to the 4.0 milestone, to make sure that we actually decide.

**Comment by ojwb** [comment]
Nobody has spoken up in favour of keeping it in nearly 2 years and several people are in favour of dropping it.  I've just run into it trying to clean up the mess of Python options for 4.0.0, so I'm going to remove it now.

**Comment by wsfulton** [comment]
Whoa not so fast! I'm not convinced this is okay at all. Will take a closer look and get back later.

**Comment by mromberg** [comment]
I have a (now foggy) memory about this.   The nondynamic stuff looks more important than it is.   And in some way, it is important for the same reason :).   If I recall, more or less *ALL* python attribute access passes through functions for this feature regardless of the feature being enabled or not.   It is a mess.

  And the swig code would benefit from removing it.   But it will not be simple surgery.   The end result will be worth it however as the end state will be a clean path for setting and getting attributes from swig wrapped objects.   

  The mess is further complicated by the use of python meta classes.   And very few people really understand those fully enough to competently work with them.   It would be good if swig generated code did not include these meta classes if it does not have to.   One of the benefits of the swig code is that one can fairly easily examine the swig output and see what is going on behind the scenes.

**Comment by ojwb** [comment]
> Whoa not so fast! I'm not convinced this is okay at all. Will take a closer look and get back later.

Two years of nobody speaking up against a proposed removal is too fast?

I'll hold off for now, but this really seems like a feature nobody uses or wants, and it complicates things internally.

**Comment by ojwb** [comment]
The incompatibility between nondynamic and `-O` seems to be more specifically with `-modern` (which AIUI tells SWIG to use the style of classes which Python has supported since Python 2.3).

**Comment by wsfulton** [comment]
It is fixed for -modern now, so I'm closing this issue. See #718. 

Whatever one thinks of the merits of %pythonnondynamic, it has some logic behind it and I can see it might be useful to replicate the C++ functionality being wrapped (C++ is inherently non-dynamic). If someone wants to use %pythonnondynamic they are welcome to, it is entirely optional. The addition of metaclasses only occurs when using %pythonnondynamic as per the original frozen recipe it claims to implement so the complexity of the implementation is confined to the usage of this feature.

**Comment by kwwette** [comment]
I know it's bad form to comment on old/closed issues, but it case there's future debate about whether to keep this feature - please do! I intend to use it in [LALSuite](https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/1988) -- indeed I would have been using it a long time ago had I known it existed, it's unfortunate it's not better documented.
