### ISSUE TITLE
C# director delegates are generated with public modifier instead of internal

### ISSUE THREAD

**Issue by dhoegerl** [swig/swig#748]
Hello altogether! I was wondering why my generated director delegates (SwigDelegateXX) are generated with 'public' modifier instead of internal and searched on the internet. What I found was the original SWIG documentation containing an example for C++ to C# here: http://www.swig.org/Doc3.0/SWIGDocumentation.html#CSharp_directors

But if I run this example using swig v3.0.10 I observe the same issue -> I get generated SWIG delegates for the 'Base' class with 'public' modifier instead of the 'internal' which should be the default according to the documentation. So my question is whether this is a bug in the latest SWIG versions (also tested negative with 3.0.7) or how can I change the generated modifier to 'internal' ?

Best regards, Daniel

**Comment by wsfulton** [comment]
My recollection is a bit hazy, but I think they are public by default because the C# compiler optimized them away. I couldn't replicate this so may be wrong. Rather than risk changing this, I've added in a new feature to customize the access modifiers for the delegate, such as:
```
%feature("csdirectordelegatemodifiers") MyClass::myFunction "internal"
```
see the commits referenced above.
