### ISSUE TITLE
SwigPyIterator value is always base class

### ISSUE THREAD

**Issue by ldlchina** [swig/swig#775]
I have classes A, B, C in C++. B and C are derived from A. And I have function in c++ returns vector of B and C: like `std::vector<A*> getAllObjects()`. I use swig to generate Python wrapper. Then I call getAllObjects() in Python as below:

```
objects = getAllObjects()
for obj in objects:
    if isinstance(obj, B):
        print("OK")
    elif isinstance(obj, C):
        print("OK")
```

The object I get from iterator is instance A, but it should be B or C. How to resolve the problem?

**Comment by ldlchina** [comment]
I got a workaround from http://stackoverflow.com/questions/39202265/swigpyiterator-value-is-always-base-class.
Can we consider it's a swig defect or as designed? Shouldn't it return the real type of the object?

**Comment by wsfulton** [comment]
This is more by design than not. It is a trade off favouring simplicity and performance over being feature rich and strictly correct. This could be changed with a dynamic_cast to every possible type in the inheritance hierarchy to find out the real C++ type whenever a type is obtained from the C++ layer. This would be very slow with very little benefit. If this is important for you though, then you can write this manually using the similar approach described in the Java chapter http://swig.org/Doc3.0/Java.html#Java_adding_downcasts. The equivalent to isinstance in C++ is dynamic_cast, so you could just create some C++ functions wrapping dynamic_cast and wrap those and call them instead of isinstance. I suggest you also try the "director" feature as this is a more feature rich approach to handling polymorphic types.
