### ISSUE TITLE
shared_ptr for node javascript

### ISSUE THREAD

**Issue by pcdeadeasy** [swig/swig#798]
Hi, Is there a plan to support this for javascript in the near future?

**Comment by ojwb** [comment]
SWIG is a project build by volunteers, so it's really down to when someone contributes a patch for it.

**Comment by wsfulton** [comment]
There is a patch for this available, see #236. It needs some work before it can be added to master.
Closing ticket as there the aforementioned patch already.

**Comment by karanchadha90** [comment]
Hi,
How do I check if this patch has made into the master yet ? I am just starting with swig and I already have the interface file for C++ to Java, but I need to compile for Javascript now. And swig is giving me an error for "unable to find 'std_shared_ptr.i'" and thought it might be related to this, since there is no shared ptr support for Javascript yet. Any information will be helpful

**Comment by wsfulton** [comment]
If you monitor changes in the aforementioned Github issue you can track when/if it gets to master. It shouldn't be hard for someone familiar with Javascript and C++ shared_ptr to convert the Java testcase into one that works for Javascript. Take this as a plea for help too as you could ensure it gets merged by converting the testcases as mentioned in the ticket.
