### ISSUE TITLE
Swigged structures do not throw a KeyError when trying to assign a value to a non-member

### ISSUE THREAD

**Issue by surhudm** [swig/swig#799]
I have a C++ code with a simple structure like this:
```
# In file a.h
struct test{
double a;
double b;
} ;
```

and I used swig to wrap this code into python (an empty `a.cpp` which just includes `a.h` and a vanilla `a.i` file). Then in python,

```
str = a.test()
str.c = 5.0
```
does not generate any error, even though `c` is not a member of the struct. Shouldn't the python code throw a KeyError in this case? Instead it just adds a new member `c` to the `str.__dict__ `. 

This can cause unintended consequences, which should be possible for swig to catch, see e.g., surhudm/aum#9 .

**Comment by surhud** [comment]
I decided to take a look at the python code that swig generates and noticed that I should be changing one line:

```
__setattr__ = lambda self, name, value: _swig_setattr(self, test, name, value)
```
to 
```
__setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, test, name, value)
```

A Google for nondynamic swig brought me to #719 where I discovered the nondynamic feature which will work for my case, only to find out that the issue is advocating dropping this feature entirely. I guess the original motivation for nondynamic started with exactly the same problem (see [here](https://bytes.com/topic/python/answers/820611-decorator-prevent-adding-attributes-class)), an inadvertent bug caused by setting a value to a non-existing member.

**Comment by ojwb** [comment]
I think this is more of a Python feature than a SWIG bug - you can add arbitrary attributes to Python objects, so that's also true when those objects are part of a SWIG-generated wrapper:

```
>>> class Foo: pass
... 
>>> a = Foo()
>>> a.test = 'hello'
>>> a.test
'hello'
```

**Comment by surhudm** [comment]
I see, I guess there is a choice on whether to emulate the behaviour in C++ or python. I understand the problem then, and somehow there needs to be argument checking handled in the c++ code.
