### ISSUE TITLE
PHP7: libkolabxml generated with swig causes error "zend_mm_heap corrupted"

### ISSUE THREAD

**Issue by tpokorra** [swig/swig#859]
First I want to thank you @ojwb for adding PHP7 support!

I have built a swig package from git master a week ago (07b7edcd87ff3d01e5791556a72906f1225594d9), and built libkolabxml with it.
That package makes use of swig to create the php bindings. That worked fine.

The SRPMs for swig and libkolabxml are here: https://tpokorra.fedorapeople.org/kolab/Kolab_16/

But now when I install those modules, I get when I execute any php call, eg. even `php --version` (this is Fedora 25):

```
PHP 7.0.14 (cli) (built: Dec  7 2016 10:01:29) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
zend_mm_heap corrupted
```

A workaround would be to call this beforehand: `export USE_ZEND_ALLOC=0`, but I guess that is not a proper solution.

My question is, how can I debug this, and help finding the cause for this?

**Comment by ojwb** [comment]
Have you tried running the crashing commands under valgrind?

If that doesn't help, cutting down the interface file to produce a minimal self-container reproducer is probably the best approach.  If that process doesn't make the issue clear, then it gives something much easier to poke at.

**Comment by javitonino** [comment]
Hi,

I have also been trying to get kolabformat to work on PHP7 and I've been able to reproduce the issue here. I tried your suggestion of using valgrind and I couldn't find anything kolab specific in the output, only errors within what seems to be PHP code. So I tried removing stuff from the interface file until I eventually got to an empty interface file, which stills reproduces the error.

With the following interface file:
```
/* kolabformat.i */
%module kolabformat
%{

%}
```

this is the valgrind output: https://gist.github.com/javitonino/d99989e32aa88f6c3888a8158a14a23d
Using PHP 7.0.14 and swig 5919e9c3c7f699339fad1e659b4009e2d279f2cd

I also tried adding `#define SWIGRUNTIME_DEBUG` to the interface file, and I get:
```
SWIG_InitializeModule: size 0
**** SWIG_InitializeModule: Cast List ******
**** SWIG_InitializeModule: Cast List ******
PHP 7.0.14 (cli) (built: Dec 28 2016 23:37:34) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

Not sure if any of this sheds some light.

**Comment by ojwb** [comment]
Works for me, using the SWIG git repo with HEAD at the same commit as you and with the same PHP version even:

```
$ cat test.i
/* kolabformat.i */
%module kolabformat
%{

%}
$ ../preinst-swig -php7 test.i
$ gcc -fPIC -Wall -Wno-unused -shared `php-config7.0 --includes` test_wrap.c `php-config7.0 --ldflags --libs` -o kolabformat.so
$ php7.0 -n -d safe_mode=off -d enable_dl=on -d extension_dir=$PWD -r 'include "kolabformat.php";'
$ php7.0 --version
PHP 7.0.14-1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.14-1, Copyright (c) 1999-2016, by Zend Technologies
```

The above is on Debian - I guess you're running Arch from the valgrind output?  I guess there might be distro-specific patches applied to the PHP packages, or perhaps you're building the module a different way?

Does `make check-php-test-suite` in the SWIG source tree pass for you?

**Comment by javitonino** [comment]
Thanks for taking a look @ojwb. Yes, I'm running Arch, and I can replicate the same behaviour as you are getting running your commands. The test suite passes, no problems reported (aside from a couple of warnings with overloaded classes).

The problem seem to be in loading the extension from the config file (instead of loading it with `dl`). Easiest way to reproduce is running: `php -n -d extension_dir=$PWD -d extension=kolabformat.so --version` which segfaults in my system.

**Comment by ojwb** [comment]
Thanks, that reproduces.

It seems to be the `swig_runtime_data_type_pointer` constant - there's no seg fault if I change:

```
  REGISTER_MAIN_LONG_CONSTANT(const_name, (long) pointer, 0);
```

to

```
  REGISTER_MAIN_LONG_CONSTANT(const_name, (long) pointer, CONST_CS | CONST_PERSISTENT);
```

(`CONST_CS` isn't needed to fix this, but there's no good reason for this constant to have a case-insensitive name that I can see).

Not sure if that's the appropriate fix, but hopefully it'll at least allow you to test more.

**Comment by ojwb** [comment]
"Advanced PHP Programming" by George Schlossnagle says (page 530):

> Obviously, if you are defining constants during module initialization, you must specify `CONST_PERSISTENT`.

and also at the start of the next page it recommends using `CONST_CS` too, so I've added both of those flags here.

Interestingly this code has been there for well over a decade, and seems to work fine with PHP4 and PHP5, but I've corrected this in the PHP5 backend too.

**Comment by javitonino** [comment]
The fix seems to work ✨. I rebuilt the kolabformat module with the latest swig and no more segfaults for me. Thanks!
