### ISSUE TITLE
Nested classes not supported in XML

### ISSUE THREAD

**Issue by ianba3** [swig/swig#874]
Using 3.0.11, nested classes are not generated when outputing -xml, though I expect XML can handle this nicely.

In particular:

`class A
{
  public:
  class B
  {
  public:
    float b;
  };
};`

When %feature("flatnested") is used, flattened classes are generated.

Thanks,
Ian.

**Comment by ojwb** [comment]
Nested classes are a feature which requires per-target-language support and the XML "target language" doesn't support them.

It doesn't get a lot of attention in general, and it's really a case of if you want it to do something you probably need to contribute a patch I'm afraid (unless/until someone steps forward to actively maintain it).

Here are all the changes to `Lib/xml` and `Source/Modules/xml.cxx` in the last decade:

```
*  2d871655 2016-09-27 15:15:47 +1300  Update xml.cxx to return typenames (#777)
*  a950d130 2016-08-05 11:52:35 +1200  [xml] Fix how the output filename is built
*  7841a0d0 2013-01-12 01:21:16 +0000  Remove cvs/svn Id strings
*  7b58300c 2012-07-21 22:52:30 +0000  Fix display of pointers on 64 bit systems, only 32 bit values were being shown.
*  39d8882a 2012-04-13 06:18:21 +0000  Apply #3513569 which adds a catchlist to the xml output
```

The 2013 one was a mechanical removal of cvs/svn leftovers across the whole codebase, so that's really only 4 changes in 10 years.

**Comment by wsfulton** [comment]
Previously the parse tree contained just the forward class declaration for nested classes, the `<classforward>` XML element as nested class support had not been turned on during parsing for `-xml`. The nested class support has now been turned on so that the nested classes appear in the parse tree in a `<class>` XML element.

Note that the `-xmlout` option always generated the nested classes when used with a target language that supported nested classes (such as with `-java`).
