### ISSUE TITLE
Templated class method in %extend

### ISSUE THREAD

**Issue by sethrj** [swig/swig#876]
It seems that creating a templated method inside a class using the `%extend` directive is only partly supported. A function is generated, but the `wrap:action` is wrong. Consider the following example:
```c++
%module test

class Foo
{
public:

%extend {
    template<typename T>
    void do_stuff(int a, T b)
    {
        $self->do_stuff_impl(a, b, 4.0);
    }
}

};

%template(do_stuff_inst) Foo::do_stuff<double>;
```

The wrapper code generated (included example is for `-java`) attempts to call an *actual* method called `do_stuff` on the instance of `Foo` instead of instantiating the content of the `%extend` function:
```c++
SWIGEXPORT void JNICALL Java_testJNI_Foo_1do_1stuff_1inst(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jdouble jarg3) {
  Foo *arg1 = (Foo *) 0 ;
  int arg2 ;
  double arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Foo **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (double)jarg3; 
  (arg1)->SWIGTEMPLATEDISAMBIGUATOR do_stuff< double >(arg2,arg3);
}
```

**Comment by pjohangustavsson** [comment]
Isn't that the behaviour to expect, though? I really don't see what's wrong because `do_stuff_inst` is just like the template it is made of a member of Foo, so yes it will be called on Foo* objects due to `do_stuff_inst`'s hidden *this argument. `do_stuff_inst` is only a name SWIG uses towards the target language. The line which calls do_stuff<double> both creates the real function code during compilation, the linker makes it callable during execution. 

The templated method is non-static, so yes, all instances of this templated method will also become class members. Templates in C++ are compiler constructs and can't exist outside C++ which, so what SWIG does is to wrap all instantiated templates as wrapper functions with names Java understands, such as  `do_stuff_inst()` which becomes a wrapper function around `(Foo*)->do_stuff< double >()` in the form of a JNI-native wrapper function JNI only have require a symbol address reference and call.

**Comment by ojwb** [comment]
@pjohangustavsson No - `(arg1)->SWIGTEMPLATEDISAMBIGUATOR do_stuff< double >(arg2,arg3);` is clearly wrong as the C++ class `Foo` has no `do_stuff` method.

SWIG can't actually magically add a method to an existing C++ class, so at the C++ level `%extend` works by creating a non-class function which takes an extra first parameter (`self`) of type "pointer to the class being extended".  This non-class function is then wrapped to look as if it's a class method in the target language.

So the code generated here should be something like:

```
  arg1 = *(Foo **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (double)jarg3; 
  Foo_do_stuff_inst(arg1,arg2,arg3);
```

@sethrj What I'm not clear about though is why you're trying to use a template here (perhaps because this is a cut down example) - what benefits does the template give you a normal extend method?

```
%module test

class Foo
{
public:

%extend {
    void do_stuff(int a, double b)
    {
        $self->do_stuff_impl(a, b, 4.0);
    }
}

};
```

**Comment by wsfulton** [comment]
At first I thought this a little crazy, but I suspect the motivation for using a template here would be the same for using a template function instead of a non-template function more generally. I've fixed this and it turned out to be much simpler than I imagined. Will commit soon.

The corrected code is almost as @ojwb mentioned, but also has the SWIG template name mangling:
```
  arg1 = *(Foo **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (double)jarg3; 
  Foo_do_stuff_Sl_double_Sg_(arg1,arg2,arg3);
```

**Comment by wsfulton** [comment]
b538070016e46e463b3897fbdb75e1ae995f936e fixes this

**Comment by ojwb** [comment]
@wsfulton Wow, impressively simple.

**Comment by wsfulton** [comment]
I tweaked the commit a bit and have now also added in support for static template methods and template constructors in %extend.

**Comment by sethrj** [comment]
Thanks @wsfulton . You got it exactly: there was a template member function in the C++ code that needed to be wrapped (to have its interface changed slightly); so having a templated `%extend` method would be ideal.
