### ISSUE TITLE
CFFI: Merge glycerine/swig-cpp-to-cffi-for-common-lisp-enhancements

### ISSUE THREAD

**Issue by gitfoxi** [swig/swig#877]
Back in 2011 someone named Jason wrote some some nice codes, resolving issues with CFFI that persist in the mainline today. At least, his work will close #868.

https://github.com/glycerine/swig-cpp-to-cffi-for-common-lisp-enhancements

I attempted to merge it, but too much time has passed and I'm not good enough with git. I think I can make something that merges his changes and doesn't lose the 5 years of improvements. But, I don't think I can avoid losing his history.

This is because he starts by checking everything out from SVN and making his own git repo with an extra level of path hierarchy. To make matters worse he checks in a lot of CCache stuff then removes it, then checks it in again.

Then there's the question of whether I have permission. I've asked here: https://github.com/glycerine/swig-cpp-to-cffi-for-common-lisp-enhancements/issues/1

**Comment by wsfulton** [comment]
Probably you ought to spend a few hours improving git knowledge to achieve a merge including history. Some ideas... 
1)  Use git format-patch to create the 50 odd patches, and apply them to the same revision that the fork from svn was done. These should apply cleanly. Then use git rebase to tidy up the history removing the CCache mods.
2) Use git format-patch to create the 50 odd patches. Edit them by hand removing the CCache commits. Then apply to a clone of the SWIG repo.

I'll do the above merge into the SWIG repo to get started if you commit to getting the test-suite running for cffi on linux and take up the role of maintainer for cffi, The maintainer role will require at a minimum checking pull requests don't regress the test-suite and then merging them in.

**Comment by gitfoxi** [comment]
I'm willing to take another stab at it right now. In my first, failed, attempt, I discovered that commit 53cdb227ef05f6aa7640494aec18e9e575062110 imports all of SWIG from SVN without history and modifies cffi.cxx in the same commit. Other challenges:

* The build system changed in the last 5 years so edits to `configure.in` need to be applied to `configure.ac`
* Something to do with case-sensitivity in path names. Jason was probably on a Mac (as am I) so `cffi` and `CFFI` interact badly
* This patch comes with some tests but they don't run, probably due to build-system changes

Tell me more about maintainer-ing. I've never done it before but I'd welcome the opportunity. Is there a guide I could read?

**Comment by wsfulton** [comment]
You could create a diff from the svn version to the first version in the glycerine git repo. Create a git branch from the point that glycerine branched and apply that as one commit. Then use the techniques I suggested to apply the remaining commits from the glycerine repo.

I think git is clever enough to deal with the configure.in to configure.ac renaming, so when you merge to/from master, it'll work. You may get some merge conflicts, but they shouldn't be big and won't be anything to do with the renaming.

I don't know why there is both a CFFI and a cffi subdirectory, you'll have to combine them, or maybe one is redundant?? I wouldn't recommend a case insensitive file system for fixing git repos though, so linux would be a simple, better bet. If you don't have linux, I could do this git work to get you going.

There isn't a maintainer document. But the idea in a nutshell is to follow and enforce current coding and testing conventions, ensuring code changes include a test in the test-suite where possible. Any enhancements, should follow other languages w.r.t. features and typemap conventions. This may not be clear to begin with but can be 'discovered' by using another robust SWIG target language, but please ask otherwise. Most background developer info is in the docs in the Docs/Devel directory and http://swig.org/Doc3.0/Extending.html#Extending.  You'll need to follow discussions on the swig-devel mailing list and take responsibility for reviewing/approving cffi patches submitted to Github.  Currently cffi is sub-standard and I have even considered removing it altogether from SWIG. If you have the motivation, you may want to bring it completely up to the standard of the other languages.

If you'd like to take on this maintainer role, I suggest you work on your own Github repo for a short while and when you have a minimal test-suite working, I'll help hook it up to Travis and then we can move your development to the SWiG Github repo.

**Comment by ojwb** [comment]
> There isn't a maintainer document

Not as such, but there are a number of relevant documents under `Doc/Devel/` - sadly they're not all up to date.

BTW, you can look at all the open CFFI issues and PRs (or at least all those that have been tagged appropriately) here:

https://github.com/swig/swig/labels/CFFI

**Comment by wsfulton** [comment]
@gitfoxi will you be able taking this any further?

**Comment by wsfulton** [comment]
CFFI will be completely removed as part of a cleanup in SWIG 4.0.0 as the module has been neglected and does not meet the new standards required to stay in SWIG. See #1437.

Rather disappointingly, the glycerine fork does not have a working test-suite and is still below par. Anyone wishing to use CFFI again can bring it up to the expected standard and then it can be included again.

**Comment by wsfulton** [comment]
Closing all open CFFI issues as CFFI has been disabled, please see #1447.
