### ISSUE TITLE
Inconsistencies around supported C versions in documentation

### ISSUE THREAD

**Issue by saxbophone** [swig/swig#890]
Hi,

On this page (http://www.swig.org/tutorial.html) of the online tutorials, towards the bottom it mentions (in the checklist) that the code must use **ANSI C/C++** syntax.

If I'm not mistaken, _ANSI C_ normally refers to the first standardised version of C (informally referred to as C89/C90 depending on who you ask).

Yet on the features page (http://www.swig.org/compare.html), it clarifies that **SWIG is capable of wrapping all of ISO C99**, which is the next standardised version after C89/ANSI.

I think I noticed other places on the site where the term ANSI was used.

Maybe this can be amended in these places to remove the ambiguity?

**Comment by ojwb** [comment]
What change are you proposing here?  Essentially a global `s/ANSI/ISO/`?

(FWIW, it's not really true that SWIG supports all of ISO C99 - e.g. #635, #300, #241, #45, https://sourceforge.net/p/swig/bugs/429/ are all cases of valid ISO C99 code which SWIG doesn't handle).

**Comment by saxbophone** [comment]
I'm suggesting a change in the documentation to consistently refer to which C standard SWIG supports - is that what you mean by a global `s/ANSI/ISO/`?

Thanks for sending those related issues regarding C99 not being fully supported, that's useful to know.

I realise this issue may a bit pedantic but I think it would reduce the ambiguity greatly and also mean people are less likely to be confused about what standard is accepted.

**Comment by ojwb** [comment]
> If I'm not mistaken, ANSI C normally refers to the first standardised version of C (informally referred to as C89/C90 depending on who you ask).

I'm not sure that's really correct - while the more recent standards were published first by ISO, they've also been adopted by ANSI ("C89" was published first by ANSI, then by ISO the next year, hence "C90").

But I'd certainly be supportive of a global change to refer to them as "ISO C" and "ISO C++", as those are the commonly used names these days (and are valid ways of referring to the original C and C++ standards).

> I'm suggesting a change in the documentation to consistently refer to which C standard SWIG supports

That would be nice, but it rather harder to do - someone would need to go through all the changes in C99 from C90 (and also the changes in C11 from C99) and for each one check if there's anything SWIG needs to do to support it (some language features just aren't relevant to SWIG), or if it's already supported (e.g. I think SWIG has supported `//` comments in C mode as an extension from the early days because GCC did), or if work is needed.

**Comment by wsfulton** [comment]
Web site updated too in swig/www@11f2445ec2a31ddc708cc7bb669d947028749fcb
