### ISSUE TITLE
 SWIG_Python_FixMethods use of strncpy confuses coverity

### ISSUE THREAD

**Issue by srepmub** [swig/swig#893]
the following part of this function triggers a coverity issue:
 
strncpy(buff, "swig_ptr: ", 10);

it warns that buff is not null-terminated after this. which is correct but not a real problem of course, since we continue to write into buff. it might be nice though to use eg memcpy here instead, to avoid tripping up coverity and perhaps make the intent a bit clearer of what we are doing.

**Comment by wsfulton** [comment]
@srepmub, could you please instead supply code patches for Coverity warnings instead of raising issues as these are unlikely to get looked at without more details including file/line numbers and a proposed fix as there is no motivating / real-life problem. Unfortunately we don't have SWIG developers with time to devise fixes as there are lots of real problems to look at. I'm all for squashing Coverity warnings if it helps improve the code base and your involvement will be much appreciated.

**Comment by srepmub** [comment]
thanks, no problem! hope this is fine:

https://gist.github.com/srepmub/a065ae74131512a2fe2af6af786667b2

**Comment by ojwb** [comment]
Please open a PR (pull request) for each proposed patch - then they'll get automatically tested for most supported target languages on 3 platforms.  If you just give us a patch file in a gist, we'd have to do all that testing by hand before we can be confident about merging.

**Comment by srepmub** [comment]
https://github.com/swig/swig/pull/898

btw thanks for your work on xapian.. ^^

**Comment by ojwb** [comment]
#898 merged, closing.

YW.
