### ISSUE TITLE
Python and C++ : Overloading virtual function

### ISSUE THREAD

**Issue by dalgos-adsk** [swig/swig#897]
Hi there,

Need some help, I'm not sure if I'm doing something wrong, if this is an issue or simply a limitation of swig/Python. 
I'm working with C++, say I have a class like:

**Base.h**
```
class A;
class B;
class C;

class Base
{
public:
	Base();
	virtual ~Base();

	virtual bool validateAndSetValue(const A&, const B&);
     virtual bool validateAndSetValue(const A&, const B&, const C&);  
};
```
**Base.cpp**
```
... 
bool validateAndSetValue(const A&, const B&)
{
          // do something
}

bool validateAndSetValue(const A&, const B&, const C&)
{
    // This fct will be deprecated - redirecting to other validateAndSetValue
   validateAndSetValue(A, B);
}
```
Applying swig for Python, I create my python object as 

```
class myPythonNode(Base):
    ...
    
    def validateAndSetValue(self, A, B, C):
        
        // do some cool python stuff
        Base.validateAndSetValue(self, A, B, C)
```

So if I try to simulate my callstack, it would be something like this whenever calling Base.validateAndSetValue(self, A, B, C) :
_module.cxx
```
SWIGINTERN PyObject *_wrap_Base_validateAndSetValue__SWIG_1(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
   ......
 director = SWIG_DIRECTOR_CAST(arg1);
  upcall = (director && (director->swig_get_self()==obj0));
  try {
    if (upcall) {
      result = (arg1)->Base::validateAndSetValue((A const &)*arg2,(B const &)*arg3,(C const &)*arg4);
```
Going to the Base.cpp's `bool validateAndSetValue(const A&, const B&, const C&);`
Which then calls` validateAndSetValue(A, B);`

This is where I'm having a problem. At this point 
_module.cxx
```
bool SwigDirector_Base::validateAndSetValue(A const &arg0, B const &arg1) {
...
#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
  const size_t swig_method_index = 37;
  const char *const swig_method_name = "validateAndSetValue";
  PyObject *method = swig_get_method(swig_method_index, swig_method_name);
  swig::SwigVar_PyObject result = PyObject_CallFunction(method, (char *)"(OO)" ,(PyObject *)obj0,(PyObject *)obj1);
#else
  swig::SwigVar_PyObject result = PyObject_CallMethod(swig_get_self(), (char *)"validateAndSetValue", (char *)"(OO)" ,(PyObject *)obj0,(PyObject *)obj1);  <-- THIS ONE GETS CALLED
#endif
```

Since swig is calling back the python's object, I get an error :
Error: validateAndSetValue() takes exactly 4 arguments (3 given)

Is this something that you have come across before ?

**Comment by Alzathar** [comment]
I have not yet tried to call Python function from C++ code. However, this seems possible by using a [SWIG director class](http://www.swig.org/Doc3.0/Python.html#Python_nn34).

Looking for [SWIG + Python + director](https://encrypted.google.com/search?hl=en&q=SWIG%20%2B%20Python%20%2B%20director) on gogole may help you! 

For example: http://rjp.io/2013/05/07/swigdirectors-subclassing-from-python/

**Comment by ojwb** [comment]
I think @sdalgo is already using directors, since the problem seems to occur in `bool SwigDirector_Base::validateAndSetValue(A const &arg0, B const &arg1)`.

The problem seems to be some interaction between directors and an overloaded method, but without a small, self-contained reproducer (including SWIG command line options used) it's hard to usefully investigate.

**Comment by sdalgo** [comment]
@ojwb @Alzathar thanks for the replies. 
We are working with a very large code base, it would be difficult to give you a sample of our code. Is there any samples (ideally with a C++ virtual class and directors) that I can tweak to demonstrate the issue I am encountering ?
Thanks in advance

**Comment by Alzathar** [comment]
Did you try to add a Python definition for your method that use only two arguments (i.e. `def validateAndSetValue(self, A, B):`)? For example:

```
class myPythonNode(Base):
    ...
    
    def validateAndSetValue(self, A, B):
        
        // do some cool python stuff
        Base.validateAndSetValue(self, A, B)

    def validateAndSetValue(self, A, B, C):
        
        // do some cool python stuff
        Base.validateAndSetValue(self, A, B, C)
```

Like that, the director calls the Python method with only two arguments and this one calls internally the C++ Base method.

**Comment by ojwb** [comment]
@sdalgo There are a number of director testcases - see `Examples/test-suite/director*` - I'd expect all will involve a C++ virtual class, since that's what directors are meant for.

**Comment by sdalgo** [comment]
Hey @ojwb,
I'll work on a small reproducer to show the issue I am encountering. I'll post it here once I got it done. 
@Alzathar, that would work great although last I heard you cant overload in Python :(. let me work on the example and we can see if this is something I am doing wrong

Thanks again for the quick feedback

**Comment by sdalgo** [comment]
[classExampleSwig.zip](https://github.com/swig/swig/files/832002/classExampleSwig.zip)
Hey guys,
Sorry for the late reply. I am attaching a modified version or class/example to show the issue we are having.

We can see here that the internal c++ code is redirecting the move( x ,y ) method to the new implementation. Since the method is virtual, it calls Cube.move(x,y,z) only to find that the number of params is wrong. 
In this case, yes we could use Shape::move( x, y, z), but we dont want to do that. There could be an internal calls that are still using move(x, y) and we want to be redirected to move(x,y,z) with the possibility that the plugin (say Cube or Sphere) has some specific implementation to move(x,y,z), so not call explicitely Shape's move(x,y,z)... 

Here are the commands I have used to compile this :

```
swig -c++ -python example.i
g++ -c -fPIC example.cxx example_wrap.cxx -I/usr/include/python2.7
g++ -shared example.o example_wrap.o -L/usr/lib/python2.7/config -lpython2.7 -o _example.so
```

let me know if you guys need more info.
Thanks in advance for helping me out :) much appreciated

**Comment by sdalgo** [comment]
Hello ? 
Any luck reproducing the issue I have @ojwb @Alzathar 
Thanks

**Comment by ojwb** [comment]
Thanks for the reproducer - I can repeat this with current git master too, and it does appear to be a SWIG bug.

**Comment by ArcEarth** [comment]
## Disambiguate overloaded virtual calls based on function argument count

Hi, guys, I have also encountered this issue.

I have a hack that modified the generated cxx file that allows the director to disambiguate overloaded virtual calls (based on function argument count)

### Limitation
Will not disambiguate overloads if the Python script defined the override method as:
- A function with variadic arguments
- A CFucntion call.

Since Python is not a static typing language, I guess this is the best of what we can do.

### Example
Based on @sdalgo 's classExampleSwig.zip

```c++
// Interface file
class Shape {
public:
    virtual void move(double, double);
    virtual void move(double, double, double);
    //...
};

// Generated director source file
void SwigDirector_Shape::move(double dx, double dy) {
  swig::SwigVar_PyObject obj0;
  obj0 = SWIG_From_double(static_cast< double >(dx));
  swig::SwigVar_PyObject obj1;
  obj1 = SWIG_From_double(static_cast< double >(dy));
  if (!swig_get_self()) {
    Swig::DirectorException::raise("'self' uninitialized, maybe you forgot to call Shape.__init__.");
  }

>>>>>>>>>>>
//overloading based on arg count, see processSwigCode.py for detail
int py_argc = PyObject_GetMethodArgCount(swig_get_self(),"move");
//If arg count (include 'this') missmatch, this is a fake override, go back to base class 
if (py_argc >= 0 && py_argc != 1+2) return this->Shape::move(dx,dy);
>>>>>>>>>>>

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
  const size_t swig_method_index = 0;
  const char *const swig_method_name = "move";
  PyObject *method = swig_get_method(swig_method_index, swig_method_name);
  swig::SwigVar_PyObject result = PyObject_CallFunction(method, (char *)"(OO)" ,(PyObject *)obj0,(PyObject *)obj1);
#else
  swig::SwigVar_PyObject result = PyObject_CallMethod(swig_get_self(), (char *)"move", (char *)"(OO)" ,(PyObject *)obj0,(PyObject *)obj1);
#endif
  if (!result) {
    PyObject *error = PyErr_Occurred();
    if (error) {
      Swig::DirectorMethodException::raise("Error detected when calling 'Shape.move'");
    }
  }
```

**Comment by wsfulton** [comment]
@ArcEarth, your approach doesn't work for the example as the problem is in the 3 argument version of `SwigDirector_Shape::move` not the 2 argument version as `Shape::move` calls `SwigDirector_Shape::move(double dx, double dy, double dz)`:
```c++
void Shape::move(double dx, double dy) {
    cout << "inside shape::move(x, y)" << endl ;
    move(dx, dy, 0); // Call move(x,y,z)
}
```
Although the above may work for C++ classes derived from Shape at compile time, it doesn't work with dynamic languages like Python and @dalgos-adsk should change it to:
```c++
void Shape::move(double dx, double dy) {
    cout << "inside shape::move(x, y)" << endl ;
    Shape::move(dx, dy, 0); // Call move(x,y,z)
}
```
ie, it needs to explicitly call `Shape::move(dx,dy,0)`. 

Alternatively, if you feel you cannot make that change, then you can take the following approach which is similar to what @ArcEarth has put together. When the above function calls `move(dx, dy, 0)`, it attempts to call up into Python, it fails with a TypeError
```
TypeError: move() takes exactly 3 arguments (4 given)

```
SWIG allows you to customise the director error handling with the "director:except" feature. Use this to catch errors of this type and then do what you want, that is call `Shape::move(dx,dy,0)`.
```swig
%feature("director:except") Shape::move(double dx, double dy, double dz) %{
  // custom director except code
  if ($error) {
    std::cout << "Error detected and overriding code" << std::endl;
    if ($error == PyExc_TypeError) {
      PyErr_Clear();
      Shape::move(dx,dy,0);
      return;
    } else {
      Swig::DirectorMethodException::raise("Error detected when calling 'Shape.move'");
    }
  }
%}
```
Results in:
```c++
void SwigDirector_Shape::move(double dx, double dy, double dz) {
  swig::SwigVar_PyObject obj0;
  obj0 = SWIG_From_double(static_cast< double >(dx));
  swig::SwigVar_PyObject obj1;
  obj1 = SWIG_From_double(static_cast< double >(dy));
  swig::SwigVar_PyObject obj2;
  obj2 = SWIG_From_double(static_cast< double >(dz));
  if (!swig_get_self()) {
    Swig::DirectorException::raise("'self' uninitialized, maybe you forgot to call Shape.__init__.");
  }
#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
  const size_t swig_method_index = 1;
  const char *const swig_method_name = "move";
  PyObject *method = swig_get_method(swig_method_index, swig_method_name);
  swig::SwigVar_PyObject result = PyObject_CallFunctionObjArgs(method ,(PyObject *)obj0,(PyObject *)obj1,(PyObject *)obj2, NULL);
#else
  swig::SwigVar_PyObject swig_method_name = SWIG_Python_str_FromChar("move");
  swig::SwigVar_PyObject result = PyObject_CallMethodObjArgs(swig_get_self(), (PyObject *) swig_method_name ,(PyObject *)obj0,(PyObject *)obj1,(PyObject *)obj2, NULL);
#endif
  if (!result) {
    PyObject *error = PyErr_Occurred();
    
    // custom director except code
    if (error) {
      std::cout << "Error detected and overriding code" << std::endl;
      if (error == PyExc_TypeError) {
        PyErr_Clear();
        Shape::move(dx,dy,0);
        return;
      } else {
        Swig::DirectorMethodException::raise("Error detected when calling 'Shape.move'");
      }
    }
    
  }
}

```
The above solution results in similar logic to @ArcEarth's hand modified code, but the effect is the same. 

Anyway, I don't see how this is a bug in SWIG. It is a limitation of dynamic languages like Python which does not support proper method overloading. If you are overriding a method in Python using SWIG directors, you need to handle all the cases available in the base class as Python can only have one method with the same name and can't disambiguate the arguments other than at runtime in the one method. We ought to write some documentation about this, volunteers? 

I can't see SWIG trying to implement something like this by default as it really does depend on how the inheritance hierarchy is designed. In your case, it looks like a derived class' implementation of move *must* call the base class implementation, which is definitely not always the case in OO design. Some users would also want to have the TypeError if the Python method is not correctly defined.

The correct approach is to have one overridden Python method to handle all the overloads like this:
```python
class Cube(example.Shape):
    ...
    def move(self, x, y, z=0):
        print "Inside Sphere move(x,y,z=None)"
        print "doing some cool python stuff specific to Cube"
        example.Shape.move(self, x, y, z)  # Use default base implementation for rest
        print "Successfully moved to %d, %d, %d:" % (x, y, z)
```
but I can see why you are trying to get it to work without modifying the classes already derived from Shape... you are trying to support an API change and provide backwards compatibility.
