### ISSUE TITLE
Incorrect handling of enum based on long long

### ISSUE THREAD

**Issue by andershol** [swig/swig#902]
When generating c# wrapper with this c++ code:
`%module EnumIssue
enum TestEnum : long long { Test = 1LL << 32 };`
the output is, in part, the invalid c#:
`public enum TestEnum {
  Test = 1LL << 32
}`
The output should probably be:
`public enum TestEnum : long {
  Test = 1L << 32
}`
I.e. a single "L" and a single "long" to indicate 64-bit signed in c# as opposed to two in c++.
A similar problem exist with unsigned types.

**Comment by ojwb** [comment]
Still present in current git master.

**Comment by ojwb** [comment]
I've closed https://sourceforge.net/p/swig/bugs/1182/ as a duplicate.  The testcase there was:

```
enum BigNumbers {
  big=(unsigned int)1L, bigger
};
```

**Comment by wsfulton** [comment]
Since af72fbb08b23d6922ba5cd1d44020376a26b4714 for swig-4.2, the generated C# enum will instead be:
```
public enum TestEnum : long {
  Test = 1LL << 32
}
```
So the underlying C# type is now correct (long). SWIG does not attempt to convert the enum values, such as, `1LL << 32`, into C# code. This is generally too hard. It happens to work in this case as `1LL.GetType() == long`. The user is expected to make use of csconst instead to replace the C# enum value with an equivalent valid C# expression, such as:
```swig
%csconstvalue("(long)1 << 32") Test;
```
This is possible in earlier versions of SWIG too. In these earlier versions you can also manually specify the underlying C# enum type with:
```swig
%typemap(csbase) TestEnum "long"
```

This is not a problem, by default, for Java as the enum value is obtained by calling into Java code. If you are using %javaconst, then as documented, also use %javaconstvalue to specify an equivalent Java expression (like csconstvalue shown above).
