### ISSUE TITLE
[C++/Java] Problem when using #define with parentheses (javaconst = 1)

### ISSUE THREAD

**Issue by ricardolyn** [swig/swig#904]
When you have a define in C like this:
```
#define FOO (';')
#define BAR ("bar")
```

Swig will generate this **compile constant** in Java:
```
public final static char FOO = '(;)';
public final static String BAR = "(bar)";
```

It should generate this:
```
public final static char FOO = ';';
public final static String BAR = "bar";
```

Any way to fix? Can anyone point me where I can do the fix (to do it myself)?

Ricardo

**Comment by ricardolyn** [comment]
Any update about this?

**Comment by ojwb** [comment]
Looks like the same issue as #913 - as I suggested there, it may be fall-out from #781.  Finding out if this is a regression would be very useful (2 reports of it in a short space of time makes me suspect it is).

**Comment by ricardolyn** [comment]
@ojwb it happened also on 3.0.10 and 3.0.11

**Comment by ojwb** [comment]
It's not a regression from #781 then.

> Can anyone point me where I can do the fix (to do it myself)?

I had a quick poke.  This gets output in `Source/Modules/java.cxx` by:

```
Printf(constants_code, "%s;\n", Getattr(n, "value"));
```

If I add `Swig_print_node(n);` there then I get:

```
+++ constant - 0x7f75082b9430 ----------------------------------------
| value        - "\'(;)\'"
| constantWrapper:view - "constantDirective"
| constantDirective:value - "(;)"
| feature:except - "0"
| feature:java:const - "1"
| name         - "FOO"
| sym:symtab   - 0x7f75082489b0
| feature:immutable - "1"
| sym:name     - "FOO"
| view         - "constantWrapper"
| feature:java:enum - "typesafe"
| type         - "char"
| rawvalue     - "(;)"
| sym:overname - "__SWIG_0"
| storage      - "%constant"
| constantWrapper:value - "(;)"
| tmap:jstype  - "char"
| 
+++ constant - 0x7f75082b97f0 ----------------------------------------
| value        - "\"(bar)\""
| constantWrapper:view - "constantDirective"
| constantDirective:value - "(bar)"
| feature:except - "0"
| feature:java:const - "1"
| name         - "BAR"
| sym:symtab   - 0x7f75082489b0
| feature:immutable - "1"
| sym:name     - "BAR"
| view         - "constantWrapper"
| feature:java:enum - "typesafe"
| type         - "p.q(const).char"
| rawvalue     - "(bar)"
| sym:overname - "__SWIG_0"
| storage      - "%constant"
| constantWrapper:value - "(bar)"
| tmap:jstype  - "String"
| rawval       - "\"(bar)\""
| 
```

So it looks like this is earlier than that.

I think the problem probably stems from the parser in this rule:

```
/* grouping */
               |  LPAREN expr RPAREN %prec CAST {
                   $$.val = NewStringf("(%s)",$2.val);
                   $$.type = $2.type;
              }
```

That's right for handling a constant expression such as `(1 + 2) * 3` not what we want for `("bar")`.

Just omitting the `()` based on `$2.type` seems like it could break some cases (expressions which aren't a string but involve strings, though I don't have an example to hand).  This could do something special with `rawval` if we generated `rawval` for a `T_STRING` a little earlier (like happens for a `T_WSTRING`), but javaconst actually doesn't use `rawval` (I guess because `rawval` is confusingly not in fact the "raw" value but in C/C++ syntax) and instead uses `value`.  Perhaps we need the parser to also create an actual raw string value, i.e. the characters in the string as a string.

**Comment by ojwb** [comment]
SWIG 4.0.2 avoids this bug by not generating a Java constant by default:

```
  public final static char FOO = xJNI.FOO_get();
  public final static String BAR = xJNI.BAR_get();
```

It still goes wrong in the same way with `%javaconst(1);`.  The docs say "using a `%javaconst(1)` at the top of your interface file is strongly recommended" but also warn "Be careful using the `%javaconst(1)` directive as not all C code will compile as Java code".  This case still seems problematic though as the generated code will compile as Java code (at least in the string case - not sure about a multiple character character literal), but the string contents are silently wrong.
