### ISSUE TITLE
Consider using libclang or libtooling for parsing

### ISSUE THREAD

**Issue by DemiMarie** [swig/swig#918]
SWIG currently uses its own C/C++ parser.  Comments in the source indicate that the parser is very hackish and needs to be cleaned up.

A better solution is libclang.  Since it uses Clang's front-end, it can parse (correctly) anything Clang can handle (which is all of C++14, plus some GNU and Microsoft extensions).  Like Clang itself, libclang is written in clean C++11 and is BSD-licensed

**Comment by vadz** [comment]
It would, of course, be great to switch to using libclang, but it's totally different from the current parser and it risks being very difficult to recreate the current parse tree using it (IMO keeping the current tree structure is the only realistic approach, otherwise 90% of SWIG code would need to be rewritten).

So I'm not really sure it's useful to keep this issue open.

**Comment by wkalinin** [comment]
There is also an issue with operating on partially available/not quite valid input data. I believe this issue was already discussed (possibly not once). Although it is hard to disagree with the initial sentiment, while looking at the parser code.

**Comment by ojwb** [comment]
The parser also needs to deal with SWIG-specific stuff - if you look at `Source/CParse/parser.y` there are rules for things like `swig_directive` (and the 20 or so specific directives under that).

The basic idea of reusing an existing parser (and one that's maintained separately so should get updated for future language changes for us) is rather appealing - it's something I've certainly pondered before, and I bet other have too.  But it does seem like it would inevitably be a fairly large project, and since SWIG is a code-base maintained by volunteers it's not like there's a team of full-time developers sitting waiting to be given things to do.  There's already far more to do than volunteer time available, so if you want to see a change of this sort of scope you're probably going to need to do most of the work yourself, though I'd imagine you'll get plenty of encouragement.

**Comment by wsfulton** [comment]
#1159 has more background info.

**Comment by DemiMarie** [comment]
One other thought I had is to use this pipeline:

- preprocess (use libclang)
- use a variant of the current parser to extract SWIG directives and
replace them with C++11 attributes
- run libclang over the modified header

**Comment by wsfulton** [comment]
Conversion to C++11 attributes would only cover a fraction of the SWIG syntax.

**Comment by ojwb** [comment]
Rather than trying to morph SWIG, I suspect the best approach here is to build a new tool on top of libclang or similar, and design the syntax such that it can all be specified within the syntax available there.  SWIG has a lot of historical baggage which is hard to deal with because doing so would require large coordinated invasive changes across the whole code-base.

C++11 attributes work for some SWIG features, though that probably doesn't help for C code.  Maybe the GCC-compatible `__attribute__` syntax could be used (this could be hidden behind macros).  Or a C++-only tool might be OK - most C API headers these days can probably be parsed as C++ successfully, as they really need to be to be usable from C++ code.

`#pragma SWIG ...` could be used for some other things.

I'm not sure what you could do about incomplete type information.  Perhaps this new tool would just require visibility of everything the compiler would have (which might be more reasonable for a tool built on compiler components).

**Comment by DemiMarie** [comment]
Another option would be to map SWIG contents into doc comments.

**Comment by timotheecour** [comment]
I'd like to mention https://github.com/Syniurge/Calypso by @Syniurge as a project pursuing similar (but not identical) goals: it uses clang and llvm to allow using arbitrary C and C++ code in D, without using any wrapper.
Of course, it's only working with D code so not useful as is for other consumers, but a lot of ideas (and maybe implementation) could be reused.
It's already very powerful, eg I was able to use openCV from D code, without any wrapper.
See https://github.com/Syniurge/Calypso/tree/master/examples for other examples.

**Comment by ojwb** [comment]
> C++11 attributes work for some SWIG features, though that probably doesn't help for C code. Maybe the GCC-compatible __attribute__ syntax could be used (this could be hidden behind macros). Or a C++-only tool might be OK - most C API headers these days can probably be parsed as C++ successfully, as they really need to be to be usable from C++ code.

This point is now moot at least, since C23 adds attributes with the same syntax C++11 used:

https://en.cppreference.com/w/c/language/attributes

> Conversion to C++11 attributes would only cover a fraction of the SWIG syntax.

This is still as true.

I wonder if we should just close this as essentially "wontfix" as it just seems unfeasible to actually achieve.  People will probably keep opening "you should use libclang" issues, but we've had at least two reported even with this open.

**Comment by ojwb** [comment]
> I wonder if we should just close this as essentially "wontfix" as it just seems unfeasible to actually achieve. People will probably keep opening "you should use libclang" issues, but we've had at least two reported even with this open.

Nobody's disagreed, so closing.

**Comment by wsfulton** [comment]
I think this ticket can still be used for discussing clang as a front end parser, it's more a discussion which can evolve over time.

> It would, of course, be great to switch to using libclang, but it's totally different from the current parser and it risks being very difficult to recreate the current parse tree using it (IMO keeping the current tree structure is the only realistic approach, otherwise 90% of SWIG code would need to be rewritten).

Agreed that it would be great to switch to it. SWIG would benefit a lot from using some well maintained C++ front end parser. Most of the hard work and hard to do in another SWIG-like tool is what happens after parsing though. Morphing another tool's parse tree into SWIG's parse tree can't be too hard to achieve. I think this is the basis [CableSwig](https://github.com/gccxml/CableSwig) using gccxml. if we swap out SWIG's parser for something else, it will of course need to be extended to support the additional SWIG syntax (which isn't complicated and not much of an extension to C++). Also needs to have an option not to follow #include only one file deep.

I understand Doxygen has clang/LLVM as an alternative front end parser, see version 1.8.4 in the [Doxygen changelog](https://www.doxygen.nl/manual/changelog.html). The information that Doxygen needs is very similar to what SWIG needs, that is the parsed API, not function bodies etc. Ideally we find a C++ only parser project to work with for extending SWIG syntax into. I have a feeling that clang/LLVM is just too big and is hard to keep up with though and could be quite burden, negating the motivation to switching to a 3rd party parser.
