### ISSUE TITLE
Remove Racket (was MZScheme) support?

### ISSUE THREAD

**Issue by DemiMarie** [swig/swig#920]
MZScheme is now known as Racket, and has (by default) a precise GC.  This requires that all C variables that point to Scheme garbage-collected values must be registered with the GC whenever a GC may occur.

**Comment by ojwb** [comment]
I don't think we've had an active maintainer for SWIG's mzscheme backend for some time, but if you want something fixing, patches with suitable test coverage to give a maintainer without specific knowledge of the language are welcome.  If you're also interested in taking on maintainership, that would be great.

**Comment by ojwb** [comment]
If Racket defaults to precise GC and precise GC requires something that SWIG isn't currently doing, does that mean SWIG-generated Racket bindings have broken behaviour if GC happens?

If so, it seems that's been the case for at least 5 years now...

**Comment by DemiMarie** [comment]
Racket is now based on Chez Scheme, so I doubt the original C API is even present now.

**Comment by ojwb** [comment]
Tests are currently passing in CI using the racket package from Ubuntu 20.04, which seems to be version 7.2+dfsg1-2ubuntu3 (but may just happen not to trigger the precise GC issue).

https://en.wikipedia.org/wiki/Racket_(programming_language) says that racket 8.0 is based on Chez Scheme.  If that means a new and incompatible C API then sadly I suspect that's the nail in the coffin for SWIG's current racket support limping along.

**Comment by DemiMarie** [comment]
I’d be fine with just dropping support entirely.  A missing GC root will typically lead to hard-to-debug memory corruption, and Racket 8.0 would need an entirely new backend based on Racket’s FFI.

**Comment by ojwb** [comment]
At least according to https://en.wikipedia.org/wiki/Racket_features the precise GC has been the default since 2007.

I'm going to convert this ticket to a proposal to demote racket (mostly still known as mzscheme in the SWIG code) to "experimental" status in SWIG 4.1.0 because:

* Since 2007 Racket has defaulted to a precise GC which requires that all C variables that point to Scheme garbage-collected values must be registered with the GC whenever a GC may occur (which SWIG apparently doesn't do).  This will typically lead to hard-to-debug memory corruption.

* The latest release series (Racket 8.0) is based on different Scheme implementation and doesn't support the C API which SWIG uses.

* The last commit to touch mzscheme code (from `git log Lib/mzscheme/ Source/Modules/mzscheme.cxx Examples/test-suite/mzscheme/`) which was not from wsfulton or me, and wasn't a global cleanup or similar seems to have been 2006 (c0082db527a87e5d798324931a1575658b3f0e2d) so we clearly don't have an active maintainer for this target language.

"Experimental" status still means the support is there and usable, but it will flag a warning when used which will might find us a new active maintainer, and if not will at least alert any remaining users to the issues above.

**Comment by ojwb** [comment]
Oh, actually it already has experimental status!

It seems unlikely someone is going to turn up and put the effort into fixing the issue with precise GC now given this it's only relevant for old Racket versions, and support for Racket 8 would probably be best done as a new target language (which would also allow it to be called "racket" everywhere in SWIG), so maybe we should put it out of its misery before 4.1.0.

**Comment by wsfulton** [comment]
Where is the information pointing to Racket 8.0 regarding not supporting the the C API that SWIG uses? I would like to see some info from the Racket site/docs quoted to indicate this. From what I read on the wikipedia links given, the default implementation is changing in version 8. My guess is this implies the older implementation still lives...

> Racket 8.0 marks the first release where Racket with the Chez Scheme runtime system, known as Racket CS, is the default implementation.

If Racket 8.0 does not support the C API we've used until now, then agreed, this language module has reached end of life and can be considered for removal from SWIG, especially if the 'precise GC' really is a problem. Can the 'precise GC' problem not be trivially fixed by registering the appropriate objects?

I think some further feedback from Racket users would help us decide steps forward. The only Github issue discussing Racket that I can see is from @cwbowron so perhaps he can put in an opinion. I suggest emailing the swig-user and swig-devel mailing lists about dropping the language module altogether to help garner opinion from the Racket users community.

**Comment by ojwb** [comment]
Info re 8.0 was mostly from discussion above.

Re "the default implementation" part, I found https://blog.racket-lang.org/2021/01/racket-status.html:

> Although Racket CS will be the default for v8.0, Racket BC will remain available through a “More Installers” link on the download page for the foreseeable future. So, Racket users will still have the option of falling back to the old runtime system and compiler if something goes wrong, or if they need a package that does not yet work on Racket CS.

(Though reading around a bit it clears that "Racket CS" is the future and one of the motivations for the change was a smaller codebase to maintain so I wonder how long they'll actually maintain both in parallel...)

> Can the 'precise GC' problem not be trivially fixed by registering the appropriate objects?

I think the solution can be trivially described, but probably the devil is in the detail of making sure all the places that need amending are dealt with.  With GC you generally can't prove a lack of problems just by testing.

Also, we don't have a SWIG/racket maintainer so who's going to do that work?  You're the only person to actually make **any** mzscheme-specific change since 2006, so are you volunteering?  If not, it seems unlikely we're going to get such a patch contributed.

Anyway, if there's actually something people can use it with still I'm OK to leave the support in place - I just raised it because it seemed from the evidence I'd found that it probably wasn't useful any more and there's a maintenance cost to these crusty target language backends (when making global changes, increased time to build SWIG, extra CI jobs mean CI takes longer to complete, etc).

If we keep it but aren't going to fix the precise GC issue that should really be warned about in the documentation, ideally with a pointer for how to disable precise GC (I'm assuming there's a way since it is described as the "default").

**Comment by wsfulton** [comment]
I don't recall it creating any maintenance problems, so there's no motivation from me to remove it yet. When it stops working in our CI environment, then we can kill it if no new maintainer has stepped forward. Given it work on Ubuntu 20.04, that'll probably be in 2 or 3 years time. Not sure it's worth keeping this ticket open for that long.

**Comment by ojwb** [comment]
> Not sure it's worth keeping this ticket open for that long.

You're probably right - realistically anyone stepping up to fix this is going to do so not because they saw this ticket but because they tried to use SWIG with racket 8 and found it doesn't work.

**Comment by wsfulton** [comment]
Deprecation notice for the removal of MzScheme/Racket added in 322bf68. See #2830.
