### ISSUE TITLE
Generate LuaJIT FFI bindings

### ISSUE THREAD

**Issue by DemiMarie** [swig/swig#921]
On LuaJIT, the FFI is much faster than the Lua-C API, for functions that cannot call back into Lua.

**Comment by ojwb** [comment]
This would essentially be adding a new target language, and new target languages get added to SWIG because someone is keen enough to put in the work - without any further interest at all in LuaJIT support for over 5 years that doesn't seem likely to happen. In particular having an issue open for a new target language is really only useful if it serves as a place for people interested in it to find each other to collaborate, so I'm going to close this ticket now. A good quality patch which fulfilled the criteria for a new target language listed in the manual would still be considered of course.
