### ISSUE TITLE
Generate JRuby bindings

### ISSUE THREAD

**Issue by DemiMarie** [swig/swig#923]
JRuby does not support the C extension API.  Instead, FFI can be used, or a combination of a Java extension (for JRuby) and a JNI library can be used.

**Comment by ojwb** [comment]
FWIW, I don't think we currently claim to support jruby, so this would be a new feature.

It sounds like it's probably a non-trivial amount of work, so if you're keen to see it happen anytime soon, you'll probably need to work on it yourself.

**Comment by ojwb** [comment]
SInce JRuby doesn't support Ruby's C API it's effectively a whole new target language backend (just one where the `_runme.rb` files needed for the testsuite presumably will need little if any work to adapt from an already support language).

New target languages get added to SWIG because someone is keen enough to put in the work - without any further interest at all in JRuby support for over 5 years that doesn't seem likely to happen.  In particular having an issue open for a new target language is really only useful if it serves as a place for people interested in it to find each other to collaborate, so I'm going to close this ticket now.  A good quality patch adding JRuby support which fulfilled the criteria listed in the manual would still be considered of course.
