### ISSUE TITLE
Identifier "self" undefined, masked by SWIGUNUSEDPARM although needed

### ISSUE THREAD

**Issue by jkfindeisen** [swig/swig#967]
I use Python SWIG 3.0.12 on Windows without setting the builtin flag and I get an error during compilation

> identifier "self" is undefined

The self parameter in the function is masked by SWIGUNUSEDPARM, so I guess SWIG falsely determined I don't need self. If I remove it, it compiles and tests indicate everything is fine.

The C++ part is really very simple

```
struct Stack
{
  ...
  Data data()
}
```

and I have a return value typemap

```
%typemap( out ) Data
{
	%try_catch( $result = Python::numpy_array( self, $1 ) ; )
}

```
So what I want is returning a Numpy array representing the data when the data() method of a Stack object is called. The NumPy array needs self and so SWIG should not mask self as unused. How can I achieve that?

**Comment by ojwb** [comment]
It's hard to say for sure without a complete reproducer, but the issue sounds to me to be that this parameter is only used in some situations, and someone overeagerly added `SWIGUNUSEDPARM` to squash compiler warnings.

That works OK in C where `SWIGUNUSEDPARM(x)` expands to `x SWIGUNUSED` and `SWIGUNUSED` is `__attribute__ ((__unused__))` for compilers which support that, but for C++ `SWIGUNUSEDPARM(x)` expands to nothing (because in C++ you can omit the name of a parameter which isn't used).

One option is to change C++ to expand this the same way as C, but that means introducing warnings from C++ compilers for which `SWIGUNUSED` is empty.  Perhaps we need a `SWIGMAYBEUNUSEDPARM(x)` which expands to `x SWIGUNUSED` always.  Or just change this case to use `SWIGUNUSED` directly instead.

Do you have a small, self-contained reproducer?
