### ISSUE TITLE
enhancement - support for swift

### ISSUE THREAD

**Issue by johndpope** [swig/swig#981]

**Comment by ojwb** [comment]
A new language backend is a significant amount of work, and we don't have a team of developers sitting waiting for things to do.  So in practice a new language backend gets added to SWIG because somebody (or some group) who wants it implements it and submits a patch.

You can find the guide to adding support for a new language here:

http://www.swig.org/Doc3.0/Extending.html

**Comment by NaiyerAghaz** [comment]
how to call with swig library we have domain, userauth, password 
Please help me out asap.
