### ISSUE TITLE
default value of -1U not handled like ~0U for constructors

### ISSUE THREAD

**Issue by adl** [swig/swig#993]
The following `test.i` file contains two identical structures, except that the default value of the constructor `-1U` is replaced by the equivalent `~0U`.

```
module test

%inline %{

struct foo
{
  unsigned val_;

  foo(unsigned val = -1U) : val_(val)
  {
  }
};

struct bar
{
  unsigned val_;

  bar(unsigned val = ~0U) : val_(val)
  {
  }
};
%}
```

Then

```
% swig3.0 -c++ -python -py3 -O test.i
% g++ -Wall -O3 --shared -fPIC -o _test.so test_wrap.cxx `pkg-config python3 --cflags --libs
% python3 -q
>>> import test
>>> test.bar()
<test.bar; proxy of <Swig Object of type 'bar *' at 0x7fca2c4eb510> >
>>> test.foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adl/tmp/test.py", line 112, in __init__
    _test.foo_swiginit(self, _test.new_foo(val))
OverflowError: in method 'new_foo', argument 1 of type 'unsigned int'
```

I'd expect both `test.bar()` and `test.foo()` to behave identically.

Strangely, if you declare `bar` and `foo` as functions (i.e., `unsigned foo(unsigned val=-1U)`, and `unsigned bar(unsigned val=~0U)` they work.  It also seems to work well with methods, so I suspect the bug is just with constructors.

(I'm using Swig 3.0.10 from Debian.)

**Comment by wsfulton** [comment]
In swig-3.0.12, both constructors and methods handle it the same. If you add in a function called `func` as you mentioned:
```swig
struct foo
{
  unsigned val_;

  foo(unsigned val = -1U) : val_(val)
  {
  }
  foo* func(unsigned val = -1U)
  {
    val_ = val;
    return this;
  }
};

struct bar
{
  unsigned val_;

  bar(unsigned val = ~0U) : val_(val)
  {
  }
  bar* func(unsigned val = ~0U)
  {
    val_ = val;
    return this;
  }
};
```
The generated code is:
```python
class foo(_object):
    def __init__(self, val=-1):
        this = _example.new_foo(val)
        ...

    def func(self, val=-1):
        return _example.foo_func(self, val)

class bar(_object):
    def __init__(self, *args):
    ...

    def func(self, *args):
        return _example.bar_func(self, *args)
```
You can see that the constructor wrappers are handled the same as the function `func`. The main difference is that SWIG doesn't accept `~0` is valid Python (this is possibly a bug) and so it changes the wrappers to handle the default value in C code rather than Python code. Hence the difference in the wrappers.

When you call bar(), it passes the default Python value `-1U` which is passed to the C layer as `-1` because `-1U` is not valid Python code. The C layer doesn't accept `-1` because this is a negative input for an unsigned type.

If you can't change the default C++ value, (-1U is rather unusual), then I suggest you use `%feature("python:cdefaultargs") foo::foo;` to make the foo constructor use the C default argument handling as a fix. This will make it use `def __init(sefl, *args)` like is in bar.

Anyway, I'll fix for the next version of SWIG.

**Comment by wsfulton** [comment]
Interestingly, the problem didn't occur with global functions such as:
```
void globalfunc(unsigned val = -1U);
```
due to a subtle difference in the generated code which results in the following generated code:
```python
def globalfunc(val=-1):
    return _example.globalfunc(val)
globalfunc = _example.globalfunc
```
The net result is the second `globalfunc` is the one called, bypassing the `def globalfunc(val=-1)` Python function. This is different to member variables which don't have the second function generated.

**Comment by adl** [comment]
Thank you for the fix, and the mention of `python:cdefaultargs`.  
Looking at `convertValue()` from your patch, I realized that another workaround is to simply write `-(1U)` as my default value, and the set of parentheses will prevent `convertValue()` to work,.
